module

public import Mathlib.Analysis.Normed.Field.Krasner

/-!
# Closest conjugates and Krasner's lemma

This file defines when an algebraic element is closer to one element than to all of its
other conjugates, and connects this condition to Krasner's lemma.
-/

@[expose] public section

namespace AlgebraicClosure

/-- `α` is the closest conjugate to `β` if `β` is closer to `α` than to every image of
`α` under a nontrivial `K`-algebra automorphism of the algebraic closure. -/
def IsClosestConjugate (K : Type*) [NormedField K]
    (α β : AlgebraicClosure K) : Prop :=
  ∀ σ : AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K,
    σ α ≠ α →
    spectralNorm K (AlgebraicClosure K) (β - α) <
      spectralNorm K (AlgebraicClosure K) (β - σ α)

/-- A closest-conjugate hypothesis gives the conjugate-root inequality used by Krasner's lemma. -/
theorem IsClosestConjugate.lt_spectralNorm_sub_of_isConjRoot
    {K : Type*} [NontriviallyNormedField K] [IsUltrametricDist K] [CompleteSpace K]
    {α β α' : AlgebraicClosure K} (h : IsClosestConjugate K α β)
    (hconj : IsConjRoot K α α') (hne : α ≠ α') :
    spectralNorm K (AlgebraicClosure K) (α - β) <
      spectralNorm K (AlgebraicClosure K) (α - α') := by
  let _ : NormedField (AlgebraicClosure K) := spectralNorm.normedField K _
  let _ : NormedAlgebra K (AlgebraicClosure K) := spectralNorm.normedAlgebra K _
  have _ : IsUltrametricDist (AlgebraicClosure K) :=
    IsUltrametricDist.of_normedAlgebra K
  rw [isConjRoot_iff_exists_algEquiv] at hconj
  obtain ⟨σ, hσ⟩ := hconj
  have hα' : α' = σ.symm α := by
    rw [← hσ]
    simp
  have hne' : σ.symm α ≠ α := by
    rw [← hα']
    exact hne.symm
  have hclose := h σ.symm hne'
  rw [← NormedAlgebra.norm_eq_spectralNorm K,
      ← NormedAlgebra.norm_eq_spectralNorm K] at hclose ⊢
  subst hα'
  rw [norm_sub_rev α β]
  by_contra hle
  push Not at hle
  have h_ultra : ‖β - σ.symm α‖ ≤ max ‖β - α‖ ‖α - σ.symm α‖ := by
    have : β - σ.symm α = (β - α) + (α - σ.symm α) := by abel
    rw [this]
    exact IsUltrametricDist.norm_add_le_max _ _
  linarith [max_le (le_refl ‖β - α‖) hle]

/-- A closest-conjugate hypothesis places `α` in the field generated by `β`. -/
theorem IsClosestConjugate.adjoin_le
    {K : Type*} [NontriviallyNormedField K] [IsUltrametricDist K] [CompleteSpace K]
    {α β : AlgebraicClosure K} (h : IsClosestConjugate K α β)
    (hsep : IsSeparable K α) :
    IntermediateField.adjoin K {α} ≤ IntermediateField.adjoin K {β} := by
  let _ : NormedField (AlgebraicClosure K) := spectralNorm.normedField K _
  let _ : NormedAlgebra K (AlgebraicClosure K) := spectralNorm.normedAlgebra K _
  have _ : IsUltrametricDist (AlgebraicClosure K) :=
    IsUltrametricDist.of_normedAlgebra K
  rw [IntermediateField.adjoin_simple_le_iff]
  apply IsKrasner.krasner hsep
  · exact IsAlgClosed.splits _
  · exact (Algebra.IsAlgebraic.isAlgebraic β).isIntegral
  · intro α' hconj hne
    simpa only [NormedAlgebra.norm_eq_spectralNorm K] using
      h.lt_spectralNorm_sub_of_isConjRoot hconj hne

end AlgebraicClosure
