module

import MathlibExt.NumberTheory.Padics.CasselsEmbedding
import Mathlib.Basic.Real.Basic

noncomputable section

-- The subring generated by two real numbers embeds in suitable p-adic integers.
example (x y : ℝ) :
    ∃ (p : ℕ) (hp : p.Prime),
      letI : Fact p.Prime := ⟨hp⟩
      3 ≤ p ∧ ∃ phi : Subring.closure (↑({x, y} : Finset ℝ) : Set ℝ) →+* ℤ_[p],
        Function.Injective phi :=
  Subring.exists_injective_ringHom_closure_padicInt {x, y}
