/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Code.Transcription.Comparator
import Code.Transcription.SortSlice
import Code.Transcription.Powerloop
import Code.Transcription.Minrun
import Code.Transcription.MergeState
import Code.Transcription.TempStorageInvariant
import Code.Transcription.MergeInitStorage
import Code.Transcription.ReverseSlice
import Code.Transcription.Binarysort
import Code.Transcription.CountRun
import Code.Transcription.Gallop
import Code.Transcription.MergeMemory
import Code.Transcription.MergeLo
import Code.Transcription.MergeHi
import Code.Transcription.MergeAt
import Code.Transcription.FoundNewRun
import Code.Transcription.MergeForceCollapse
import Code.Transcription.ListSortImpl
import Code.Equivalence.Minrun
import Code.Equivalence.MinrunResults
import Code.Equivalence.Powerloop
import Code.Equivalence.PowerloopResults
import Code.Policy.PendingLayout
import Code.Policy.StackPowers
import Code.Policy.MergeAtPreservation
import Code.Policy.BoundaryPowerGeometry
import Code.Policy.MergeTopPowerPreservation
import Code.Policy.FoundNewRunPreservation
import Code.Policy.StackDepth
import Code.Policy.PushRunPreservation
import Code.Policy.MergeForceCollapsePreservation
import Code.Assembly.AccessTrace
import Code.Assembly.MergeCost
import Code.Assembly.MergeTreeCost
import Code.Assembly.MergePolicyReplay
import Code.Assembly.PowerEntropyBound
import Code.Assembly.PowerTreeEntropy
import Code.Assembly.PowerSortPolicyCost
import Code.Assembly.AlphabeticCostBound
import Code.Assembly.ScanPowerForestInvariant
import Code.Assembly.ListSortScanReached
import Code.Assembly.ListSortMergePolicy
import Code.Assembly.ListSortScanPolicy
import Code.Assembly.ListSortPolicyEndpoints
import Code.Assembly.ListSortPolicyBridge
import Code.Assembly.ListSortCollapseCost
import Code.Assembly.ListSortCostBound
import Code.Assembly.PowerSortCostRegression
import Code.Assembly.SortSliceSafety
import Code.Assembly.ReverseSliceSafety
import Code.Assembly.CountRunSafety
import Code.Assembly.BinarysortSafety
import Code.Assembly.ListSortInputMode
import Code.Assembly.MergeMemcpyProvenance
import Code.Assembly.GallopLeftSafety
import Code.Assembly.GallopRightSafety
import Code.Assembly.MergeGetmemRequestBound
import Code.Assembly.MergeGetmemStorageValid
import Code.Assembly.MergeTracePrimitives
import Code.Assembly.MergeLoSafety
import Code.Assembly.MergeHiSafety
import Code.Assembly.MergeAtSafety
import Code.Assembly.FoundNewRunSafety
import Code.Assembly.MergeForceCollapseSafety
import Code.Assembly.TempStorageLiveness
import Code.Assembly.ListSortSafety
import Code.Assembly.MergeMemorySafety
import Code.Assembly.Order
import Code.Assembly.GallopCorrectness
import Code.Correctness.ReverseSliceCorrectness
import Code.Correctness.PendingRunCorrectness
import Code.Correctness.SortSliceRange
import Code.Correctness.ScanRemainder
import Code.Correctness.DescendingRunNormalization
import Code.Correctness.DescendingRunInvariant
import Code.Correctness.ReverseRangeSupport
import Code.Correctness.EntrySnapshotPermutation
import Code.Correctness.BinarysortCorrectness
import Code.Correctness.CountRunCorrectness
import Code.Correctness.StableMerge
import Code.Correctness.MergeMovementCorrectness
import Code.Correctness.MergeSemanticPre
import Code.Correctness.MergeLoInvariant
import Code.Correctness.MergeLoCorrectness
import Code.Correctness.MergeHiInvariant
import Code.Correctness.MergeHiCorrectness
import Code.Correctness.MergeTargetConsistency
import Code.Correctness.MergeAtCorrectnessSupport
import Code.Correctness.MergeAtCorrectness
import Code.Correctness.FoundNewRunCorrectness
import Code.Correctness.MergeForceCollapseCorrectness
import Code.Correctness.ScanCorrectnessSupport
import Code.Correctness.ScanStepSupport
import Code.Correctness.ScanStepCorrectness
import Code.Correctness.OriginRelabelEquivariance
import Code.Correctness.OriginRelabelMerges
import Code.Correctness.OriginRelabelScan
import Code.Correctness.ReverseModeAlgebra
import Code.Correctness.ScanLoopCorrectness
import Code.Correctness.ReverseScanTransport
import Code.Correctness.ReverseModeCorrectness
import Code.Correctness.OccurrenceErasure
import Code.Correctness.OccurrenceErasureMerges
import Code.Correctness.OccurrenceErasureScan
import Code.Correctness.ListSortCorrectness

/-! Root module for the CPython listsort formalization. -/
