/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import Mathlib.RingTheory.AdjoinRoot
public import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import Mathlib.RingTheory.Ideal.GoingUp
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# Maximal ideals of `AdjoinRoot g` over a local base ring

For `A` a commutative local ring and `g : A[X]`, a maximal ideal of
`AdjoinRoot g` is determined by an irreducible factor of the reduction of `g`
modulo the maximal ideal of `A`. This is the `AdjoinRoot` form of ATLAS
`NumberTheoryI` item N209, Corollary 10.11 (Section 10.1). The English target
is pinned at ATLAS revision `e8b31c5cb0bec89b487ce33fe525a2c0b0f8b9c6`
([N209 / Corollary 10.11, lines 1450-1458](https://github.com/facebookresearch/atlas-lean/blob/e8b31c5cb0bec89b487ce33fe525a2c0b0f8b9c6/v1/Atlas/NumberTheoryI/targets.yaml#L1450-L1458)):
for a local Noetherian ring `A` and a polynomial `g`, it classifies maximal
ideals of `AdjoinRoot g` as the ideals generated by the base maximal ideal and
a lift `q` of an irreducible factor of the reduction of `g`.

Source map to the immutable
[ATLAS Lean implementation](https://github.com/facebookresearch/atlas-lean/blob/e8b31c5cb0bec89b487ce33fe525a2c0b0f8b9c6/v1/Atlas/NumberTheoryI/code/LocalExtensions.lean#L93-L255):

* `AdjoinRoot.maximal_ideal_form` (lines 104-186) proves the forward
  classification, and `AdjoinRoot.exists_irreducible_factor_of_is_maximal`
  is its form here: a maximal ideal `m` yields a lifted polynomial `q` whose
  reduction is irreducible, divides the reduction of `g`, and generates `m`
  together with the base maximal ideal.
* `Polynomial.comap_mapRingHom_bot_eq_map_C_ker` is the reduction-kernel
  identity used by the proof: reduction modulo an ideal kills exactly the
  constant polynomials with coefficients in that ideal.
* This forward theorem replaces the source's `IsNoetherianRing A` plus
  `Module.Finite A (AdjoinRoot g)` assumptions with the sufficient hypothesis
  `Algebra.IsIntegral A (AdjoinRoot g)`, because contraction of a maximal
  ideal is maximal along an integral extension and no Noetherian argument
  is used.
* `AdjoinRoot.is_maximal_of_irreducible_factor` is the reverse clause,
  corresponding to the source `AdjoinRoot.is_maximal_of_irreducible_factor`
  (lines 188-237); it needs no integrality, Noetherianity, or
  module-finiteness assumption.
* `AdjoinRoot.is_maximal_iff_irreducible_factor` combines the two clauses
  under integrality, matching the source `AdjoinRoot.maximal_ideal_iff`
  (lines 239-255), while `is_maximal_iff_irreducible_factor_of_monic`
  specializes it to monic `g`, where integrality is automatic.
* Together these declarations cover the full N209 / Corollary 10.11
  classification in an existential, one-maximal-ideal / one-irreducible-factor
  formulation; they do not package the distinct factors into an enumerated
  finite list.
-/

@[expose] public section

open Polynomial

variable {A : Type*} [CommRing A] [IsLocalRing A]

namespace Polynomial

omit [IsLocalRing A] in
/-- Reduction of polynomials modulo an ideal kills exactly the constant
polynomials with coefficients in the ideal. -/
theorem comap_mapRingHom_bot_eq_map_C_ker (I : Ideal A) :
    Ideal.comap (Polynomial.mapRingHom (Ideal.Quotient.mk I)) ⊥ =
      Ideal.map Polynomial.C I := by
  rw [← RingHom.ker_eq_comap_bot, Polynomial.ker_mapRingHom, Ideal.mk_ker]

end Polynomial

namespace AdjoinRoot

/-- Every maximal ideal upstairs is generated by the base maximal ideal and
a lift of an irreducible factor of the reduced polynomial. -/
theorem exists_irreducible_factor_of_is_maximal (g : A[X])
    [Algebra.IsIntegral A (AdjoinRoot g)] (m : Ideal (AdjoinRoot g))
    [hm : m.IsMaximal] :
    ∃ q : A[X],
      Irreducible (q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∧
        (q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∣
          (g.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∧
        m = Ideal.map (algebraMap A (AdjoinRoot g))
          (IsLocalRing.maximalIdeal A) ⊔
          Ideal.span {AdjoinRoot.mk g q} := by
  have hcomap_max : (m.comap (algebraMap A (AdjoinRoot g))).IsMaximal :=
    Ideal.isMaximal_comap_of_isIntegral_of_isMaximal (algebraMap A (AdjoinRoot g))
      (algebraMap_isIntegral_iff.mpr inferInstance) m
  have hcomap_eq : m.comap (algebraMap A (AdjoinRoot g)) =
      IsLocalRing.maximalIdeal A :=
    IsLocalRing.eq_maximalIdeal hcomap_max
  have hle : Ideal.map (algebraMap A (AdjoinRoot g))
      (IsLocalRing.maximalIdeal A) ≤ m := by
    rw [← hcomap_eq]
    exact Ideal.map_comap_le
  have hsurj : Function.Surjective (Polynomial.mapRingHom
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) := by
    rw [Polynomial.coe_mapRingHom]
    exact Polynomial.map_surjective _ Ideal.Quotient.mk_surjective
  let MM : Ideal A[X] := Ideal.comap (AdjoinRoot.mk g) m
  have hMM_max : MM.IsMaximal :=
    Ideal.comap_isMaximal_of_surjective _ AdjoinRoot.mk_surjective
  have hker_mk : RingHom.ker (AdjoinRoot.mk g) ≤ MM := fun f hf =>
    show (AdjoinRoot.mk g) f ∈ m from (RingHom.mem_ker.mp hf) ▸ m.zero_mem
  have hCp_le : Ideal.map Polynomial.C (IsLocalRing.maximalIdeal A) ≤ MM := by
    rw [Ideal.map_le_iff_le_comap]
    intro a ha
    exact hle (Ideal.mem_map_of_mem _ ha)
  have hker_map : Ideal.comap (Polynomial.mapRingHom
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ⊥ ≤ MM := by
    rw [Polynomial.comap_mapRingHom_bot_eq_map_C_ker]
    exact hCp_le
  have hMMbar_max : (Ideal.map (Polynomial.mapRingHom
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) MM).IsMaximal := by
    have := hMM_max
    apply Ideal.IsMaximal.map_of_surjective_of_ker_le hsurj
    rwa [RingHom.ker_eq_comap_bot]
  have hg_in : g ∈ MM :=
    hker_mk (by rw [RingHom.mem_ker]; exact AdjoinRoot.mk_self)
  have hgbar_in : Polynomial.map
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)) g ∈
      Ideal.map (Polynomial.mapRingHom
        (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) MM :=
    Ideal.mem_map_of_mem _ hg_in
  let : Field (A ⧸ IsLocalRing.maximalIdeal A) :=
    Ideal.Quotient.field _
  obtain ⟨qb, hqb⟩ := IsPrincipalIdealRing.principal (Ideal.map
    (Polynomial.mapRingHom (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)))
    MM)
  have hMMbar_eq : Ideal.map (Polynomial.mapRingHom
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) MM =
      Ideal.span {qb} := hqb
  have hqb_irred : Irreducible qb := by
    have hmax : (Ideal.span {qb}).IsMaximal := hMMbar_eq ▸ hMMbar_max
    have hqb0 : qb ≠ 0 := by
      intro h
      subst h
      exact Ring.ne_bot_of_isMaximal_of_not_isField hmax
        (Polynomial.not_isField (A ⧸ IsLocalRing.maximalIdeal A))
        Ideal.span_singleton_zero
    exact ((Ideal.span_singleton_prime hqb0).mp hmax.isPrime).irreducible
  have hqb_dvd : qb ∣ Polynomial.map
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)) g := by
    rw [← Ideal.mem_span_singleton, ← hMMbar_eq]
    exact hgbar_in
  obtain ⟨q, hq_lift⟩ := Polynomial.map_surjective
    (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))
    Ideal.Quotient.mk_surjective qb
  have hMM_comap : MM = Ideal.comap (Polynomial.mapRingHom
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)))
      (Ideal.map (Polynomial.mapRingHom
        (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) MM) := by
    rw [Ideal.comap_map_of_surjective _ hsurj]
    exact (sup_eq_left.mpr hker_map).symm
  have hMMbar_span : Ideal.map (Polynomial.mapRingHom
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) MM =
      Ideal.map (Polynomial.mapRingHom
        (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)))
        (Ideal.span {q}) := by
    rw [hMMbar_eq, Ideal.map_span, Set.image_singleton]
    simp only [Polynomial.coe_mapRingHom, hq_lift]
  have hMM_decomp : MM = Ideal.span {q} ⊔
      Ideal.map Polynomial.C (IsLocalRing.maximalIdeal A) := by
    rw [hMM_comap, hMMbar_span, Ideal.comap_map_of_surjective _ hsurj,
      Polynomial.comap_mapRingHom_bot_eq_map_C_ker]
  have hmm_map : m = Ideal.map (AdjoinRoot.mk g) MM :=
    (Ideal.map_comap_of_surjective _ AdjoinRoot.mk_surjective m).symm
  refine ⟨q, ?_, ?_, ?_⟩
  · rw [hq_lift]
    exact hqb_irred
  · rw [hq_lift]
    exact hqb_dvd
  · rw [hmm_map, hMM_decomp, Ideal.map_sup, Ideal.map_span,
      Set.image_singleton, Ideal.map_map,
      show (AdjoinRoot.mk g).comp Polynomial.C = AdjoinRoot.of g from rfl,
      ← AdjoinRoot.algebraMap_eq, sup_comm]

/-- An irreducible factor of the reduced polynomial generates a maximal ideal
upstairs together with the base maximal ideal. No integrality hypothesis. -/
theorem is_maximal_of_irreducible_factor (g q : A[X])
    (hirr : Irreducible
      (q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))))
    (hdvd : (q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∣
      (g.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)))) :
    (Ideal.map (algebraMap A (AdjoinRoot g)) (IsLocalRing.maximalIdeal A) ⊔
      Ideal.span {AdjoinRoot.mk g q}).IsMaximal := by
  have hsurj : Function.Surjective (Polynomial.mapRingHom
      (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) := by
    rw [Polynomial.coe_mapRingHom]
    exact Polynomial.map_surjective _ Ideal.Quotient.mk_surjective
  let : Field (A ⧸ IsLocalRing.maximalIdeal A) :=
    Ideal.Quotient.field _
  have hqbar_max : (Ideal.span
      {q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))}).IsMaximal :=
    PrincipalIdealRing.isMaximal_of_irreducible hirr
  have hM_eq : Ideal.span {q} ⊔ Ideal.map Polynomial.C
      (IsLocalRing.maximalIdeal A) = Ideal.comap (Polynomial.mapRingHom
        (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)))
        (Ideal.span {q.map (Ideal.Quotient.mk
          (IsLocalRing.maximalIdeal A))}) := by
    have hspan : Ideal.span
        {q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))} =
        Ideal.map (Polynomial.mapRingHom
          (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)))
          (Ideal.span {q}) := by
      rw [Ideal.map_span, Set.image_singleton]
      simp only [Polynomial.coe_mapRingHom]
    rw [hspan, Ideal.comap_map_of_surjective _ hsurj,
      Polynomial.comap_mapRingHom_bot_eq_map_C_ker]
  have : (Ideal.span {q} ⊔ Ideal.map Polynomial.C
      (IsLocalRing.maximalIdeal A)).IsMaximal := by
    rw [hM_eq]
    exact Ideal.comap_isMaximal_of_surjective _ hsurj
  have hg_in_M : g ∈ Ideal.span {q} ⊔ Ideal.map Polynomial.C
      (IsLocalRing.maximalIdeal A) := by
    rw [hM_eq, Ideal.mem_comap, Ideal.mem_span_singleton]
    exact hdvd
  have hker_le : RingHom.ker (AdjoinRoot.mk g) ≤ Ideal.span {q} ⊔
      Ideal.map Polynomial.C (IsLocalRing.maximalIdeal A) := by
    change RingHom.ker (Ideal.Quotient.mk (Ideal.span {g})) ≤ _
    rw [Ideal.mk_ker, Ideal.span_le]
    exact Set.singleton_subset_iff.mpr hg_in_M
  have hmmax : (Ideal.map (AdjoinRoot.mk g) (Ideal.span {q} ⊔
      Ideal.map Polynomial.C (IsLocalRing.maximalIdeal A))).IsMaximal :=
    Ideal.IsMaximal.map_of_surjective_of_ker_le AdjoinRoot.mk_surjective
      hker_le
  convert hmmax using 1
  show Ideal.map (algebraMap A (AdjoinRoot g)) (IsLocalRing.maximalIdeal A) ⊔
      Ideal.span {AdjoinRoot.mk g q} = Ideal.map (AdjoinRoot.mk g)
      (Ideal.span {q} ⊔ Ideal.map Polynomial.C (IsLocalRing.maximalIdeal A))
  rw [Ideal.map_sup, Ideal.map_span, Set.image_singleton, Ideal.map_map,
    show (AdjoinRoot.mk g).comp Polynomial.C = AdjoinRoot.of g from rfl,
    ← AdjoinRoot.algebraMap_eq, sup_comm]

/-- Classification of maximal ideals of `AdjoinRoot g` over a local ring:
they are exactly the ideals generated by the base maximal ideal and a lift
of an irreducible factor of the reduction of `g`. -/
theorem is_maximal_iff_irreducible_factor (g : A[X])
    [Algebra.IsIntegral A (AdjoinRoot g)] (m : Ideal (AdjoinRoot g)) :
    m.IsMaximal ↔
      ∃ q : A[X],
        Irreducible
          (q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∧
          (q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∣
            (g.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∧
          m = Ideal.map (algebraMap A (AdjoinRoot g))
            (IsLocalRing.maximalIdeal A) ⊔
            Ideal.span {AdjoinRoot.mk g q} := by
  constructor
  · intro hm
    have := hm
    exact exists_irreducible_factor_of_is_maximal g m
  · rintro ⟨q, hirr, hdvd, rfl⟩
    exact is_maximal_of_irreducible_factor g q hirr hdvd

/-- Monic specialization: for monic `g`, integrality is automatic. -/
theorem is_maximal_iff_irreducible_factor_of_monic (g : A[X]) (hg : g.Monic)
    (m : Ideal (AdjoinRoot g)) :
    m.IsMaximal ↔
      ∃ q : A[X],
        Irreducible
          (q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∧
          (q.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∣
            (g.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∧
          m = Ideal.map (algebraMap A (AdjoinRoot g))
            (IsLocalRing.maximalIdeal A) ⊔
            Ideal.span {AdjoinRoot.mk g q} := by
  have := hg.finite_adjoinRoot
  exact is_maximal_iff_irreducible_factor g m

end AdjoinRoot
