/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import Mathlib.Data.List.Basic
public import Mathlib.Data.Nat.Digits.Defs

@[expose] public section

namespace MetaMathlibExt

/-- The Thue–Morse substitution on the binary alphabet: `0 ↦ 01` and `1 ↦ 10`,
where `false` represents `0` and `true` represents `1`.

This is Example 2 in Scott Balchin and Dan Rust, *Computations for Symbolic
Substitutions*, Journal of Integer Sequences 20 (2017):
https://cs.uwaterloo.ca/journals/JIS/VOL20/Rust/rust3.tex. -/
def thueMorseSubstitution : Bool → List Bool
  | false => [false, true]
  | true => [true, false]

/-- The `n`th finite Thue–Morse block, obtained by iterating
`thueMorseSubstitution` from the one-letter word `0`. -/
def thueMorseBlock : Nat → List Bool
  | 0 => [false]
  | n + 1 => (thueMorseBlock n).flatMap thueMorseSubstitution

/-- The zero-indexed Thue–Morse sequence. Its value is the parity of the number
of `1`s in the binary expansion of its index, so evaluation takes time and
space logarithmic in the index rather than constructing an exponentially long
finite substitution block.

The source lists the initial blocks `0`, `01`, `0110`, and `01101001`, and the
limit beginning `0110100110010110`. See Eiji Miyanohara, *Transcendence of
Digital Expansions Generated by a Generalized Thue-Morse Sequence*, Journal of
Integer Sequences 18 (2015):
https://cs.uwaterloo.ca/journals/JIS/VOL18/Miyanohara/miy5.tex. -/
def thueMorse (n : Nat) : Bool :=
  decide ((Nat.digits 2 n).count 1 % 2 = 1)

end MetaMathlibExt
