module

public import Mathlib.Data.Matrix.Basic

/-!
# Hankel matrices

A Hankel matrix is constant on each antidiagonal. The finite definition here is the zero-shift
case of the matrices in Mario Garcia Armas and B. A. Sethuraman,
*A Note on the Hankel Transform of the Central Binomial Coefficients*:
<https://cs.uwaterloo.ca/journals/JIS/VOL11/Sethuraman/sethuraman2.tex>.
-/

@[expose] public section

namespace Matrix

/-- The infinite Hankel matrix generated by `s`, with `(i, j)` entry `s (i + j)`. -/
def hankel {α : Type*} (s : ℕ → α) : Matrix ℕ ℕ α :=
  fun i j ↦ s (i + j)

@[simp]
theorem hankel_apply {α : Type*} (s : ℕ → α) (i j : ℕ) : hankel s i j = s (i + j) :=
  rfl

/-- The finite `n × n` Hankel matrix generated by `s`. -/
def hankelFin {α : Type*} (n : ℕ) (s : ℕ → α) : Matrix (Fin n) (Fin n) α :=
  fun i j ↦ s (i + j)

@[simp]
theorem hankelFin_apply {α : Type*} (n : ℕ) (s : ℕ → α) (i j : Fin n) :
    hankelFin n s i j = s (i + j) :=
  rfl

end Matrix
