/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

import Batteries.Util.ProofWanted
import Mathlib.Algebra.BigOperators.Group.Finset.Defs
import Mathlib.Data.Finset.Interval
import Mathlib.Data.List.Basic

namespace MathlibExt.Combinatorics.PVHHCubeMorphicWordWanted

/-- The alphabet whose symbols carry the integer values `0`, `1`, `3`, and `4`. -/
inductive Letter where
  | zero
  | one
  | three
  | four
  deriving DecidableEq

/-- The substitution `0 ↦ 03`, `1 ↦ 43`, `3 ↦ 1`, `4 ↦ 01`. -/
def substitution : Letter → List Letter
  | .zero => [.zero, .three]
  | .one => [.four, .three]
  | .three => [.one]
  | .four => [.zero, .one]

/-- The `k`-fold substituted image of the initial letter `0`. -/
def substitutionIterate : ℕ → List Letter
  | 0 => [.zero]
  | k + 1 => (substitutionIterate k).flatMap substitution

/-- `w` is the infinite word generated by iterating the substitution from `0`: every finite
iterate is a prefix of `w`. -/
def IsGeneratedFixedPoint (w : ℕ → Letter) : Prop :=
  ∀ k i (hi : i < (substitutionIterate k).length),
    w i = (substitutionIterate k).get ⟨i, hi⟩

/-- The integer represented by a letter. -/
def letterValue : Letter → ℤ
  | .zero => 0
  | .one => 1
  | .three => 3
  | .four => 4

/-- The sum of the values in a factor of `w`. -/
def factorSum (w : ℕ → Letter) (start length : ℕ) : ℤ :=
  (Finset.range length).sum fun i ↦ letterValue (w (start + i))

/-- The word has no three consecutive nonempty factors of equal length and equal letter sum. -/
def AvoidsPVHHCubes (w : ℕ → Letter) : Prop :=
  ∀ start length, 0 < length →
    ¬(factorSum w start length = factorSum w (start + length) length ∧
      factorSum w (start + length) length = factorSum w (start + 2 * length) length)

/-- The fixed point beginning with `0` of the substitution
`0 ↦ 03`, `1 ↦ 43`, `3 ↦ 1`, `4 ↦ 01` avoids every PVHH-cube. -/
def conjecture : Prop :=
  ∃ w : ℕ → Letter, IsGeneratedFixedPoint w ∧ AvoidsPVHHCubes w

/--
Resolved true: Cassaigne, Currie, Schaeffer and Shallit (J. ACM 61 (2014), arXiv:1106.5204,
Theorem 18) prove, via a finite-graph reachability reduction checked by computer, that the fixed
point of 0->03, 1->43, 3->1, 4->01 contains no additive cubes. Source: Julien Cassaigne, James
D. Currie, Luke Schaeffer and Jeffrey Shallit, Avoiding three consecutive blocks of the same
size and same sum, J. ACM 61(2) (2014), Article 10, arXiv:1106.5204,
https://arxiv.org/abs/1106.5204. Moved from `OpenConjectures/Combinatorics/PVHHCubeMorphicWord`.
-/
theorem_wanted conjecture_holds : conjecture

end MathlibExt.Combinatorics.PVHHCubeMorphicWordWanted
