/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

import Batteries.Util.ProofWanted
public import Mathlib.Combinatorics.Additive.ApproximateSubgroup
public import Mathlib.GroupTheory.Nilpotent

namespace MetaMathlibExt

@[expose] public section

open scoped Pointwise

/-- The **Breuillard–Green–Tao structure theorem** (approximate-subgroup form):
a `K`-approximate subgroup `A` of an arbitrary group is controlled by a genuine
subgroup with nilpotent quotient of bounded rank. There is a subgroup `H` with
a normal subgroup `N` such that `H ⧸ N` is nilpotent of bounded class and is
generated by a finite set of bounded size, `N` sits inside a bounded power of
`A / A`, and `A` is covered by `F * H` for a finite set `F` of bounded size.

Sources: S. Machado, *Topics in Geometric Group Theory* lecture notes,
<https://sites.google.com/view/simonmachado/teaching>, Theorem 4.4;
original B. Breuillard, B. Green, T. Tao, *The structure of approximate
groups*, Publ. Math. IHÉS 116 (2012). -/
theorem_wanted breuillard_green_tao_approximate_subgroup {K : ℝ} :
    ∃ C : ℕ, 0 < C ∧
      ∀ {G : Type*} [Group G] [DecidableEq G] (A : Set G)
        (_hA : IsApproximateSubgroup K A),
        ∃ (H : Subgroup G) (N : Subgroup H) (_hD : N.Normal) (F : Finset G)
          (S : Finset (H ⧸ N)),
        Subgroup.upperCentralSeries (H⧸ N) C = ⊤ ∧
          S.card ≤ C ∧
          Subgroup.closure (↑S : Set (H ⧸ N)) = ⊤ ∧
          ((↑) '' (N : Set H) : Set G) ⊆ ((A / A) ^ C) ∧
          F.card ≤ C ∧
          A ⊆ (F : Set G) * (H : Set G)

end

end MetaMathlibExt
