/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

import Batteries.Util.ProofWanted
public import Mathlib.Combinatorics.Additive.DoublingConst
public import Mathlib.Data.Real.Basic
public import Mathlib.GroupTheory.Nilpotent
public import Mathlib.SetTheory.Cardinal.Finite

namespace MetaMathlibExt

@[expose] public section

open scoped Combinatorics.Additive Pointwise

/-- The **Breuillard–Green–Tao structure theorem** (small-doubling form): a
nonempty finite set of bounded doubling in an arbitrary group is controlled by
a subgroup with nilpotent quotient of bounded rank. More precisely, if
`σₘ[A] ≤ K` then there is a subgroup `N` with a normal subgroup `D` such that
`N ⧸ D` is nilpotent of bounded class and is generated by a finite set of
bounded size, `D` sits inside a bounded power of `A / A`, and `A` is covered
by boundedly many cosets of `N`.

Sources: S. Machado, *Topics in Geometric Group Theory* lecture notes,
<https://sites.google.com/view/simonmachado/teaching>, Theorem 1.8;
original B. Breuillard, B. Green, T. Tao, *The structure of approximate
groups*, Publ. Math. IHÉS 116 (2012). -/
theorem_wanted breuillard_green_tao_small_doubling {K : ℝ} :
    ∃ C : ℕ, 0 < C ∧
      ∀ {G : Type*} [Group G] [DecidableEq G] (A : Finset G)
        (_hA_nonempty : A.Nonempty) (_hA : ((σₘ[A] : ℚ≥0) : ℝ) ≤ K),
        ∃ (N : Subgroup G) (D : Subgroup N) (_hD : D.Normal)
          (S : Finset (N ⧸ D)),
          Subgroup.upperCentralSeries (N⧸ D) C = ⊤ ∧
            S.card ≤ C ∧
            Subgroup.closure (↑S : Set (N ⧸ D)) = ⊤ ∧
            ((↑) '' (D : Set N) : Set G) ⊆ ((A / A) ^ 4 : Set G) ∧
            ∃ a : Fin C → G, (A : Set G) ⊆ ⋃ i, a i • (N : Set G)

end

end MetaMathlibExt
