/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import MathlibExt.RingTheory.Localization.AtPrime.Multiplicity
import Mathlib.RingTheory.DedekindDomain.Different

@[expose] public section

/-!
# Tests for ideal multiplicity under localization at a maximal ideal

Examples exercising `IsLocalization.AtPrime.emultiplicity_maximalIdeal_map_eq`:
the generic canonical-localization application, the number-theory
specialization to `differentIdeal A B`, the correction-term specialization to
`Ideal.span {(e : B)}`, and a concrete integer localization at the prime `(5)`.
-/

set_option autoImplicit false

/-- Generic ideal at the canonical localization `Localization.AtPrime p`. -/
example {R : Type*} [CommRing R] [IsDedekindDomain R]
    (p : Ideal R) [p.IsMaximal] (I : Ideal R) :
    emultiplicity (IsLocalRing.maximalIdeal (Localization.AtPrime p))
        (I.map (algebraMap R (Localization.AtPrime p))) =
      emultiplicity p I :=
  IsLocalization.AtPrime.emultiplicity_maximalIdeal_map_eq p I

/-- Number-theory specialization: multiplicity of `differentIdeal A B`. -/
example {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    [IsDomain A] [IsDedekindDomain B] [Module.IsTorsionFree A B]
    (P : Ideal B) [P.IsMaximal] :
    emultiplicity (IsLocalRing.maximalIdeal (Localization.AtPrime P))
        ((differentIdeal A B).map (algebraMap B (Localization.AtPrime P))) =
      emultiplicity P (differentIdeal A B) :=
  IsLocalization.AtPrime.emultiplicity_maximalIdeal_map_eq P _

/-- Correction-term specialization: `I = Ideal.span {(e : B)}`. -/
example {B : Type*} [CommRing B] [IsDedekindDomain B]
    (P : Ideal B) [P.IsMaximal] (e : B) :
    emultiplicity (IsLocalRing.maximalIdeal (Localization.AtPrime P))
        ((Ideal.span {(e : B)}).map (algebraMap B (Localization.AtPrime P))) =
      emultiplicity P (Ideal.span {(e : B)}) :=
  IsLocalization.AtPrime.emultiplicity_maximalIdeal_map_eq P _

/-- Closed primality facts for the integer prime ideal `(5)`. -/
private instance : (Ideal.span {(5 : ℤ)}).IsPrime :=
  Ideal.isPrime_span_singleton_of_prime
    (Int.prime_iff_natAbs_prime.mpr (by decide))

/-- Closed maximality fact for the integer prime ideal `(5)`. -/
private instance : (Ideal.span {(5 : ℤ)}).IsMaximal :=
  (Int.prime_iff_natAbs_prime.mpr (by decide)).isMaximal_span_singleton

/-- Concrete integer localization at the prime ideal generated by `5`: fully
closed, all instances inferred. -/
example :
    emultiplicity
        (IsLocalRing.maximalIdeal
          (Localization.AtPrime (Ideal.span {(5 : ℤ)})))
        ((Ideal.span {(5 : ℤ)}).map
          (algebraMap ℤ (Localization.AtPrime (Ideal.span {(5 : ℤ)})))) =
      emultiplicity (Ideal.span {(5 : ℤ)}) (Ideal.span {(5 : ℤ)}) :=
  IsLocalization.AtPrime.emultiplicity_maximalIdeal_map_eq _ _
