module

public import MathlibExt.Algebra.Lie.WittMultigradedDimension

import Mathlib.Data.Fin.VecNotation

@[expose] public section

namespace MathlibExtTest.Algebra.Lie.WittMultigradedDimension

open scoped BigOperators

open MetaMathlibExt

example (K : Type) [Field K] :
    (Module.finrank K
      (freeLieMultihomogeneousComponent K (![1, 1] : Fin 2 → ℕ)) : ℚ) =
      wittMultigradedValue (![1, 1] : Fin 2 → ℕ) := by
  exact finrank_freeLieMultihomogeneousComponent K (![1, 1]) (by norm_num)

-- The bidegree `(1, 1)` component is generated by the bracket of the two generators.
example (K : Type) [Field K] :
    (Module.finrank K
      (freeLieMultihomogeneousComponent K (![1, 1] : Fin 2 → ℕ)) : ℚ) = 1 := by
  rw [witt_multigraded_dimension_formula K 2 (by omega) (![1, 1]) (by norm_num)]
  have hg : Finset.univ.gcd (![1, 1] : Fin 2 → ℕ) = 1 := by decide
  rw [wittMultigradedValue, show ∑ i, (![1, 1] : Fin 2 → ℕ) i = 2 by decide, hg]
  norm_num [Nat.multinomial]

end MathlibExtTest.Algebra.Lie.WittMultigradedDimension

end
