import MathlibExt.NumberTheory.NumberField.RayClass.Modulus
import Mathlib.RingTheory.DedekindDomain.Factorization
import Mathlib.RingTheory.ClassGroup.Basic

/-!
# Ray groups attached to a modulus (N403 foundation)

Built over `NumberField.Modulus`, whose infinite-place multiplication
uses union, representing truncated exponent addition `min (m v + n v) 1`
(the ATLAS-extracted `max` formula was a typo).
-/

@[expose] public noncomputable section

open scoped nonZeroDivisors

namespace NumberField
namespace Modulus

variable {K : Type*} [Field K] [NumberField K]

/-- Finite-prime support of a modulus: primes dividing the finite part. -/
def finiteSupported (m : Modulus K) (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) : Prop :=
  (m.finitePart : Ideal (𝓞 K)) ≤ v.asIdeal

/-- Exponent of the finite part of a modulus at a finite prime. -/
def finiteExponent (m : Modulus K) (v : IsDedekindDomain.HeightOneSpectrum (𝓞 K)) : ℤ :=
  FractionalIdeal.count K v
    ((m.finitePart : Ideal (𝓞 K)) : FractionalIdeal (𝓞 K)⁰ K)

/-- Fractional ideals coprime to the finite part of a modulus. -/
def coprimeFractionalIdeals (m : Modulus K) :
    Subgroup (FractionalIdeal (𝓞 K)⁰ K)ˣ where
  carrier :=
    { u |
      ∀ v, finiteSupported m v →
        FractionalIdeal.count K v (u : FractionalIdeal (𝓞 K)⁰ K) = 0 }
  one_mem' := by
    intro v _
    rw [Units.val_one]
    exact FractionalIdeal.count_one K v
  mul_mem' := by
    intro a b ha hb v hv
    rw [Units.val_mul]
    rw [FractionalIdeal.count_mul K v (Units.ne_zero a) (Units.ne_zero b)]
    rw [ha v hv, hb v hv, add_zero]
  inv_mem' := by
    intro a ha v hv
    rw [Units.val_inv_eq_inv_val]
    rw [FractionalIdeal.count_inv K v (a : FractionalIdeal (𝓞 K)⁰ K), ha v hv, neg_zero]

theorem mem_coprimeFractionalIdeals_iff (m : Modulus K)
    (u : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    u ∈ coprimeFractionalIdeals m ↔
      ∀ v, finiteSupported m v →
        FractionalIdeal.count K v (u : FractionalIdeal (𝓞 K)⁰ K) = 0 :=
  Iff.rfl

/-- Elements of `Kˣ` whose principal ideal is coprime to the modulus. -/
def rayElements (m : Modulus K) : Subgroup Kˣ :=
  Subgroup.comap (toPrincipalIdeal (𝓞 K) K)
    (coprimeFractionalIdeals m)

theorem mem_rayElements_iff (m : Modulus K) (x : Kˣ) :
    x ∈ rayElements m ↔
      toPrincipalIdeal (𝓞 K) K x ∈
        coprimeFractionalIdeals m :=
  Subgroup.mem_comap

/-- Congruence `x ≡ 1` at the finite part of a modulus. -/
def CongruentOneAtFinitePart (m : Modulus K) (x : Kˣ) : Prop :=
  ∀ v, finiteSupported m v →
    (x : K) = 1 ∨
      finiteExponent m v ≤
        FractionalIdeal.count K v
          (FractionalIdeal.spanSingleton (𝓞 K)⁰ ((x : K) - 1))

/-- Positivity at the real places selected by a modulus. -/
def PositiveAtInfinitePart (m : Modulus K) (x : Kˣ) : Prop :=
  ∀ w : RealPlace K, w ∈ m.infinitePart →
    InfinitePlace.embedding_of_isReal w.property (x : K) > 0

/-- Ray elements congruent to `1` modulo `m`. -/
def IsRayElementOne (m : Modulus K) (x : Kˣ) : Prop :=
  x ∈ rayElements m ∧ CongruentOneAtFinitePart m x ∧ PositiveAtInfinitePart m x

theorem IsRayElementOne.mem_rayElements {m : Modulus K} {x : Kˣ}
    (h : IsRayElementOne m x) : x ∈ rayElements m :=
  h.1

theorem IsRayElementOne.congruent {m : Modulus K} {x : Kˣ}
    (h : IsRayElementOne m x) : CongruentOneAtFinitePart m x :=
  h.2.1

theorem IsRayElementOne.positive {m : Modulus K} {x : Kˣ}
    (h : IsRayElementOne m x) : PositiveAtInfinitePart m x :=
  h.2.2

/-- Principal generators coming from elements congruent to `1` mod `m`. -/
def rayGenerators (m : Modulus K) : Set (coprimeFractionalIdeals m) :=
  { y |
    ∃ x : Kˣ, ∃ hx : IsRayElementOne m x,
      (⟨toPrincipalIdeal (𝓞 K) K x,
        Subgroup.mem_comap.mp hx.1⟩ :
        coprimeFractionalIdeals m) = y }

/-- Subgroup generated by the ray generators: the ray group. -/
def rayGroup (m : Modulus K) : Subgroup (coprimeFractionalIdeals m) :=
  Subgroup.closure (rayGenerators m)

theorem rayGenerators_mem_of_isRayElementOne (m : Modulus K) (x : Kˣ)
    (hx : IsRayElementOne m x) :
    (⟨toPrincipalIdeal (𝓞 K) K x,
      Subgroup.mem_comap.mp hx.1⟩ :
      coprimeFractionalIdeals m) ∈ rayGenerators m :=
  ⟨x, hx, rfl⟩

theorem mem_rayGroup_of_isRayElementOne (m : Modulus K) (x : Kˣ)
    (hx : IsRayElementOne m x) :
    (⟨toPrincipalIdeal (𝓞 K) K x,
      Subgroup.mem_comap.mp hx.1⟩ :
      coprimeFractionalIdeals m) ∈ rayGroup m :=
  Subgroup.subset_closure (rayGenerators_mem_of_isRayElementOne m x hx)

theorem rayGroup_closure_le {m : Modulus K}
    {H : Subgroup (coprimeFractionalIdeals m)}
    (h : rayGenerators m ⊆ (↑H : Set _)) : rayGroup m ≤ H :=
  (Subgroup.closure_le H).2 h

theorem congruentOneAtFinitePart_one (m : Modulus K) :
    CongruentOneAtFinitePart m 1 := fun _ _ => Or.inl rfl

theorem positiveAtInfinitePart_one (m : Modulus K) :
    PositiveAtInfinitePart m 1 := by
  intro w _
  rw [Units.val_one, map_one]
  exact one_pos

theorem isRayElementOne_one (m : Modulus K) : IsRayElementOne m 1 :=
  ⟨one_mem _, congruentOneAtFinitePart_one m, positiveAtInfinitePart_one m⟩

end Modulus
end NumberField
