/-
Author: @toskua, Avocado
-/

module

import MathlibExt.RingTheory.AdjoinRoot.LocalMaximal
public import Mathlib.RingTheory.AdjoinRoot
public import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.RingTheory.Polynomial.Eisenstein.Distinguished
public import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.DiscreteValuationRing.TFAE

/-!
# Eisenstein extensions of discrete valuation rings

ATLAS source: NumberTheoryI N221, Lemma 11.4, pinned at revision
`e8b31c5cb0bec89b487ce33fe525a2c0b0f8b9c6`.
Target statement: `v1/Atlas/NumberTheoryI/targets.yaml`, lines 1555--1560.
Primary Lean source: `v1/Atlas/NumberTheoryI/code/EisensteinRamified.lean`,
lines 49--177, with final source theorem `adjoinRoot_eisenstein_isDVR`,
lines 141--175.

## Source-to-API map

The source DVR `A` and monic Eisenstein polynomial `f` are the same parameters
here. `AdjoinRoot f` represents `A[x]/(f)`, and `AdjoinRoot.root f` is the
source uniformizer. The public API maps to the source as follows:

- `AdjoinRoot.isLocalRing_of_isEisensteinAt` derives locality;
- `AdjoinRoot.isLocalRing_maximalIdeal_eq_span_root` identifies the maximal
  ideal with the root span;
- `AdjoinRoot.isDiscreteValuationRing_of_isEisensteinAt` is the full
  N221/Lemma 11.4 DVR conclusion;
- `AdjoinRoot.irreducible_root_of_isEisensteinAt` records the uniformizer
  irreducibility consequence.

Scope: this module covers the full N221/Lemma 11.4 target for monic
positive-degree Eisenstein polynomials over a DVR. It strengthens the ATLAS
implementation by deriving the locality and maximal-ideal hypotheses that ATLAS
assumes in its final theorem.
-/

@[expose] public section

open Polynomial Ideal IsLocalRing

namespace AdjoinRoot

variable {A : Type*} [CommRing A]

/-- The image of the constant coefficient of `f` lies in the span of the root. -/
lemma algebraMap_coeff_zero_mem_span_root (f : A[X]) :
    algebraMap A (AdjoinRoot f) (f.coeff 0) ∈ Ideal.span {root f} := by
  have heval := eval₂_root f
  rw [Polynomial.eval₂_eq_sum_range] at heval
  rw [Finset.sum_range_succ'] at heval
  simp only [pow_zero, mul_one] at heval
  rw [add_comm] at heval
  have hcoeff0 := eq_neg_of_add_eq_zero_left heval
  rw [algebraMap_eq, hcoeff0]
  apply neg_mem
  apply Ideal.sum_mem
  intro i _
  apply Ideal.mul_mem_left
  rw [pow_succ']
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)

end AdjoinRoot

namespace Polynomial.IsEisensteinAt

variable {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]

/-- The maximal ideal of a DVR is generated by the constant coefficient of an
Eisenstein polynomial of positive degree. -/
lemma maximalIdeal_eq_span_coeff_zero (f : A[X])
    (hf : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hdeg : 0 < f.natDegree) :
    IsLocalRing.maximalIdeal A = Ideal.span {f.coeff 0} := by
  have ha_mem : f.coeff 0 ∈ IsLocalRing.maximalIdeal A := hf.mem (by omega)
  have ha_notmem : f.coeff 0 ∉ (IsLocalRing.maximalIdeal A) ^ 2 := hf.notMem
  have ha_ne : f.coeff 0 ≠ 0 := fun h => ha_notmem (h ▸ Ideal.zero_mem _)
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible A
  obtain ⟨n, u, heq⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible ha_ne hϖ
  rw [hϖ.maximalIdeal_eq] at ha_mem ha_notmem
  rw [Ideal.span_singleton_pow] at ha_notmem
  have hn_ge : 1 ≤ n := by
    by_contra h
    simp only [not_le, Nat.lt_one_iff] at h
    subst h; simp only [pow_zero, mul_one] at heq
    rw [heq, Ideal.mem_span_singleton] at ha_mem
    exact hϖ.not_isUnit (isUnit_of_dvd_unit ha_mem u.isUnit)
  have hn_le : n ≤ 1 := by
    by_contra h
    simp only [not_le] at h
    apply ha_notmem; rw [heq, Ideal.mem_span_singleton]
    obtain ⟨k, rfl⟩ : ∃ k, n = k + 2 := ⟨n - 2, by omega⟩
    exact ⟨↑u * ϖ ^ k, by ring⟩
  have hn1 : n = 1 := le_antisymm hn_le hn_ge
  subst hn1
  simp only [pow_one] at heq ha_mem ha_notmem ⊢
  rw [heq]
  exact (Associated.irreducible ⟨u, mul_comm ϖ ↑u⟩ hϖ).maximalIdeal_eq

end Polynomial.IsEisensteinAt

namespace AdjoinRoot

/-- The maximal ideal of a DVR maps into the span of the root of an Eisenstein
polynomial of positive degree. -/
lemma map_maximalIdeal_le_span_root {A : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] (f : A[X])
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hdeg : 0 < f.natDegree) :
    Ideal.map (algebraMap A (AdjoinRoot f)) (IsLocalRing.maximalIdeal A) ≤
      Ideal.span {root f} := by
  rw [Polynomial.IsEisensteinAt.maximalIdeal_eq_span_coeff_zero f heis hdeg,
    Ideal.map_span, Set.image_singleton, Ideal.span_le, Set.singleton_subset_iff]
  exact algebraMap_coeff_zero_mem_span_root f

/-- The root of a monic Eisenstein polynomial of positive degree is nonzero. -/
lemma root_ne_zero {A : Type*} [CommRing A] [IsDomain A] [IsLocalRing A] (f : A[X])
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hf : f.Monic) (hdeg : 0 < f.natDegree) :
    root f ≠ 0 := by
  change (mk f) X ≠ 0
  intro h
  rw [mk_eq_zero] at h
  obtain ⟨g, hg⟩ := h
  have h0 : 0 = f.coeff 0 * g.coeff 0 := by
    have := congr_arg (fun p => p.coeff 0) hg
    simp only [coeff_X_zero, mul_coeff_zero] at this
    exact this
  have ha_ne : f.coeff 0 ≠ 0 := fun h => heis.notMem (h ▸ Ideal.zero_mem _)
  have hg0 : g.coeff 0 = 0 := by
    rcases mul_eq_zero.mp h0.symm with h | h
    · exact absurd h ha_ne
    · exact h
  have hf_ne : f ≠ 0 := hf.ne_zero
  have hg_ne : g ≠ 0 := right_ne_zero_of_mul (hg ▸ X_ne_zero)
  have hdeg_eq : 1 = natDegree f + natDegree g := by
    rw [← natDegree_X (R := A), hg, natDegree_mul hf_ne hg_ne]
  have hnd_g : natDegree g = 0 := by omega
  rw [eq_C_of_natDegree_eq_zero hnd_g, hg0, C_0] at hg_ne
  exact hg_ne rfl

/-- The span of the root of a monic Eisenstein polynomial of positive degree
over a DVR is a maximal ideal. -/
theorem isMaximal_span_root {A : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] (f : A[X])
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hf : f.Monic) (hdeg : 0 < f.natDegree) :
    (Ideal.span {root f}).IsMaximal := by
  have hdist : f.IsDistinguishedAt (IsLocalRing.maximalIdeal A) :=
    ⟨heis.isWeaklyEisensteinAt, hf⟩
  have hmap := hdist.map_eq_X_pow
  let : Field (A ⧸ IsLocalRing.maximalIdeal A) :=
    Ideal.Quotient.field _
  have hirr : Irreducible
      (Polynomial.X.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) := by
    rw [Polynomial.map_X]
    exact Polynomial.irreducible_X
  have hdvd : (Polynomial.X.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ∣
      (f.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) := by
    rw [hmap]
    simpa only [Polynomial.map_X] using
      dvd_pow_self (Polynomial.X : (A ⧸ IsLocalRing.maximalIdeal A)[X])
        (Nat.pos_iff_ne_zero.mp hdeg)
  have hmax := is_maximal_of_irreducible_factor f Polynomial.X hirr hdvd
  rw [mk_X] at hmax
  have hle := map_maximalIdeal_le_span_root f heis hdeg
  rwa [sup_eq_right.mpr hle] at hmax

/-- The root power `root f ^ f.natDegree` lies in every ideal above the base
maximal ideal, for monic Eisenstein `f`. -/
private lemma root_pow_natDegree_mem_of_map_maximalIdeal_le {A : Type*} [CommRing A]
    [IsLocalRing A] (f : A[X]) (hf : f.Monic)
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (m : Ideal (AdjoinRoot f))
    (hbase : Ideal.map (algebraMap A (AdjoinRoot f))
      (IsLocalRing.maximalIdeal A) ≤ m) :
    (root f) ^ f.natDegree ∈ m := by
  have heval := AdjoinRoot.eval₂_root f
  rw [Polynomial.eval₂_eq_sum_range, Finset.sum_range_succ] at heval
  rw [← AdjoinRoot.algebraMap_eq] at heval
  rw [hf.coeff_natDegree, map_one, one_mul] at heval
  have hsum : (∑ i ∈ Finset.range f.natDegree,
      algebraMap A (AdjoinRoot f) (f.coeff i) * (root f) ^ i) ∈ m := by
    apply Ideal.sum_mem
    intro i hi
    have hi_lt : i < f.natDegree := Finset.mem_range.mp hi
    have hci : f.coeff i ∈ IsLocalRing.maximalIdeal A := heis.mem hi_lt
    have hmap : algebraMap A (AdjoinRoot f) (f.coeff i) ∈ m :=
      hbase (Ideal.mem_map_of_mem _ hci)
    exact Ideal.mul_mem_right _ _ hmap
  rw [add_comm] at heval
  have hroot : (root f) ^ f.natDegree =
      -(∑ i ∈ Finset.range f.natDegree,
        algebraMap A (AdjoinRoot f) (f.coeff i) * (root f) ^ i) :=
    eq_neg_of_add_eq_zero_left heval
  rw [hroot]
  exact m.neg_mem hsum

/-- Every maximal ideal of `AdjoinRoot f`, for monic Eisenstein `f` of positive
degree over a DVR, contains the root. -/
theorem root_mem_of_isMaximal {A : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] (f : A[X])
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hf : f.Monic)
    (m : Ideal (AdjoinRoot f)) (hm : m.IsMaximal) :
    root f ∈ m := by
  have := hf.finite_adjoinRoot
  have := hm
  have hmax : (m.comap (algebraMap A (AdjoinRoot f))).IsMaximal :=
    Ideal.isMaximal_comap_of_isIntegral_of_isMaximal (algebraMap A (AdjoinRoot f))
      (algebraMap_isIntegral_iff.mpr (AdjoinRoot.isIntegral_of_monic hf)) m
  have hcon : m.comap (algebraMap A (AdjoinRoot f)) =
      IsLocalRing.maximalIdeal A :=
    IsLocalRing.eq_maximalIdeal hmax
  have hbase : Ideal.map (algebraMap A (AdjoinRoot f))
      (IsLocalRing.maximalIdeal A) ≤ m := by
    rw [← hcon]
    exact Ideal.map_comap_le
  have hpow := root_pow_natDegree_mem_of_map_maximalIdeal_le f hf heis m hbase
  exact hm.isPrime.mem_of_pow_mem f.natDegree hpow

/-- `AdjoinRoot f` is local for monic Eisenstein `f` of positive degree over a DVR. -/
theorem isLocalRing_of_isEisensteinAt {A : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] (f : A[X])
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hf : f.Monic) (hdeg : 0 < f.natDegree) :
    IsLocalRing (AdjoinRoot f) := by
  apply IsLocalRing.of_unique_max_ideal
  refine ⟨Ideal.span {root f}, isMaximal_span_root f heis hf hdeg, fun m hm => ?_⟩
  have hle : Ideal.span {root f} ≤ m :=
    Ideal.span_le.mpr (Set.singleton_subset_iff.mpr (root_mem_of_isMaximal f heis hf m hm))
  exact ((isMaximal_span_root f heis hf hdeg).eq_of_le hm.ne_top hle).symm

/-- The maximal ideal of `AdjoinRoot f` is generated by the root, for monic
Eisenstein `f` of positive degree over a DVR. -/
theorem isLocalRing_maximalIdeal_eq_span_root {A : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] (f : A[X])
    (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hf : f.Monic) (hdeg : 0 < f.natDegree) [IsLocalRing (AdjoinRoot f)] :
    IsLocalRing.maximalIdeal (AdjoinRoot f) = Ideal.span {root f} :=
  (IsLocalRing.eq_maximalIdeal (isMaximal_span_root f heis hf hdeg)).symm

/-- `AdjoinRoot f` is a discrete valuation ring for monic Eisenstein `f` of
positive degree over a DVR. -/
theorem isDiscreteValuationRing_of_isEisensteinAt
    {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (f : A[X]) (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hf : f.Monic) (hdeg : 0 < f.natDegree) :
    @IsDiscreteValuationRing (AdjoinRoot f) _
      (AdjoinRoot.isDomain_of_prime
        (UniqueFactorizationMonoid.irreducible_iff_prime.mp
          (heis.irreducible (IsLocalRing.maximalIdeal.isMaximal A).isPrime
            hf.isPrimitive hdeg))) := by
  have : IsDomain (AdjoinRoot f) := AdjoinRoot.isDomain_of_prime
    (UniqueFactorizationMonoid.irreducible_iff_prime.mp
      (heis.irreducible (IsLocalRing.maximalIdeal.isMaximal A).isPrime
        hf.isPrimitive hdeg))
  have : IsLocalRing (AdjoinRoot f) :=
    isLocalRing_of_isEisensteinAt f heis hf hdeg
  have : Module.Finite A (AdjoinRoot f) := hf.finite_adjoinRoot
  have : IsNoetherianRing (AdjoinRoot f) := IsNoetherianRing.of_finite A (AdjoinRoot f)
  have h_maxeq : IsLocalRing.maximalIdeal (AdjoinRoot f) = Ideal.span {root f} :=
    isLocalRing_maximalIdeal_eq_span_root f heis hf hdeg
  have hprinc : (IsLocalRing.maximalIdeal (AdjoinRoot f)).IsPrincipal :=
    h_maxeq ▸ inferInstance
  have h_not_field : ¬IsField (AdjoinRoot f) := by
    rw [IsLocalRing.isField_iff_maximalIdeal_eq, h_maxeq,
      Ideal.span_singleton_eq_bot]
    exact root_ne_zero f heis hf hdeg
  exact ((IsDiscreteValuationRing.TFAE (AdjoinRoot f) h_not_field).out 5 1).mp hprinc

/-- The root of a monic Eisenstein polynomial of positive degree over a DVR is
irreducible. -/
theorem irreducible_root_of_isEisensteinAt
    {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (f : A[X]) (heis : f.IsEisensteinAt (IsLocalRing.maximalIdeal A))
    (hf : f.Monic) (hdeg : 0 < f.natDegree) :
    Irreducible (root f) := by
  have : IsDomain (AdjoinRoot f) := AdjoinRoot.isDomain_of_prime
    (UniqueFactorizationMonoid.irreducible_iff_prime.mp
      (heis.irreducible (IsLocalRing.maximalIdeal.isMaximal A).isPrime
        hf.isPrimitive hdeg))
  have : IsLocalRing (AdjoinRoot f) :=
    isLocalRing_of_isEisensteinAt f heis hf hdeg
  have : IsDiscreteValuationRing (AdjoinRoot f) :=
    isDiscreteValuationRing_of_isEisensteinAt f heis hf hdeg
  have : IsLocalRing.maximalIdeal (AdjoinRoot f) = Ideal.span {root f} :=
    isLocalRing_maximalIdeal_eq_span_root f heis hf hdeg
  exact (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr this

end AdjoinRoot
