/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import MathlibExt.NumberTheory.NumberField.LatticeDiscriminant

/-!
# Extension discriminants

For a tower A to B to L, imageOfB is the image of B in L as an A-submodule. The extension
discriminant is the lattice discriminant of that submodule.

The result is represented as an A-submodule of K, not literally as an Ideal A. Showing that it
comes from an integral ideal requires additional hypotheses.
-/

@[expose] public section

set_option autoImplicit false

universe u

section ImageOfB

variable (A : Type*) (L : Type u) (B : Type*)
  [CommRing A] [CommRing B] [Field L]
  [Algebra A B] [Algebra B L] [Algebra A L] [IsScalarTower A B L]

/-- The image of B in L, regarded as an A-submodule of L. -/
def imageOfB : Submodule A L :=
  Subalgebra.toSubmodule (IsScalarTower.toAlgHom A B L).range

/-- Membership in imageOfB is membership in the range of the algebra map from B to L. -/
theorem mem_imageOfB {x : L} :
    x ∈ imageOfB A L B ↔ ∃ b : B, algebraMap B L b = x := by
  simp only [imageOfB, Subalgebra.mem_toSubmodule, AlgHom.mem_range,
    IsScalarTower.coe_toAlgHom']

/-- Every element mapped from B belongs to imageOfB. -/
theorem algebraMap_mem_imageOfB (b : B) :
    algebraMap B L b ∈ imageOfB A L B :=
  (mem_imageOfB A L B).mpr ⟨b, rfl⟩

/-- The image of a finite A-module B is finite as an A-module. -/
instance imageOfB_finite [Module.Finite A B] :
    Module.Finite A ↥(imageOfB A L B) := by
  have heq : imageOfB A L B =
      (IsScalarTower.toAlgHom A B L).toLinearMap.range := by
    ext x
    constructor
    · intro hx
      rw [mem_imageOfB A L B] at hx
      rcases hx with ⟨b, rfl⟩
      exact ⟨b, rfl⟩
    · rintro ⟨b, rfl⟩
      exact (mem_imageOfB A L B).mpr ⟨b, rfl⟩
  rw [heq]
  exact Module.Finite.range (IsScalarTower.toAlgHom A B L).toLinearMap

end ImageOfB

section ExtensionDiscriminant

variable (A K : Type*) (L : Type u) (B : Type*)
  [CommRing A] [Field K] [CommRing B] [Field L]
  [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
  [IsScalarTower A K L] [IsScalarTower A B L] [FiniteDimensional K L]

/--
The extension discriminant, represented by the A-submodule of K generated by discriminants of
tuples from the image of B in L. It is not, at this level of generality, an Ideal A.
-/
def extensionDiscriminant : Submodule A K :=
  latticeDiscriminant A K (imageOfB A L B)

/-- The extension discriminant is the lattice discriminant of imageOfB. -/
theorem extensionDiscriminant_eq :
    extensionDiscriminant A K L B =
      latticeDiscriminant A K (imageOfB A L B) :=
  rfl

/-- The discriminant of a tuple from imageOfB belongs to the extension discriminant. -/
theorem discr_mem_extensionDiscriminant
    {b : Fin (Module.finrank K L) → L} (hb : ∀ i, b i ∈ imageOfB A L B) :
    Algebra.discr K b ∈ extensionDiscriminant A K L B :=
  discr_mem_latticeDiscriminant A K hb

end ExtensionDiscriminant
