module

public import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
public import Mathlib.NumberTheory.NumberField.ExistsRamified
public import Mathlib.NumberTheory.RamificationInertia.Unramified
public import MathlibExt.NumberTheory.NumberField.Unramified

@[expose] public section

/-!
# Cyclotomic fields are unramified away from the conductor

Packaging of the pointwise ramification-index computation for cyclotomic
extensions as a native `Algebra.IsUnramifiedIn` statement. This is the
"in particular, if `p` does not divide `m` then `Q(zeta_m)` is unramified
at `p`" clause of MIT 18.785 Proposition 19.14 (ATLAS NumberTheoryI N390).

## Source map for the `p`-power bottom theorem

`eq_bot_of_isUnramifiedIn_prime_pow` below formalizes the prime-power
vanishing step of the N390 maximality argument, following the ATLAS source
`v1/Atlas/NumberTheoryI/code/AnalyticClassNumber.lean` at revision
`e8b31c5cb0bec89b487ce33fe525a2c0b0f8b9c6`, lines 1462--1547:

* `cyclotomic_ppow_unramified_at_other_primes` (lines 1462--1479) becomes
  `isUnramifiedIn_of_not_dvd` above, descended with
  `NumberField.isUnramifiedIn_mono` (the generic form of the source's
  `isUnramifiedAtPrime_of_le`, lines 1433--1460);
* `minkowski_no_unramified_extension` (lines 1482--1530) becomes
  `NumberField.exists_not_isUnramifiedIn`, which packages the Minkowski
  discriminant argument in Mathlib;
* `cyclotomic_ppow_unramified_le_bot` (lines 1532--1547) becomes
  `eq_bot_of_isUnramifiedIn_prime_pow`, generalized to an arbitrary
  exponent `e` and an arbitrary number-field ambient `L` (the source fixes
  `e = padicValNat p m` and `L = CyclotomicField m ℚ`).

This closes the `p`-power-vanishing prerequisite of Proposition 19.14, but
not the full proposition or the N390 maximality theorem: no compositum
unramifiedness and no localization equivalence is claimed here.
-/

open scoped NumberField

namespace IsCyclotomicExtension.Rat

/-- A cyclotomic extension of conductor `m` is unramified at the prime
ideal generated by `p` whenever `p` does not divide `m`. -/
theorem isUnramifiedIn_of_not_dvd
    {m p : ℕ} [NeZero m] (hp : p.Prime)
    (K : Type*) [Field K] [NumberField K]
    [IsCyclotomicExtension {m} ℚ K] (hm : ¬ p ∣ m) :
    Algebra.IsUnramifiedIn (𝓞 K) (Ideal.span {(p : ℤ)}) := by
  let _ : Fact p.Prime := ⟨hp⟩
  rw [Algebra.isUnramifiedIn_iff_forall_ramificationIdx_eq_one]
  intro P hP hLie
  have _ := hP
  have _ := hLie
  exact ramificationIdx_eq_of_not_dvd p K P hm

/-- The `p`-free conductor of `m` admits an unramified cyclotomic field
at `p`: `Q(zeta_{m'})` with `m' = Nat.divMaxPow m p`. -/
theorem isUnramifiedIn_divMaxPow
    (m p : ℕ) [NeZero m] (hp : p.Prime) :
    Algebra.IsUnramifiedIn
      (𝓞 (CyclotomicField (Nat.divMaxPow m p) ℚ))
      (Ideal.span {(p : ℤ)}) := by
  have h_eq := Nat.divMaxPow_mul_pow_padicValNat p m
  have hne : Nat.divMaxPow m p ≠ 0 := by
    intro h0
    rw [h0, zero_mul] at h_eq
    exact NeZero.ne m h_eq.symm
  let _ : NeZero (Nat.divMaxPow m p) := ⟨hne⟩
  let _ : NeZero ((Nat.divMaxPow m p : ℕ) : ℚ) := ⟨Nat.cast_ne_zero.mpr hne⟩
  let _ : IsCyclotomicExtension {Nat.divMaxPow m p} ℚ
      (CyclotomicField (Nat.divMaxPow m p) ℚ) :=
    CyclotomicField.isCyclotomicExtension (Nat.divMaxPow m p) ℚ
  exact isUnramifiedIn_of_not_dvd (m := Nat.divMaxPow m p) (p := p) hp
    (CyclotomicField (Nat.divMaxPow m p) ℚ)
    (Nat.not_dvd_divMaxPow hp.one_lt (NeZero.ne m))

/-- A subfield of a `p`-power cyclotomic extension that is unramified at `p`
is the bottom field.

This is the prime-power vanishing step of the N390 maximality argument
(`cyclotomic_ppow_unramified_le_bot` in the primary source). The exponent is
an arbitrary `e` and the ambient field an arbitrary number field `L`; the
source's `e = padicValNat p m` with `L = CyclotomicField m ℚ` is recovered
in the test file. -/
theorem eq_bot_of_isUnramifiedIn_prime_pow
    {p e : ℕ} (hp : p.Prime)
    (L : Type*) [Field L] [NumberField L]
    (E₁ : IntermediateField ℚ L) [IsCyclotomicExtension {p ^ e} ℚ E₁]
    (F : IntermediateField ℚ L) (hFE₁ : F ≤ E₁)
    (hF : Algebra.IsUnramifiedIn (𝓞 F) (Ideal.span {(p : ℤ)})) :
    F = ⊥ := by
  by_contra hFne
  have hfin : Module.finrank ℚ F ≠ 1 :=
    fun h => hFne (IntermediateField.finrank_eq_one_iff.mp h)
  obtain ⟨q, hq, hram⟩ : ∃ q : ℕ, q.Prime ∧
      ¬ Algebra.IsUnramifiedIn (𝓞 F) (Ideal.span {(q : ℤ)}) :=
    NumberField.exists_not_isUnramifiedIn hfin
  apply hram
  by_cases hqp : q = p
  · subst hqp
    exact hF
  · have hqdvd : ¬ q ∣ p ^ e := by
      intro hd
      exact hqp (Nat.prime_eq_prime_of_dvd_pow hq hp hd)
    have : NeZero (p ^ e) := ⟨pow_ne_zero _ hp.ne_zero⟩
    exact NumberField.isUnramifiedIn_mono F E₁ hFE₁ (Ideal.span {(q : ℤ)})
      (isUnramifiedIn_of_not_dvd (m := p ^ e) (p := q) hq E₁ hqdvd)

end IsCyclotomicExtension.Rat

end
