module

public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import Mathlib.FieldTheory.PrimitiveElement
public import Mathlib.FieldTheory.PurelyInseparable.Basic

/-!
# Purely inseparable extensions of prime degree

Source/provenance: this is the theorem represented by ATLAS NumberTheoryI N77
(see the audited English/API brief): a finite purely inseparable extension whose
degree is a prime `p` is generated by a single element with minimal polynomial
`X ^ p - C a`, where `a` is not a `p`th power in the base field.

The statement and proof below are authored directly against Mathlib; no ATLAS
source was inspected.
-/

@[expose] public section

set_option autoImplicit false

open IntermediateField Module Polynomial

namespace IsPurelyInseparable

variable (K L : Type*) [Field K] [Field L] [Algebra K L]
variable (p : ℕ) [CharP K p] [IsPurelyInseparable K L]
variable [FiniteDimensional K L]

/-- ATLAS N77: a finite purely inseparable extension of prime degree `p` is
generated by a root of `X ^ p - C a` with `a` not a `p`th power in `K`. -/
theorem exists_minpoly_X_pow_sub_C_of_finrank_eq_prime (hp : p.Prime)
    (hfin : finrank K L = p) :
    ∃ α : L, ∃ a : K,
      minpoly K α = X ^ p - C a ∧
        (∀ b : K, b ^ p ≠ a) ∧ K⟮α⟯ = ⊤ := by
  have _ := Fact.mk hp
  have hbot_ne_top : (⊥ : IntermediateField K L) ≠ ⊤ := by
    intro hcon
    have h1 : finrank K (↥(⊥ : IntermediateField K L)) = 1 :=
      IntermediateField.finrank_bot
    have h2 : finrank K (↥(⊤ : IntermediateField K L)) = finrank K L :=
      IntermediateField.finrank_top'
    have hp1 : p ≠ 1 := hp.ne_one
    rw [hcon] at h1
    omega
  have hlt : (⊥ : IntermediateField K L) < ⊤ := lt_of_le_of_ne bot_le hbot_ne_top
  obtain ⟨α, _, hα⟩ := SetLike.exists_of_lt hlt
  have hint : IsIntegral K α := Algebra.IsIntegral.isIntegral α
  have hdeg_adjoin : finrank K K⟮α⟯ = (minpoly K α).natDegree :=
    IntermediateField.adjoin.finrank hint
  have htower : finrank K K⟮α⟯ * finrank K⟮α⟯ L = finrank K L :=
    Module.finrank_mul_finrank K K⟮α⟯ L
  have hdvd : finrank K K⟮α⟯ ∣ p := ⟨_, (htower.trans hfin).symm⟩
  have hne_one : finrank K K⟮α⟯ ≠ 1 :=
    mt IntermediateField.finrank_adjoin_simple_eq_one_iff.mp hα
  have hfin_adjoin : finrank K K⟮α⟯ = p := by
    rcases (Nat.dvd_prime hp).mp hdvd with h | h
    · exact absurd h hne_one
    · exact h
  have hdeg : (minpoly K α).natDegree = p := by omega
  obtain ⟨n, a, hmin⟩ := IsPurelyInseparable.minpoly_eq_X_pow_sub_C (F := K) (E := L)
    (q := p) (x := α)
  have hpn : p ^ n = p := by
    have hcon := hdeg
    rw [hmin, Polynomial.natDegree_X_pow_sub_C] at hcon
    exact hcon
  have hn1 : n = 1 := Nat.pow_right_injective hp.one_lt (by simpa using hpn)
  subst hn1
  rw [pow_one] at hmin
  refine ⟨α, a, hmin, ?_, ?_⟩
  · intro b hb
    have hirr : Irreducible (X ^ p - C a : K[X]) :=
      hmin ▸ minpoly.irreducible hint
    have hsub : ((X - C b : K[X]) ^ p) = X ^ p - C (b ^ p) := by
      rw [sub_pow_expChar, map_pow]
    rw [hb] at hsub
    rw [← hsub] at hirr
    exact not_irreducible_pow hp.ne_one hirr
  · rw [Field.primitive_element_iff_minpoly_natDegree_eq (F := K) (E := L)
      (α := α), hmin,
      Polynomial.natDegree_X_pow_sub_C, hfin]

end IsPurelyInseparable
