/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import Mathlib.FieldTheory.PrimitiveElement
public import Mathlib.FieldTheory.Separable
public import Mathlib.FieldTheory.SeparableDegree
public import Mathlib.RingTheory.AdjoinRoot

/-!
# Separable finite extensions are generated by a separable polynomial

A finite-dimensional extension of fields is separable if and only if it is
generated by the root of a monic separable irreducible polynomial, i.e. it is
isomorphic (as a `K`-algebra) to `AdjoinRoot f` for such an `f`.
-/

@[expose] public section

set_option autoImplicit false

open scoped Polynomial

open IntermediateField

namespace Algebra

variable (K L : Type*) [Field K] [Field L] [Algebra K L] [FiniteDimensional K L]

/-- A finite extension is separable iff it is `AdjoinRoot` of a monic separable
irreducible polynomial. -/
theorem isSeparable_iff_exists_monic_irreducible_separable :
    Algebra.IsSeparable K L ↔
      ∃ f : K[X], f.Monic ∧ Irreducible f ∧ f.Separable ∧
        Nonempty (L ≃ₐ[K] AdjoinRoot f) := by
  constructor
  · intro hsep
    have := hsep
    obtain ⟨α, hα⟩ := Field.exists_primitive_element K L
    have hsepα : IsSeparable K α := Algebra.IsSeparable.isSeparable K α
    have hInt : IsIntegral K α := hsepα.isIntegral
    refine ⟨minpoly K α, minpoly.monic hInt, minpoly.irreducible hInt, hsepα, ?_⟩
    · have e1 := IntermediateField.adjoinRootEquivAdjoin K hInt
      have e2 : K⟮α⟯ ≃ₐ[K] L :=
        (IntermediateField.equivOfEq hα).trans IntermediateField.topEquiv
      exact ⟨e2.symm.trans e1.symm⟩
  · rintro ⟨f, hfM, hfI, hfS, ⟨e⟩⟩
    have : Fact (Irreducible f) := ⟨hfI⟩
    have hf0 : f ≠ 0 := hfM.ne_zero
    have hmin : minpoly K (AdjoinRoot.root f) = f := by
      rw [AdjoinRoot.minpoly_root hf0, hfM.leadingCoeff, inv_one, map_one, mul_one]
    have hroot : IsSeparable K (AdjoinRoot.root f) := by
      change Polynomial.Separable (minpoly K (AdjoinRoot.root f))
      rw [hmin]
      exact hfS
    have : Algebra.IsSeparable K K⟮AdjoinRoot.root f⟯ :=
      IntermediateField.isSeparable_adjoin_simple_iff_isSeparable K _ |>.mpr hroot
    have e1 : AdjoinRoot (minpoly K (AdjoinRoot.root f)) ≃ₐ[K]
        K⟮AdjoinRoot.root f⟯ :=
      IntermediateField.adjoinRootEquivAdjoin K hroot.isIntegral
    rw [hmin] at e1
    have : Algebra.IsSeparable K (AdjoinRoot f) :=
      Algebra.IsSeparable.of_algHom K _ e1.toAlgHom
    exact Algebra.IsSeparable.of_algHom K _ e.toAlgHom

end Algebra
