/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import Mathlib.Data.Fin.Basic
public import Mathlib.Data.Fintype.BigOperators
public import Mathlib.Data.Nat.Totient
import Mathlib.Algebra.Torsor.Defs
import Mathlib.Combinatorics.Colex
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.Logic.Equiv.Fin.Basic
import Mathlib.Tactic.Abel

@[expose] public section

namespace MetaMathlibExt

open scoped BigOperators

/-- Invariance of a `Bool`-valued function under adding `g` extends to all integer
multiples of `g`. -/
private theorem inv_zsmul {G : Type*} [AddCommGroup G] (g : G) (f : G → Bool)
    (hf : ∀ x, f (x + g) = f x) : ∀ (k : ℤ) (x : G), f (x + k • g) = f x := by
  have hneg : ∀ x, f (x - g) = f x := by
    intro x; have := hf (x - g); simpa using this.symm
  intro k
  induction k using Int.induction_on with
  | zero => intro x; simp
  | succ k ih =>
      intro x
      have h1 : x + ((k : ℤ) + 1) • g = (x + (k : ℤ) • g) + g := by rw [add_one_zsmul]; abel
      rw [h1, hf]; exact ih x
  | pred k ih =>
      intro x
      have h1 : x + (-(k : ℤ) - 1) • g = (x + (-(k : ℤ)) • g) - g := by rw [sub_one_zsmul]; abel
      rw [h1, hneg]; exact ih x

/-- Translation-invariant `Bool`-valued functions on `G` are the same data as functions
on the quotient by the subgroup generated by `g`. -/
private noncomputable def invEquiv {G : Type*} [AddCommGroup G] (g : G) :
    {f : G → Bool // ∀ x, f (x + g) = f x} ≃ ((G ⧸ AddSubgroup.zmultiples g) → Bool) where
  toFun fh := Quotient.lift fh.1 (by
    intro a b hab
    obtain ⟨k, hk⟩ := AddSubgroup.mem_zmultiples_iff.mp (QuotientAddGroup.leftRel_apply.mp hab)
    have hb : b = a + k • g := by rw [hk]; abel
    rw [hb, inv_zsmul g fh.1 fh.2 k a])
  invFun F := ⟨fun x => F (QuotientAddGroup.mk x), by
    intro x
    have hmk : (QuotientAddGroup.mk (x + g) : G ⧸ AddSubgroup.zmultiples g)
        = QuotientAddGroup.mk x := by
      rw [QuotientAddGroup.eq]
      exact AddSubgroup.mem_zmultiples_iff.mpr ⟨-1, by simp⟩
    exact congrArg F hmk⟩
  left_inv fh := by ext x; rfl
  right_inv F := by
    ext q
    induction q using Quotient.inductionOn with
    | h x => rfl

/-- The number of `Bool`-valued functions on a finite additive group that are invariant
under adding `g` is `2 ^ (|G| / addOrderOf g)`. -/
private theorem inv_count {G : Type*} [AddCommGroup G] [Fintype G] [DecidableEq G] (g : G) :
    (Finset.univ.filter (fun f : G → Bool => ∀ x, f (x + g) = f x)).card
      = 2 ^ (Fintype.card G / addOrderOf g) := by
  classical
  have hpos : 0 < addOrderOf g :=
    Nat.pos_of_dvd_of_pos addOrderOf_dvd_card Fintype.card_pos
  have hquot : Fintype.card (G ⧸ AddSubgroup.zmultiples g)
      = Fintype.card G / addOrderOf g := by
    have h := AddSubgroup.card_eq_card_quotient_mul_card_addSubgroup (AddSubgroup.zmultiples g)
    rw [Nat.card_zmultiples, Nat.card_eq_fintype_card, Nat.card_eq_fintype_card] at h
    rw [h, Nat.mul_div_cancel _ hpos]
  rw [← Fintype.card_subtype, Fintype.card_congr (invEquiv g), Fintype.card_fun,
    Fintype.card_bool, hquot]

/-- The cyclic shift action of `Fin m × Fin n` on binary matrices. -/
private instance shiftAction (m n : ℕ) [NeZero m] [NeZero n] :
    AddAction (Fin m × Fin n) (Fin m → Fin n → Bool) where
  vadd p x := fun r s => x (r + p.1) (s + p.2)
  zero_vadd x := by
    funext r s
    change x (r + (0 : Fin m)) (s + (0 : Fin n)) = x r s
    rw [add_zero, add_zero]
  add_vadd p q x := by
    funext r s
    change x (r + (p.1 + q.1)) (s + (p.2 + q.2)) = x (r + p.1 + q.1) (s + p.2 + q.2)
    rw [add_assoc, add_assoc]

private theorem shift_vadd_apply {m n : ℕ} [NeZero m] [NeZero n]
    (p : Fin m × Fin n) (x : Fin m → Fin n → Bool) (r : Fin m) (s : Fin n) :
    (p +ᵥ x) r s = x (r + p.1) (s + p.2) := rfl

private noncomputable def fixedByEquiv {m n : ℕ} [NeZero m] [NeZero n] (g : Fin m × Fin n) :
    (AddAction.fixedBy (Fin m → Fin n → Bool) g)
      ≃ {F : (Fin m × Fin n) → Bool // ∀ p, F (p + g) = F p} where
  toFun x := ⟨fun p => x.1 p.1 p.2, by
    intro p
    have hx : g +ᵥ x.1 = x.1 := x.2
    have h := congrFun (congrFun hx p.1) p.2
    rw [shift_vadd_apply] at h
    exact h⟩
  invFun F := ⟨fun r s => F.1 (r, s), by
    change g +ᵥ (fun r s => F.1 (r, s)) = (fun r s => F.1 (r, s))
    funext r s
    rw [shift_vadd_apply]
    exact F.2 (r, s)⟩
  left_inv x := by ext r s; rfl
  right_inv F := by ext p; rfl

/-- The number of matrices fixed by the shift `g` is `2 ^ (m n / addOrderOf g)`. -/
private theorem fixedBy_card {m n : ℕ} [NeZero m] [NeZero n] (g : Fin m × Fin n) :
    Fintype.card (AddAction.fixedBy (Fin m → Fin n → Bool) g)
      = 2 ^ (Fintype.card (Fin m × Fin n) / addOrderOf g) := by
  classical
  rw [Fintype.card_congr (fixedByEquiv g), ← inv_count g, Fintype.card_subtype]

private instance finAddCyclic (M : ℕ) [NeZero M] : IsAddCyclic (Fin M) := by
  obtain ⟨M', rfl⟩ := Nat.exists_eq_succ_of_ne_zero (NeZero.ne M)
  exact ZMod.instIsAddCyclic (M' + 1)

/-- Reindexing a sum over `Fin M` by the additive order of the element, grouping equal
orders together via Euler's totient. -/
private theorem sum_reindex_order (M : ℕ) [NeZero M] (h : ℕ → ℕ) :
    ∑ i : Fin M, h (addOrderOf i) = ∑ c ∈ M.divisors, Nat.totient c * h c := by
  classical
  rw [← Finset.sum_fiberwise_of_maps_to (s := Finset.univ) (t := M.divisors)
        (g := fun i : Fin M => addOrderOf i) (f := fun i => h (addOrderOf i))
        (fun i _ => by
          rw [Nat.mem_divisors]
          exact ⟨by simpa using (addOrderOf_dvd_card (x := i)), NeZero.ne M⟩)]
  apply Finset.sum_congr rfl
  intro c hc
  have hcd : c ∣ M := (Nat.mem_divisors.mp hc).1
  have hc' : c ∣ Fintype.card (Fin M) := by simpa using hcd
  have hcard : (Finset.univ.filter (fun a : Fin M => addOrderOf a = c)).card = c.totient :=
    IsAddCyclic.card_addOrderOf_eq_totient hc'
  have heval : ∀ i ∈ Finset.univ.filter (fun a : Fin M => addOrderOf a = c),
      h (addOrderOf i) = h c := fun i hi => by rw [(Finset.mem_filter.mp hi).2]
  rw [Finset.sum_congr rfl heval, Finset.sum_const, hcard, smul_eq_mul]

/-- The Burnside fixed-point sum equals the Pólya enumeration numerator. -/
private theorem burnside_sum_eq {m n : ℕ} [NeZero m] [NeZero n] :
    ∑ g : Fin m × Fin n, Fintype.card (AddAction.fixedBy (Fin m → Fin n → Bool) g)
      = ∑ c ∈ m.divisors, ∑ d ∈ n.divisors,
          Nat.totient c * Nat.totient d * 2 ^ (m * n / Nat.lcm c d) := by
  have hcardG : Fintype.card (Fin m × Fin n) = m * n := by
    rw [Fintype.card_prod, Fintype.card_fin, Fintype.card_fin]
  calc ∑ g : Fin m × Fin n, Fintype.card (AddAction.fixedBy (Fin m → Fin n → Bool) g)
      = ∑ g : Fin m × Fin n, 2 ^ (m * n / addOrderOf g) := by
        apply Finset.sum_congr rfl; intro g _; rw [fixedBy_card, hcardG]
    _ = ∑ i : Fin m, ∑ j : Fin n, 2 ^ (m * n / Nat.lcm (addOrderOf i) (addOrderOf j)) := by
        rw [Fintype.sum_prod_type]
        apply Finset.sum_congr rfl; intro i _
        apply Finset.sum_congr rfl; intro j _
        rw [Prod.addOrderOf_mk]
    _ = ∑ i : Fin m, ∑ d ∈ n.divisors,
          Nat.totient d * 2 ^ (m * n / Nat.lcm (addOrderOf i) d) := by
        apply Finset.sum_congr rfl; intro i _
        exact sum_reindex_order n (fun d => 2 ^ (m * n / Nat.lcm (addOrderOf i) d))
    _ = ∑ c ∈ m.divisors, Nat.totient c *
          (∑ d ∈ n.divisors, Nat.totient d * 2 ^ (m * n / Nat.lcm c d)) :=
        sum_reindex_order m
          (fun c => ∑ d ∈ n.divisors, Nat.totient d * 2 ^ (m * n / Nat.lcm c d))
    _ = ∑ c ∈ m.divisors, ∑ d ∈ n.divisors,
          Nat.totient c * Nat.totient d * 2 ^ (m * n / Nat.lcm c d) := by
        apply Finset.sum_congr rfl; intro c _
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl; intro d _
        rw [← mul_assoc]

/-- The weight (binary encoding) of a matrix. -/
private def Wt (m n : ℕ) (x : Fin m → Fin n → Bool) : ℕ :=
  ∑ r : Fin m, ∑ s : Fin n, (if x r s = true then 1 else 0) * 2 ^ (r.val * n + s.val)

private theorem e_inj (m n : ℕ) :
    Function.Injective (fun p : Fin m × Fin n => p.1.val * n + p.2.val) := by
  intro a b hab
  apply finProdFinEquiv.injective
  apply Fin.val_injective
  rw [finProdFinEquiv_apply_val, finProdFinEquiv_apply_val]
  simp only at hab
  rw [Nat.mul_comm a.1.val n, Nat.mul_comm b.1.val n] at hab
  omega

/-- The weight function is injective: the binary encoding determines the matrix. -/
private theorem Wt_inj (m n : ℕ) : Function.Injective (Wt m n) := by
  classical
  set e : Fin m × Fin n → ℕ := fun p => p.1.val * n + p.2.val with he
  have einj : Function.Injective e := e_inj m n
  have key : ∀ z : Fin m → Fin n → Bool,
      Wt m n z
        = ∑ k ∈ (Finset.univ.filter (fun p : Fin m × Fin n => z p.1 p.2 = true)).image e,
            2 ^ k := by
    intro z
    rw [Wt, ← Fintype.sum_prod_type (fun p : Fin m × Fin n =>
          (if z p.1 p.2 = true then 1 else 0) * 2 ^ (p.1.val * n + p.2.val))]
    rw [Finset.sum_image (by intro a _ b _ hab; exact einj hab), Finset.sum_filter]
    apply Finset.sum_congr rfl
    intro p _
    by_cases hp : z p.1 p.2 = true <;> simp [hp, he]
  intro x y hxy
  rw [key x, key y] at hxy
  have hT := congrArg (fun N => N.bitIndices.toFinset) hxy
  simp only [Finset.toFinset_bitIndices_sum_two_pow] at hT
  have hfilter := Finset.image_injective einj hT
  funext r s
  have hiff : (r, s) ∈ Finset.univ.filter (fun p : Fin m × Fin n => x p.1 p.2 = true)
      ↔ (r, s) ∈ Finset.univ.filter (fun p : Fin m × Fin n => y p.1 p.2 = true) := by
    rw [hfilter]
  simpa using hiff

/-- The matrices that are minimal (by weight) in their shift-orbit are in bijection with
the orbits. -/
private theorem orbit_min_count (m n : ℕ) [NeZero m] [NeZero n] :
    (Finset.univ.filter (fun x : Fin m → Fin n → Bool =>
        ∀ g : Fin m × Fin n, Wt m n x ≤ Wt m n (g +ᵥ x))).card
      = Nat.card
          (Quotient (AddAction.orbitRel (Fin m × Fin n) (Fin m → Fin n → Bool))) := by
  classical
  set G := Fin m × Fin n
  set Y := Fin m → Fin n → Bool
  set P : Y → Prop := fun x => ∀ g : G, Wt m n x ≤ Wt m n (g +ᵥ x) with hP
  have : Fintype (Quotient (AddAction.orbitRel G Y)) := Fintype.ofFinite _
  rw [Nat.card_eq_fintype_card, ← Fintype.card_subtype P]
  refine Fintype.card_of_bijective
    (f := fun x : {x // P x} => Quotient.mk (AddAction.orbitRel G Y) x.1) ?_
  constructor
  · rintro ⟨x, hx⟩ ⟨y, hy⟩ hxy
    have hrel : x ∈ AddAction.orbit G y :=
      AddAction.orbitRel_apply.mp (Quotient.exact hxy)
    obtain ⟨g, hg⟩ := AddAction.mem_orbit_iff.mp hrel
    have hg2 : (-g) +ᵥ x = y := by rw [← hg, ← add_vadd, neg_add_cancel, zero_vadd]
    have h1 : Wt m n x ≤ Wt m n y := by have := hx (-g); rwa [hg2] at this
    have h2 : Wt m n y ≤ Wt m n x := by have := hy g; rwa [hg] at this
    have hxyeq : x = y := Wt_inj m n (le_antisymm h1 h2)
    simpa using hxyeq
  · intro q
    obtain ⟨x₀, hx₀⟩ := Quotient.exists_rep q
    set O := Finset.univ.filter
      (fun z : Y => Quotient.mk (AddAction.orbitRel G Y) z = q) with hO
    have hx₀O : x₀ ∈ O := by rw [hO, Finset.mem_filter]; exact ⟨Finset.mem_univ _, hx₀⟩
    obtain ⟨xm, hxmO, hmin⟩ := Finset.exists_min_image O (Wt m n) ⟨x₀, hx₀O⟩
    have hxmq : Quotient.mk (AddAction.orbitRel G Y) xm = q := (Finset.mem_filter.mp hxmO).2
    refine ⟨⟨xm, ?_⟩, hxmq⟩
    intro g
    apply hmin
    rw [hO, Finset.mem_filter]
    refine ⟨Finset.mem_univ _, ?_⟩
    rw [← hxmq]
    exact Quotient.sound
      (AddAction.orbitRel_apply.mpr (AddAction.mem_orbit_iff.mpr ⟨g, rfl⟩))

/--
The number of binary matrices modulo cyclic row and column rotations is given by
the Pólya enumeration formula below.

Source: S. N. Ethier, "Counting Toroidal Binary Arrays," Journal of Integer
Sequences 16 (2013), Article 13.4.7, Theorem (label rotations-thm),
lines 172–176,
<https://cs.uwaterloo.ca/journals/JIS/VOL16/Ethier/ethier2.tex>.

Proves `Wanted` entry `binaryMatrixRotationOrbitCount`.
-/
theorem binaryMatrixRotationOrbitCount
    (m n : ℕ) (hm : 0 < m) (hn : 0 < n) :
    (Finset.univ.filter (fun x : Fin m → Fin n → Bool =>
      ∀ i : Fin m, ∀ j : Fin n,
        (∑ r : Fin m, ∑ s : Fin n,
          (if x r s = true then 1 else 0) * 2 ^ (r.val * n + s.val)) ≤
        (∑ r : Fin m, ∑ s : Fin n,
          (if x (r + i) (s + j) = true then 1 else 0) *
            2 ^ (r.val * n + s.val)))).card =
      (∑ c ∈ m.divisors, ∑ d ∈ n.divisors,
        Nat.totient c * Nat.totient d *
          2 ^ ((m * n) / Nat.lcm c d)) / (m * n) := by
  classical
  have : NeZero m := ⟨hm.ne'⟩
  have : NeZero n := ⟨hn.ne'⟩
  have : Fintype (Quotient
    (AddAction.orbitRel (Fin m × Fin n) (Fin m → Fin n → Bool))) := Fintype.ofFinite _
  have hpred : ∀ x : Fin m → Fin n → Bool,
      (∀ i : Fin m, ∀ j : Fin n,
          (∑ r : Fin m, ∑ s : Fin n,
            (if x r s = true then 1 else 0) * 2 ^ (r.val * n + s.val)) ≤
          (∑ r : Fin m, ∑ s : Fin n,
            (if x (r + i) (s + j) = true then 1 else 0) * 2 ^ (r.val * n + s.val)))
      ↔ (∀ g : Fin m × Fin n, Wt m n x ≤ Wt m n (g +ᵥ x)) :=
    fun x => ⟨fun h g => h g.1 g.2, fun h i j => h (i, j)⟩
  have hfe := Finset.filter_congr (s := Finset.univ) (fun x (_ : x ∈ Finset.univ) => hpred x)
  rw [hfe, orbit_min_count]
  have hburn := AddAction.sum_card_fixedBy_eq_card_orbits_mul_card_addGroup
    (Fin m × Fin n) (Fin m → Fin n → Bool)
  rw [burnside_sum_eq] at hburn
  have hcardG : Fintype.card (Fin m × Fin n) = m * n := by
    rw [Fintype.card_prod, Fintype.card_fin, Fintype.card_fin]
  rw [hcardG] at hburn
  rw [Nat.card_eq_fintype_card, hburn, Nat.mul_div_cancel _ (Nat.mul_pos hm hn)]

end MetaMathlibExt
