/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import Mathlib.Data.Complex.Basic
public import Mathlib.NumberTheory.Divisors

namespace MetaMathlibExt

@[expose] public section

/-- The Fermat sequence generated by a complex sequence `b`, defined by
`a n = ∑ m ∈ n.divisors, m * b m`.

This follows lines 181–190 of B.-S. Du, S.-S. Huang, and M.-C. Li,
*Newton, Fermat, and Exactly Realizable Sequences*, Journal of Integer Sequences 8 (2005):

<https://cs.uwaterloo.ca/journals/JIS/VOL8/Huang/huang11.tex>

The source defines the sequence for positive indices. We totalize it at zero using
`Nat.divisors 0 = ∅`, so its value there is zero.

Source SHA-256: `e280997f941eb46d98b411cb2d2ff593d284837371b6565cd4efdb1cdaabffdb`.
Concept `jis_term_a7b36e26421828cebf9c3d39`; semantic ID `jis_sem_2f7e63717e4d696b6c09cf8f`.
-/
public def fermatSequence (b : ℕ → ℂ) : ℕ → ℂ :=
  fun n => ∑ m ∈ Nat.divisors n, (m : ℂ) * b m

end

end MetaMathlibExt
