/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import Mathlib.NumberTheory.LegendreSymbol.JacobiSymbol
public import Mathlib.RingTheory.Polynomial.Resultant.Basic

/-!
Grantham Frobenius pseudoprimes, source-faithful formalization.

Controlling source: Jon Grantham, Frobenius Pseudoprimes,
Mathematics of Computation 70 (2001), 873-891,
DOI 10.1090/S0025-5718-00-01197-2.
Author deposit: arXiv 1903.06820v1, file pseudo1.tex.
Full file hash 1b9c1510d7cd24d79d21b72275648d065c9b620bd12989ae960bcdb80964cf38.

Spans used:
- Greatest common monic divisor: pseudo1.tex lines 617-624,
  span hash 7d8ab0c0b8d50501b807af1813cac82bc6fbcf1148a3c68fe01abda32e805512.
- Frobenius probable-prime test with three steps: lines 713-741,
  span hash 24035e1b362966fef29efa3397687b31aa005330056575e39c1515139e797e17.
- Frobenius pseudoprime definition: lines 763-768,
  span hash eb069e234371aec6cc8d64a51ae05c96451f9ded28ed704f7619df9f5abd51f6.

Locator note: the probable-prime algorithm and the pseudoprime definition are
unnumbered definitions in section 3. Theorem 3.1 states prime-field
consequences that motivate the test; it is not the test definition.
No Definition 3.1 locator is used.
-/

@[expose]
public section

namespace Polynomial

/-- Greatest common monic divisor (pseudo1.tex lines 617-624).
`IsGreatestCommonMonicDivisor h g1 g2` holds when `h`, `g1` and `g2` are monic
polynomials over a commutative ring and the ideal generated by `g1` and `g2`
equals the principal ideal generated by `h`. Existence is not automatic. -/
public def IsGreatestCommonMonicDivisor {R : Type*} [CommRing R]
    (h g₁ g₂ : _root_.Polynomial R) : Prop :=
  h.Monic ∧ g₁.Monic ∧ g₂.Monic ∧
    Ideal.span ({g₁, g₂} : Set (_root_.Polynomial R)) =
      Ideal.span ({h} : Set (_root_.Polynomial R))

/-- Unfolding of `Polynomial.IsGreatestCommonMonicDivisor`. -/
public theorem IsGreatestCommonMonicDivisor.unfold {R : Type*} [CommRing R]
    (h g₁ g₂ : _root_.Polynomial R) :
    IsGreatestCommonMonicDivisor h g₁ g₂ ↔
      (h.Monic ∧ g₁.Monic ∧ g₂.Monic ∧
        Ideal.span ({g₁, g₂} : Set (_root_.Polynomial R)) =
          Ideal.span ({h} : Set (_root_.Polynomial R))) :=
  Iff.rfl

end Polynomial

namespace Nat

/-- Frobenius probable prime (pseudo1.tex lines 713-741).
`f` is monic over the integers; degree and discriminant are `f.natDegree`
and `f.discr`. `n` is odd, greater than one, and coprime to the natural
absolute value of `f.eval 0 * f.discr`. All algorithm polynomials live over
`ZMod n`: `fs 0` is the coefficientwise reduction of `f`; each `F i` is a
greatest common monic divisor of `X ^ (n ^ i) - X` and `fs (i - 1)` with exact
factorization `fs (i - 1) = F i * fs i`; the stage ends with `fs f.natDegree = 1`.
The Frobenius step asks `F i ∣ (F i).comp (X ^ n)` for `2 ≤ i ≤ d`.
With quotient witnesses `q`, each even `i` satisfies `natDegree (F i) = i * q i`,
and the Jacobi step asks `(-1) ^ S = jacobiSym f.discr n` where `S` sums
`q i` over the even indices, zero elsewhere. -/
public def IsFrobeniusProbablePrime (n : ℕ) (f : _root_.Polynomial ℤ) : Prop :=
  f.Monic ∧ Odd n ∧ 1 < n ∧
    _root_.Nat.Coprime n (Int.natAbs (f.eval 0 * f.discr)) ∧
    ∃ F fs : ℕ → _root_.Polynomial (ZMod n),
      ∃ q : ℕ → ℕ,
        fs 0 = f.map (Int.castRingHom (ZMod n)) ∧
        fs f.natDegree = 1 ∧
        (∀ i ∈ Finset.Icc 1 f.natDegree,
          Polynomial.IsGreatestCommonMonicDivisor (F i)
            (Polynomial.X ^ (n ^ i) - Polynomial.X : _root_.Polynomial (ZMod n))
            (fs (i - 1)) ∧ fs (i - 1) = F i * fs i) ∧
        (∀ i ∈ Finset.Icc 2 f.natDegree,
          F i ∣ (F i).comp (Polynomial.X ^ n : _root_.Polynomial (ZMod n))) ∧
        (∀ i ∈ Finset.Icc 1 f.natDegree, Even i → (F i).natDegree = i * q i) ∧
        (-1 : ℤ) ^
            Finset.sum (Finset.Icc 1 f.natDegree)
              (fun i => if i % 2 = 0 then q i else 0) =
          jacobiSym f.discr n

/-- Frobenius pseudoprime (pseudo1.tex lines 763-768): a composite `n`
that is a Frobenius probable prime with respect to the monic polynomial `f`.
Composite is `¬ n.Prime` conjoined with the probable-prime `1 < n` clause. -/
public def IsFrobeniusPseudoprime (n : ℕ) (f : _root_.Polynomial ℤ) : Prop :=
  ¬ n.Prime ∧ IsFrobeniusProbablePrime n f

/-- Unfolding of `Nat.IsFrobeniusProbablePrime`. -/
public theorem IsFrobeniusProbablePrime.unfold (n : ℕ) (f : _root_.Polynomial ℤ) :
    IsFrobeniusProbablePrime n f ↔
      (f.Monic ∧ Odd n ∧ 1 < n ∧
        _root_.Nat.Coprime n (Int.natAbs (f.eval 0 * f.discr)) ∧
        ∃ F fs : ℕ → _root_.Polynomial (ZMod n),
          ∃ q : ℕ → ℕ,
            fs 0 = f.map (Int.castRingHom (ZMod n)) ∧
            fs f.natDegree = 1 ∧
            (∀ i ∈ Finset.Icc 1 f.natDegree,
              Polynomial.IsGreatestCommonMonicDivisor (F i)
                (Polynomial.X ^ (n ^ i) - Polynomial.X : _root_.Polynomial (ZMod n))
                (fs (i - 1)) ∧ fs (i - 1) = F i * fs i) ∧
            (∀ i ∈ Finset.Icc 2 f.natDegree,
              F i ∣ (F i).comp (Polynomial.X ^ n : _root_.Polynomial (ZMod n))) ∧
            (∀ i ∈ Finset.Icc 1 f.natDegree, Even i → (F i).natDegree = i * q i) ∧
            (-1 : ℤ) ^
                Finset.sum (Finset.Icc 1 f.natDegree)
                  (fun i => if i % 2 = 0 then q i else 0) =
              jacobiSym f.discr n) :=
  Iff.rfl

/-- A Frobenius probable prime uses a monic parameter polynomial. -/
public theorem IsFrobeniusProbablePrime.monic {n : ℕ} {f : _root_.Polynomial ℤ}
    (h : IsFrobeniusProbablePrime n f) : f.Monic :=
  h.1

/-- A Frobenius probable prime candidate is odd. -/
public theorem IsFrobeniusProbablePrime.odd {n : ℕ} {f : _root_.Polynomial ℤ}
    (h : IsFrobeniusProbablePrime n f) : Odd n :=
  h.2.1

/-- A Frobenius probable prime candidate exceeds one. -/
public theorem IsFrobeniusProbablePrime.one_lt {n : ℕ} {f : _root_.Polynomial ℤ}
    (h : IsFrobeniusProbablePrime n f) : 1 < n :=
  h.2.2.1

/-- Unfolding of `Nat.IsFrobeniusPseudoprime`. -/
public theorem IsFrobeniusPseudoprime.unfold (n : ℕ) (f : _root_.Polynomial ℤ) :
    IsFrobeniusPseudoprime n f ↔
      (¬ n.Prime ∧ IsFrobeniusProbablePrime n f) :=
  Iff.rfl

/-- A Frobenius pseudoprime is composite, as `¬ n.Prime`. -/
public theorem IsFrobeniusPseudoprime.composite {n : ℕ} {f : _root_.Polynomial ℤ}
    (h : IsFrobeniusPseudoprime n f) : ¬ n.Prime :=
  h.1

/-- A Frobenius pseudoprime is a Frobenius probable prime. -/
public theorem IsFrobeniusPseudoprime.probablePrime {n : ℕ} {f : _root_.Polynomial ℤ}
    (h : IsFrobeniusPseudoprime n f) : IsFrobeniusProbablePrime n f :=
  h.2

end Nat

end
