module

public import Mathlib.Algebra.BigOperators.Ring.Finset

namespace MetaMathlibExt

@[expose] public section

/-- A Newton sequence generated by `c`.

Concept `jis_term_29ecdc440e7c28d8af6754c5`. Sources:

- JIS VOL18/Wojcik, <https://cs.uwaterloo.ca/journals/JIS/VOL18/Wojcik/wojcik6.tex>,
  lines 276–280, SHA-256
  `2a3a1d485868744d2d339650be1fbd2f6ec8b1c45821c250f6828c973d15eee8`;
- JIS VOL8/Huang, <https://cs.uwaterloo.ca/journals/JIS/VOL8/Huang/huang11.tex>,
  lines 176–179, SHA-256
  `e280997f941eb46d98b411cb2d2ff593d284837371b6565cd4efdb1cdaabffdb`.

The source sequences begin at index one. Thus `a 0` and `c 0` are unused,
and the recurrence is stated at index `n + 1`. The two sources write the
factors in opposite orders, which agree over the common `CommSemiring`
generalization used here. -/
def IsNewtonSequence {R : Type*} [CommSemiring R] (a c : ℕ → R) : Prop :=
  ∀ n : ℕ,
    a (n + 1) =
      (∑ j ∈ Finset.range n, a (n - j) * c (j + 1)) + ((n + 1 : ℕ) : R) * c (n + 1)

/-- The defining Newton recurrence at a specified index. -/
theorem IsNewtonSequence.eq_recurrence {R : Type*} [CommSemiring R]
    {a c : ℕ → R} (h : IsNewtonSequence a c) (n : ℕ) :
    a (n + 1) =
      (∑ j ∈ Finset.range n, a (n - j) * c (j + 1)) + ((n + 1 : ℕ) : R) * c (n + 1) :=
  h n

end

end MetaMathlibExt
