module

public import Mathlib.RingTheory.DedekindDomain.Different

/-!
# The different of an element

Under the standard AKLB setup, with `A` a commutative ring, `K` its fraction field,
`B` an `A`-algebra, and `L` the fraction field of `B` generated over `K`, the
element different of `α : B` is `aeval α (derivative (minpoly A α))` when
`algebraMap B L α` generates `L` over `K`, and `0` otherwise.

This is the element-level generator appearing in Mathlib's
`conductor_mul_differentIdeal` and `aeval_derivative_mem_differentIdeal`:
membership of the element different in `differentIdeal A B` is proved separately.

## Source correspondence

The principal-different formula is Andrew V. Sutherland, *18.785 Number Theory I*,
Lecture 12,
[Proposition 12.24](https://math.mit.edu/classes/18.785/2021fa/LectureNotes12.pdf#page=9).
In the source's AKLB notation, if `B = A[α]` and `f ∈ A[X]` is the minimal
polynomial of `α`, then `D_{B/A} = (f'(α))`.

The Lean theorem `differentIdeal_eq_span_derivative_of_adjoin_eq_top` matches this
statement clause by clause:

* `IsDomain A`, `IsFractionRing A K`, and `IsIntegrallyClosed A` supply the source's
  Dedekind base and fraction field; `IsIntegralClosure B A L`, `IsFractionRing B L`,
  and `IsDedekindDomain B` identify `B` with the integral closure in its fraction field.
* `FiniteDimensional K L` and `Algebra.IsSeparable K L` are the source's finite separable
  field extension, while the scalar-tower instances identify all of the structure maps.
* `Algebra.adjoin A {α} = ⊤` is exactly the monogenicity hypothesis `B = A[α]`.
  The proof derives `K(α) = L` internally from this equality and
  `IsFractionRing B L`; it is not an additional source assumption.
* `minpoly A α` is the source polynomial `f`, and
  `Ideal.span {Polynomial.aeval α (Polynomial.derivative (minpoly A α))}` is the
  principal ideal `(f'(α))`.  Thus the conclusion is precisely
  `D_{B/A} = (f'(α))`, with no residue-polynomial lift involved.

## Main definition

- `elementDifferent`: the element different `δ_{B/A}(α)`.

## Main results

- `elementDifferent_of_adjoin_eq_top`: the primitive (generator) case.
- `elementDifferent_of_adjoin_ne_top`: the nonprimitive case.
- `elementDifferent_eq_zero_iff`: characterization of when the element different vanishes.
- `elementDifferent_mem_differentIdeal`: membership in `differentIdeal A B` in the primitive case.
- `differentIdeal_eq_span_derivative_of_adjoin_eq_top`: the different is principal generated by
  the derivative of the actual minimal polynomial when `α` generates `B` over `A`.
-/

@[expose] public section

set_option autoImplicit false

variable (A K L : Type*) {B : Type*}
  [CommRing A] [Field K] [CommRing B] [Field L]
  [Algebra A B] [Algebra B L] [Algebra K L]

open Classical in
/-- The element different `δ_{B/A}(α)`: `aeval α (derivative (minpoly A α))` when
`algebraMap B L α` generates `L` over `K`, and `0` otherwise. -/
noncomputable def elementDifferent (α : B) : B :=
  if Algebra.adjoin K {algebraMap B L α} = ⊤ then
    Polynomial.aeval α (Polynomial.derivative (minpoly A α))
  else 0

/-- Primitive case: when `algebraMap B L α` generates `L` over `K`, the element
different is `aeval α (derivative (minpoly A α))`. -/
@[simp]
theorem elementDifferent_of_adjoin_eq_top (α : B)
    (hα : Algebra.adjoin K {algebraMap B L α} = ⊤) :
    elementDifferent A K L α =
      Polynomial.aeval α (Polynomial.derivative (minpoly A α)) := by
  classical
  unfold elementDifferent
  rw [ite_eq_left hα]

/-- Nonprimitive case: when `algebraMap B L α` does not generate `L` over `K`,
the element different is `0`. -/
@[simp]
theorem elementDifferent_of_adjoin_ne_top (α : B)
    (hα : Algebra.adjoin K {algebraMap B L α} ≠ ⊤) :
    elementDifferent A K L α = 0 := by
  classical
  unfold elementDifferent
  rw [ite_eq_right hα]

/-- The element different vanishes iff either `α` is not primitive for `L / K`
or the derivative of its minimal polynomial evaluates to zero at `α`. -/
theorem elementDifferent_eq_zero_iff (α : B) :
    elementDifferent A K L α = 0 ↔
      Algebra.adjoin K {algebraMap B L α} ≠ ⊤ ∨
        Polynomial.aeval α (Polynomial.derivative (minpoly A α)) = 0 := by
  classical
  unfold elementDifferent
  split_ifs with h
  · simp [h]
  · simp [h]

/-- The element different lies in `differentIdeal A B` in the primitive case,
by Mathlib's `aeval_derivative_mem_differentIdeal`. -/
theorem elementDifferent_mem_differentIdeal
    [Algebra A K] [Algebra A L] [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsFractionRing A K]
    [FiniteDimensional K L] [Algebra.IsSeparable K L] [IsIntegralClosure B A L]
    [IsFractionRing B L] [IsIntegrallyClosed A] [IsDedekindDomain B]
    [Module.IsTorsionFree A B]
    (α : B) (hα : Algebra.adjoin K {algebraMap B L α} = ⊤) :
    elementDifferent A K L α ∈ differentIdeal A B := by
  rw [elementDifferent_of_adjoin_eq_top A K L α hα]
  exact aeval_derivative_mem_differentIdeal A K L α hα

/-- The different is principal generated by the derivative of the minimal polynomial,
when `α` generates `B` as an `A`-algebra. -/
theorem differentIdeal_eq_span_derivative_of_adjoin_eq_top
    [Algebra A K] [Algebra A L] [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsFractionRing A K]
    [FiniteDimensional K L] [Algebra.IsSeparable K L] [IsIntegralClosure B A L]
    [IsFractionRing B L] [IsIntegrallyClosed A] [IsDedekindDomain B]
    [Module.IsTorsionFree A B]
    (α : B) (hα : Algebra.adjoin A {α} = ⊤) :
    differentIdeal A B =
      Ideal.span {Polynomial.aeval α (Polynomial.derivative (minpoly A α))} := by
  have hmemB : ∀ b : B,
      algebraMap B L b ∈ IntermediateField.adjoin K {algebraMap B L α} := by
    intro b
    have hb : b ∈ Algebra.adjoin A {α} := by
      rw [hα]
      exact Set.mem_univ b
    refine Algebra.adjoin_induction ?_ ?_ ?_ ?_ hb
    · intro x hx
      have hxα : x = α := Set.mem_singleton_iff.mp hx
      subst hxα
      apply IntermediateField.subset_adjoin
      rfl
    · intro r
      have heq : algebraMap B L (algebraMap A B r) =
          algebraMap K L (algebraMap A K r) := by
        calc
          algebraMap B L (algebraMap A B r) = algebraMap A L r :=
            (IsScalarTower.algebraMap_apply A B L r).symm
          _ = algebraMap K L (algebraMap A K r) :=
            IsScalarTower.algebraMap_apply A K L r
      rw [heq]
      exact (IntermediateField.adjoin K {algebraMap B L α}).algebraMap_mem _
    · intro x y _ _ hx hy
      simpa only [map_add] using add_mem hx hy
    · intro x y _ _ hx hy
      simpa only [map_mul] using mul_mem hx hy
  have hIF : IntermediateField.adjoin K {algebraMap B L α} = ⊤ := by
    apply top_unique
    intro y _
    obtain ⟨a, b, _hb, rfl⟩ := IsFractionRing.div_surjective B y
    exact div_mem (hmemB a) (hmemB b)
  have hfield : Algebra.adjoin K {algebraMap B L α} = ⊤ :=
    (IntermediateField.adjoin_eq_top_iff).mp hIF
  have hmul := conductor_mul_differentIdeal A K L α hfield
  rw [conductor_eq_top_of_adjoin_eq_top hα, Ideal.top_mul] at hmul
  exact hmul
