/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import Batteries.Util.ProofWanted
public import Mathlib.Analysis.Asymptotics.Theta
public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.Data.List.OfFn
public import Mathlib.Logic.Function.Iterate
public import MathlibExt.Combinatorics.InfiniteWord.WordFactorComplexity
public import MathlibExt.Dynamics.EventuallyPeriodicSequence

@[expose] public section

namespace MetaMathlibExt

/-! # Pansiot's factor-complexity classification -/

/--
Pansiot's classification of the factor complexity of a pure morphic sequence generated by a
non-erasing morphism.

Source: Fabien Durand, Julien Leroy, and Gwenaël Richomme, "Do the Properties of an
S-adic Representation Determine Factor Complexity?", Journal of Integer Sequences 16
(2013), Article 13.2.6, Theorem [Pansiot] (label `thm: pansiot`), lines 267–283,
quoting J.-J. Pansiot,
<https://cs.uwaterloo.ca/journals/JIS/VOL16/Durand/durand2.tex>.

The quotation omits two hypotheses that the `Θ` lower bounds need; both are added here:
`w` is not eventually periodic, and every letter of `A` occurs in `w`. Without the first,
`σ a = [a, b]`, `σ b = [b]` fails the `Θ(n^2)` case, since `w = a b b b ⋯` has only two
factors of each positive length. Without the second, letters absent from `w` can change the
growth class of `σ` without changing `w`.

The five cases are: everywhere-growing and quasi-uniform gives `O(n)`; polynomially
diverging gives `Θ(n log log n)`; exponentially diverging gives `Θ(n log n)`;
non-everywhere-growing with infinitely many bounded-letter factors gives `Θ(n^2)`;
otherwise the sequence is a morphic image of an everywhere-growing pure fixed point
with the same complexity up to `Θ`.
-/
public theorem_wanted pansiot_factor_complexity_classification
    {A : Type} [Fintype A]
    (σ : A → List A) (a : A) (w : ℕ → A) :
    let wordPrefix {X : Type} (u : ℕ → X) (n : ℕ) : List X :=
      List.ofFn fun i : Fin n => u i
    let iterWord {X : Type} (μ : X → List X) (n : ℕ) (x : X) : List X :=
      Nat.iterate (fun u : List X => u.flatMap μ) n [x]
    let nonErasing {X Y : Type} (μ : X → List Y) : Prop :=
      ∀ x, μ x ≠ []
    let pureFixedPoint {X : Type} (μ : X → List X) (x : X) (u : ℕ → X) : Prop :=
      (∀ n, iterWord μ n x = wordPrefix u (iterWord μ n x).length) ∧
        Filter.Tendsto (fun n => (iterWord μ n x).length) Filter.atTop Filter.atTop
    let boundedLetter {X : Type} (μ : X → List X) (x : X) : Prop :=
      ∃ C, ∀ n, (iterWord μ n x).length ≤ C
    let everywhereGrowing {X : Type} (μ : X → List X) : Prop :=
      ∀ x, ¬boundedLetter μ x
    let factor {X : Type} (u : ℕ → X) (v : List X) : Prop :=
      ∃ i : ℕ, v = List.ofFn fun j : Fin v.length => u (i + j)
    let factorComplexity {X : Type} [Finite X] (u : ℕ → X) (n : ℕ) : ℕ :=
      wordFactorComplexity u n
    let growthTheta {X : Type} (μ : X → List X) (x : X) (g : ℕ → ℝ) : Prop :=
      Asymptotics.IsTheta Filter.atTop
        (fun n => ((iterWord μ n x).length : ℝ)) g
    let quasiUniform {X : Type} (μ : X → List X) : Prop :=
      ∃ β : ℝ, 1 ≤ β ∧ ∀ x, growthTheta μ x (fun n => β ^ n)
    let polynomiallyDiverging {X : Type} (μ : X → List X) : Prop :=
      ∃ (β : ℝ) (α : X → ℕ), 1 < β ∧ α ≠ 0 ∧
        ∀ x, growthTheta μ x (fun n => (n : ℝ) ^ α x * β ^ n)
    let exponentiallyDiverging {X : Type} (μ : X → List X) : Prop :=
      ∃ (x₁ x₂ : X) (α₁ α₂ : ℕ) (β₁ β₂ : ℝ),
        1 < β₁ ∧ 1 < β₂ ∧ β₁ ≠ β₂ ∧
          growthTheta μ x₁ (fun n => (n : ℝ) ^ α₁ * β₁ ^ n) ∧
          growthTheta μ x₂ (fun n => (n : ℝ) ^ α₂ * β₂ ^ n)
    let morphicImage {X Y : Type} (coding : X → List Y) (u : ℕ → X)
        (v : ℕ → Y) : Prop :=
      Filter.Tendsto (fun n => ((wordPrefix u n).flatMap coding).length)
          Filter.atTop Filter.atTop ∧
        ∀ n, (wordPrefix u n).flatMap coding =
          wordPrefix v ((wordPrefix u n).flatMap coding).length
    nonErasing σ →
      pureFixedPoint σ a w →
      (∀ x : A, ∃ i, w i = x) →
      ¬IsEventuallyPeriodic w →
        ((everywhereGrowing σ ∧ quasiUniform σ) →
            Asymptotics.IsBigO Filter.atTop
              (fun n => (factorComplexity w n : ℝ)) (fun n => (n : ℝ))) ∧
        ((everywhereGrowing σ ∧ polynomiallyDiverging σ) →
            Asymptotics.IsTheta Filter.atTop
              (fun n => (factorComplexity w n : ℝ))
              (fun n => (n : ℝ) * Real.log (Real.log (n : ℝ)))) ∧
        ((everywhereGrowing σ ∧ exponentiallyDiverging σ) →
            Asymptotics.IsTheta Filter.atTop
              (fun n => (factorComplexity w n : ℝ))
              (fun n => (n : ℝ) * Real.log (n : ℝ))) ∧
        ((¬everywhereGrowing σ ∧
            Set.Infinite {v : List A | factor w v ∧ ∀ x ∈ v, boundedLetter σ x}) →
            Asymptotics.IsTheta Filter.atTop
              (fun n => (factorComplexity w n : ℝ)) (fun n => (n : ℝ) ^ 2)) ∧
        ((¬everywhereGrowing σ ∧
            Set.Finite {v : List A | factor w v ∧ ∀ x ∈ v, boundedLetter σ x}) →
          ∃ (B : Type) (_ : Fintype B) (b : B) (τ : B → List B) (v : ℕ → B)
              (coding : B → List A),
            everywhereGrowing τ ∧ nonErasing coding ∧ pureFixedPoint τ b v ∧
              morphicImage coding v w ∧
              Asymptotics.IsTheta Filter.atTop
                (fun n => (factorComplexity w n : ℝ))
                (fun n => (factorComplexity (X := B) v n : ℝ)))

end MetaMathlibExt
