/-
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.

This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
-/

module

public import Mathlib.Algebra.Group.Pointwise.Set.Basic
public import Mathlib.Algebra.Group.Submonoid.Membership
public import Mathlib.Algebra.Group.Subgroup.Pointwise

open scoped Pointwise

@[expose] public section

namespace Subgroup

variable {G : Type*} [Group G] {X : Set G}

/-- Source 2310.10246 D01 (main.tex:146): for a group `G` and `X ⊆ G`,
with `X⁰ = {e}`, `X¹ = X`, `Xⁿ⁺¹ = Xⁿ * X` (Mathlib pointwise `Set` powers),
if `X = X⁻¹` then the subgroup generated by `X` equals `⋃ n : ℕ, X ^ n`,
i.e. `↑(Subgroup.closure X) = ⋃ n, X ^ n`. -/
theorem closure_eq_iUnion_pow (hX : X⁻¹ = X) :
    (Subgroup.closure X : Set G) = ⋃ n : ℕ, X ^ n := by
  have hUnion : X ∪ X⁻¹ = X := by
    rw [hX, Set.union_self]
  have hSubmonoid : (Subgroup.closure X).toSubmonoid = Submonoid.closure X := by
    calc
      (Subgroup.closure X).toSubmonoid = Submonoid.closure (X ∪ X⁻¹) :=
        Subgroup.closure_toSubmonoid X
      _ = Submonoid.closure X := by rw [hUnion]
  have h_eq : (Submonoid.closure X : Set G) = ⋃ n : ℕ, X ^ n := by
    rw [Submonoid.closure_eq_image_prod]
    apply Set.eq_of_subset_of_subset
    · intro x hx
      simp only [Set.mem_image, Set.mem_ofPred_eq] at hx
      obtain ⟨l, hl, rfl⟩ := hx
      induction l with
      | nil =>
        exact Set.mem_iUnion.mpr ⟨0, by simp⟩
      | cons hd tl ih =>
        have hhd : hd ∈ X := hl hd (by simp)
        have htl : ∀ y ∈ tl, y ∈ X := fun y hy => hl y (List.mem_cons_of_mem hd hy)
        have hmem_tl : List.prod tl ∈ (⋃ n : ℕ, X ^ n) := ih htl
        obtain ⟨n, hn⟩ : ∃ n : ℕ, List.prod tl ∈ (X ^ n) := Set.mem_iUnion.mp hmem_tl
        have hmul : hd * List.prod tl ∈ X * (X ^ n) :=
          Set.mul_mem_mul hhd hn
        have hpow : X * (X ^ n) = X ^ (n + 1) :=
          (pow_succ' X n).symm
        have hmem : hd * List.prod tl ∈ X ^ (n + 1) :=
          hpow ▸ hmul
        exact Set.mem_iUnion.mpr ⟨n + 1, hmem⟩
    · intro x hx
      simp only [Set.mem_iUnion] at hx
      obtain ⟨n, hn⟩ := hx
      induction n generalizing x with
      | zero =>
        have hx1 : x = 1 := by
          simpa [Set.mem_singleton_iff] using hn
        subst hx1
        exact ⟨[], by simp, by simp⟩
      | succ n ih =>
        have hpow : X ^ (n + 1) = X * (X ^ n) :=
          pow_succ' X n
        have hx_mul : x ∈ X * (X ^ n) := by
          rw [← hpow]
          exact hn
        obtain ⟨a, ha, b, hb, rfl⟩ := Set.mem_mul.mp hx_mul
        obtain ⟨l, hl, rfl⟩ := ih hb
        exact ⟨a :: l, by
          intro y hy
          simp only [List.mem_cons] at hy
          rcases hy with rfl | hy
          · exact ha
          · exact hl y hy, by simp⟩
  calc
    (Subgroup.closure X : Set G) = ((Subgroup.closure X).toSubmonoid : Set G) := rfl
    _ = (Submonoid.closure X : Set G) := by rw [hSubmonoid]
    _ = ⋃ n : ℕ, X ^ n := h_eq

end Subgroup

end
