/-
Authors: Adam Kiezun, Muse Spark 1.3, Codex
-/
module

public import Mathlib.NumberTheory.Padics.PadicIntegers

import Mathlib.Algebra.AlgebraicCard
import Mathlib.Algebra.MvPolynomial.Cardinal
import Mathlib.Algebra.MvPolynomial.Funext
import Mathlib.Analysis.Normed.Group.Ultra
import Mathlib.FieldTheory.PrimitiveElement
import Mathlib.NumberTheory.Padics.Hensel
import Mathlib.NumberTheory.Padics.RingHoms
import Mathlib.RingTheory.AlgebraicIndependent.Adjoin
import Mathlib.RingTheory.AlgebraicIndependent.Transcendental
import Mathlib.Topology.Algebra.Module.Cardinality

/-!
# Cassels' embedding theorem

The subring generated by a finite subset of a characteristic-zero field embeds into the
p-adic integers for some prime at least three.
-/

noncomputable section

namespace Subring

/-- A finite set has a finite transcendence basis over `ℚ`. -/
private theorem cassels_transcendence_basis {K : Type*} [Field K] [CharZero K]
    (S : Finset K) :
    ∃ (d : ℕ) (T : Fin d → K), AlgebraicIndependent ℚ T ∧
      ∀ s ∈ S, IsAlgebraic ↥(IntermediateField.adjoin ℚ (Set.range T)) s := by
  classical
  have hIsEmpty : IsEmpty ↥(∅ : Set K) := ⟨fun x => Set.notMem_empty x.1 x.2⟩
  have hemptySet : AlgebraicIndepOn ℚ (id : K → K) (∅ : Set K) :=
    algebraicIndependent_empty_type
  have hempty : AlgebraicIndepOn ℚ (id : K → K) (↑(∅ : Finset K) : Set K) := by
    rwa [Finset.coe_empty]
  obtain ⟨U, hUmem, hUmax⟩ := Finset.exists_max_image
    (S.powerset.filter
      (fun (U : Finset K) => AlgebraicIndepOn ℚ (id : K → K) (↑U : Set K)))
    Finset.card ⟨∅, Finset.mem_filter.mpr
      ⟨Finset.mem_powerset.mpr (Finset.empty_subset _), hempty⟩⟩
  have hUS : U ⊆ S := Finset.mem_powerset.mp (Finset.mem_filter.mp hUmem).1
  have hU : AlgebraicIndepOn ℚ (id : K → K) (↑U : Set K) :=
    (Finset.mem_filter.mp hUmem).2
  have hmax : ∀ V : Finset K, U ⊆ V → V ⊆ S →
      AlgebraicIndepOn ℚ (id : K → K) (↑V : Set K) → V = U := by
    intro V hUV hVS hV
    have hVmem : V ∈ S.powerset.filter
        (fun (U : Finset K) => AlgebraicIndepOn ℚ (id : K → K) (↑U : Set K)) :=
      Finset.mem_filter.mpr ⟨Finset.mem_powerset.mpr hVS, hV⟩
    have hcard : V.card ≤ U.card := hUmax V hVmem
    exact (Finset.eq_of_subset_of_card_le hUV hcard).symm
  refine ⟨Fintype.card ↥(↑U : Set K),
    Subtype.val ∘ (Fintype.equivFin ↥(↑U : Set K)).symm, ?_, ?_⟩
  · exact (algebraicIndependent_equiv
      (Fintype.equivFin ↥(↑U : Set K)).symm).mpr hU
  · have hTU : Set.range
        (Subtype.val ∘ (Fintype.equivFin ↥(↑U : Set K)).symm) = ↑U := by
      rw [Set.range_comp,
        Set.range_eq_univ.mpr (Fintype.equivFin ↥(↑U : Set K)).symm.surjective,
        Set.image_univ, Subtype.range_coe]
    intro s hs
    rw [hTU]
    by_cases hsU : s ∈ U
    · exact isAlgebraic_algebraMap
        (R := ↥(IntermediateField.adjoin ℚ (↑U : Set K))) ⟨s,
        IntermediateField.subset_adjoin _ _ (Finset.mem_coe.mpr hsU)⟩
    · have hsi : s ∉ (↑U : Set K) := fun h => hsU (Finset.mem_coe.mp h)
      have hnot : ¬ AlgebraicIndepOn ℚ (id : K → K) (↑(insert s U) : Set K) := by
        intro hV
        have heq := hmax (insert s U) (Finset.subset_insert _ _)
          (Finset.insert_subset hs hUS) hV
        have hmem : s ∈ insert s U := Finset.mem_insert_self s U
        rw [heq] at hmem
        exact hsU hmem
      rw [Finset.coe_insert, AlgebraicIndepOn.insert_iff hsi] at hnot
      have hnt : ¬ Transcendental ↥(Algebra.adjoin ℚ ((id : K → K) '' ↑U))
          ((id : K → K) s) :=
        fun ht => hnot ⟨hU, ht⟩
      rw [Set.image_id] at hnt
      have halg : IsAlgebraic ↥(Algebra.adjoin ℚ (↑U : Set K)) s :=
        of_not_not (fun h => hnt h)
      have hle : Algebra.adjoin ℚ (↑U : Set K) ≤
          (IntermediateField.adjoin ℚ (↑U : Set K)).toSubalgebra :=
        IntermediateField.algebra_adjoin_le_adjoin _ _
      exact IsAlgebraic.tower_top_of_subalgebra_le hle halg

/-- The evaluation map from integer polynomials at the transcendence basis. -/
private def cassels_iota {K : Type*} [Field K] [CharZero K] (d : ℕ) (T : Fin d → K) :
    MvPolynomial (Fin d) ℤ →+* ↥(IntermediateField.adjoin ℚ (Set.range T)) :=
  MvPolynomial.eval₂Hom (Int.castRingHom _)
    (fun i => ⟨T i, IntermediateField.subset_adjoin _ _ ⟨i, rfl⟩⟩)

/-- Primitive element for the finitely generated extension. -/
private theorem cassels_primitive {K : Type*} [Field K] [CharZero K]
    (d : ℕ) (T : Fin d → K) (S : Finset K)
    (hS : ∀ s ∈ S, IsAlgebraic ↥(IntermediateField.adjoin ℚ (Set.range T)) s) :
    ∃ θ : K, IsIntegral ↥(IntermediateField.adjoin ℚ (Set.range T)) θ ∧
      ∀ s ∈ S, s ∈ IntermediateField.adjoin
        ↥(IntermediateField.adjoin ℚ (Set.range T)) {θ} := by
  set E : IntermediateField ℚ K := IntermediateField.adjoin ℚ (Set.range T) with hE
  set L : IntermediateField ↥E K := IntermediateField.adjoin ↥E (↑S : Set K) with hL
  have hgen : ∀ x ∈ (↑S : Set K), IsIntegral ↥E x := by
    intro x hx
    exact IsAlgebraic.isIntegral (hS x (Finset.mem_coe.mp hx))
  have hfin : FiniteDimensional ↥E ↥L :=
    IntermediateField.finiteDimensional_adjoin hgen
  have hisInt : Algebra.IsIntegral ↥E ↥L := Algebra.IsIntegral.of_finite ↥E ↥L
  have hintα : ∀ α : ↥L, IsIntegral ↥E α := fun α => IsIntegral.of_finite ↥E α
  obtain ⟨α, hα⟩ := Field.exists_primitive_element ↥E ↥L
  have hinj : Function.Injective (L.val) := Subtype.val_injective
  refine ⟨(α : K), (isIntegral_algHom_iff (L.val) hinj).mpr (hintα α), ?_⟩
  intro s hs
  have hsL : s ∈ L :=
    IntermediateField.subset_adjoin ↥E (↑S : Set K) (Finset.mem_coe.mpr hs)
  set y : ↥L := ⟨s, hsL⟩ with hy
  have hyT : y ∈ (⊤ : IntermediateField ↥E ↥L) := IntermediateField.mem_top
  rw [← hα] at hyT
  have hmem : (L.val) y ∈ IntermediateField.adjoin ↥E ({((α : K))} : Set K) := by
    have h1 : (L.val) y ∈
        (IntermediateField.adjoin ↥E ({α} : Set ↥L)).map (L.val) :=
      (IntermediateField.map_mem_map _ _).mpr hyT
    rwa [IntermediateField.adjoin_map _ _ _, Set.image_singleton] at h1
  exact hmem

/-- The evaluation map is injective. -/
private theorem cassels_iota_injective {K : Type*} [Field K] [CharZero K]
    (d : ℕ) (T : Fin d → K) (hT : AlgebraicIndependent ℚ T) :
    Function.Injective (cassels_iota d T) := by
  have hZ : AlgebraicIndependent ℤ T :=
    hT.restrictScalars (IsFractionRing.injective ℤ ℚ)
  have hhom : ((IntermediateField.val _).toRingHom).comp (cassels_iota d T) =
      MvPolynomial.eval₂Hom (algebraMap ℤ K) T := by
    apply MvPolynomial.ringHom_ext
    · intro r
      simp
    · intro i
      simp only [RingHom.comp_apply, cassels_iota, MvPolynomial.eval₂Hom_X']
      rfl
  intro p q hpq
  apply hZ
  have hpoint : ∀ r : MvPolynomial (Fin d) ℤ, MvPolynomial.aeval T r =
      ((IntermediateField.val _).toRingHom) ((cassels_iota d T) r) := by
    intro r
    rw [MvPolynomial.aeval_eq_eval₂Hom]
    exact (RingHom.congr_fun hhom r).symm
  rw [hpoint p, hpoint q]
  exact congrArg _ hpq

/-- Auxiliary: clear rational denominators of finitely many polynomials. -/
private theorem cassels_clear_denom (d : ℕ) (SQ : Finset (MvPolynomial (Fin d) ℚ)) :
    ∃ D : ℤ, D ≠ 0 ∧ ∀ Q ∈ SQ, ∃ Q' : MvPolynomial (Fin d) ℤ,
      MvPolynomial.map (Int.castRingHom ℚ) Q' = D • Q := by
  refine ⟨((∏ Q ∈ SQ, ∏ s ∈ Q.support, (Q.coeff s).den : ℕ) : ℤ), ?_, ?_⟩
  · apply Int.natCast_ne_zero.mpr
    apply ne_of_gt
    apply Finset.prod_pos
    intro Q hQ
    apply Finset.prod_pos
    intro s hs
    exact Nat.pos_of_ne_zero (Rat.den_nz _)
  · intro Q hQ
    refine (MvPolynomial.mem_range_map_iff_coeffs_subset (f := Int.castRingHom ℚ)).mpr ?_
    intro c hc
    obtain ⟨s, hs, rfl⟩ := MvPolynomial.mem_coeffs_iff.mp (Finset.mem_coe.mp hc)
    rw [MvPolynomial.coeff_smul, zsmul_eq_mul]
    by_cases hsQ : s ∈ Q.support
    · have hdvd : (Q.coeff s).den ∣ ∏ Q ∈ SQ, ∏ s ∈ Q.support, (Q.coeff s).den :=
        (Finset.dvd_prod_of_mem (fun s => (Q.coeff s).den) hsQ).trans
          (Finset.dvd_prod_of_mem (fun Q => ∏ s ∈ Q.support, (Q.coeff s).den) hQ)
      obtain ⟨k, hk⟩ := hdvd
      have hden : (((Q.coeff s).den : ℕ) : ℚ) ≠ 0 :=
        Nat.cast_ne_zero.mpr (Rat.den_nz _)
      have hnum : (((Q.coeff s).num : ℤ) : ℚ) = Q.coeff s * (((Q.coeff s).den : ℕ) : ℚ) :=
        (div_eq_iff hden).mp (Rat.num_div_den _)
      refine ⟨(k * (Q.coeff s).num : ℤ), ?_⟩
      simp only [eq_intCast, Int.cast_mul, Int.cast_natCast]
      rw [hk, Nat.cast_mul]
      linear_combination (k : ℚ) * hnum
    · have h0 : Q.coeff s = 0 := by
        by_contra hne
        exact hsQ (MvPolynomial.mem_support_iff.mpr hne)
      rw [h0]
      simp

/-- Common denominator for finitely many elements of `E`. -/
private theorem cassels_common_denom {K : Type*} [Field K] [CharZero K]
    (d : ℕ) (T : Fin d → K) (hT : AlgebraicIndependent ℚ T)
    (Z : Finset ↥(IntermediateField.adjoin ℚ (Set.range T))) :
    ∃ q : MvPolynomial (Fin d) ℤ, q ≠ 0 ∧
      ∀ z ∈ Z, ∃ P : MvPolynomial (Fin d) ℤ,
        (cassels_iota d T) q * z = (cassels_iota d T) P := by
  classical
  have h2E : ∀ Q : MvPolynomial (Fin d) ℚ,
      (IntermediateField.val _).toRingHom ((hT.aevalEquivField) (algebraMap _ _ Q))
        = ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) Q :=
    fun Q => hT.aevalEquivField_algebraMap_apply_coe Q
  have e0surj : Function.Surjective ⇑(hT.aevalEquivField) :=
    EquivLike.surjective (hT.aevalEquivField)
  have hhomQ : ((IntermediateField.val _).toRingHom).comp (cassels_iota d T) =
      MvPolynomial.eval₂Hom (algebraMap ℤ K) T := by
    apply MvPolynomial.ringHom_ext
    · intro r
      simp
    · intro i
      simp only [RingHom.comp_apply, cassels_iota, MvPolynomial.eval₂Hom_X']
      rfl
  have aevalQK : ∀ x : MvPolynomial (Fin d) ℚ,
      ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) x =
      ((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K) x := fun x => rfl
  have iotaQ : ∀ P : MvPolynomial (Fin d) ℤ,
      ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom)
        (MvPolynomial.map (Int.castRingHom ℚ) P) =
      (IntermediateField.val _).toRingHom (cassels_iota d T P) := by
    intro P
    rw [aevalQK, show MvPolynomial.map (Int.castRingHom ℚ) P =
      MvPolynomial.map (algebraMap ℤ ℚ) P from by rw [← algebraMap_int_eq],
      MvPolynomial.aeval_map_algebraMap ℚ T P, MvPolynomial.aeval_eq_eval₂Hom T P]
    exact (RingHom.congr_fun hhomQ P).symm
  have ex : ∀ z : ↥(IntermediateField.adjoin ℚ (Set.range T)), z ∈ Z →
      ∃ w : FractionRing (MvPolynomial (Fin d) ℚ), (hT.aevalEquivField) w = z :=
    fun z _ => e0surj z
  choose wfn hwfn using ex
  have hmult := IsLocalization.map_integerMultiple
    (nonZeroDivisors (MvPolynomial (Fin d) ℚ)) Z.attach
    (fun a : ↥Z => wfn a.1 a.2)
  have hb : ((IsLocalization.commonDenom (nonZeroDivisors (MvPolynomial (Fin d) ℚ))
      Z.attach (fun a : ↥Z => wfn a.1 a.2) : nonZeroDivisors _) :
      MvPolynomial (Fin d) ℚ) ≠ 0 :=
    mem_nonZeroDivisors_iff_ne_zero.mp
      (IsLocalization.commonDenom (nonZeroDivisors (MvPolynomial (Fin d) ℚ)) Z.attach
        (fun a : ↥Z => wfn a.1 a.2)).2
  have BK : ∀ (z : ↥(IntermediateField.adjoin ℚ (Set.range T))) (hz : z ∈ Z),
      ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom)
        ((IsLocalization.commonDenom (nonZeroDivisors (MvPolynomial (Fin d) ℚ))
          Z.attach (fun a : ↥Z => wfn a.1 a.2) : nonZeroDivisors _) :
          MvPolynomial (Fin d) ℚ) *
        (IntermediateField.val _).toRingHom z =
      ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom)
        (IsLocalization.integerMultiple (nonZeroDivisors (MvPolynomial (Fin d) ℚ))
          Z.attach (fun a : ↥Z => wfn a.1 a.2) ⟨⟨z, hz⟩, Finset.mem_attach _ _⟩) := by
    intro z hz
    have hmapEq : algebraMap (MvPolynomial (Fin d) ℚ)
        (FractionRing (MvPolynomial (Fin d) ℚ))
        (IsLocalization.integerMultiple (nonZeroDivisors (MvPolynomial (Fin d) ℚ))
          Z.attach (fun a : ↥Z => wfn a.1 a.2) ⟨⟨z, hz⟩, Finset.mem_attach _ _⟩) =
        (((IsLocalization.commonDenom (nonZeroDivisors (MvPolynomial (Fin d) ℚ))
          Z.attach (fun a : ↥Z => wfn a.1 a.2) : nonZeroDivisors _) :
          MvPolynomial (Fin d) ℚ) • wfn z hz) :=
      hmult ⟨⟨z, hz⟩, Finset.mem_attach _ _⟩
    have step1 := congrArg (fun w =>
      (IntermediateField.val _).toRingHom ((hT.aevalEquivField) w)) hmapEq
    rw [Algebra.smul_def] at step1
    simp only [map_mul] at step1
    rw [h2E, h2E, hwfn z hz] at step1
    exact step1.symm
  obtain ⟨D, hD, hQD⟩ := cassels_clear_denom d
    (insert ((IsLocalization.commonDenom (nonZeroDivisors (MvPolynomial (Fin d) ℚ))
      Z.attach (fun a : ↥Z => wfn a.1 a.2) : nonZeroDivisors _) : MvPolynomial (Fin d) ℚ)
    (Z.attach.image (fun a : ↥Z =>
      IsLocalization.integerMultiple (nonZeroDivisors (MvPolynomial (Fin d) ℚ))
        Z.attach (fun a : ↥Z => wfn a.1 a.2) ⟨a, Finset.mem_attach _ a⟩)))
  obtain ⟨Qb', hQb'⟩ := hQD _ (Finset.mem_insert_self _ _)
  have vinj : Function.Injective (IntermediateField.val
      (IntermediateField.adjoin ℚ (Set.range T))).toRingHom :=
    Subtype.val_injective
  have scaleQ : ∀ Q : MvPolynomial (Fin d) ℚ,
      ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) (D • Q) =
      ((D : K)) * ((((MvPolynomial.aeval T) :
        MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) Q := by
    intro Q
    rw [zsmul_eq_mul, map_mul, map_intCast]
  have hCD : ((D : MvPolynomial (Fin d) ℚ)) ≠ 0 := by
    rw [show ((D : MvPolynomial (Fin d) ℚ)) = MvPolynomial.C (((D : ℤ)) : ℚ) from
      (map_intCast _ _).symm]
    exact MvPolynomial.C_ne_zero.mpr (Int.cast_ne_zero.mpr hD)
  have hDb : D • (((IsLocalization.commonDenom
      (nonZeroDivisors (MvPolynomial (Fin d) ℚ)) Z.attach
      (fun a : ↥Z => wfn a.1 a.2) : nonZeroDivisors _) : MvPolynomial (Fin d) ℚ)) ≠ 0 := by
    rw [zsmul_eq_mul]
    exact mul_ne_zero hCD hb
  refine ⟨Qb', ?_, ?_⟩
  · intro h0
    exact hDb (by rw [← hQb', h0, map_zero])
  · intro z hz
    obtain ⟨Qx', hQx'⟩ := hQD _ (Finset.mem_insert_of_mem
      (Finset.mem_image.mpr ⟨⟨z, hz⟩, Finset.mem_attach _ _, rfl⟩))
    refine ⟨Qx', ?_⟩
    apply vinj
    rw [map_mul, ← iotaQ, ← iotaQ, hQb', hQx', scaleQ, scaleQ, mul_assoc, BK z hz]

/-- Extend a map from `E` to a simple extension by sending the generator to a root. -/
private theorem cassels_extend {K : Type*} [Field K] [CharZero K] (E : IntermediateField ℚ K)
    (θ : K) (hint : IsIntegral ↥E θ) (p : ℕ) [Fact p.Prime]
    (σE : ↥E →+* ℚ_[p]) (z : ℚ_[p])
    (hz : Polynomial.eval₂ σE z (minpoly ↥E θ) = 0) :
    ∃ σ : ↥(IntermediateField.adjoin ↥E {θ}) →+* ℚ_[p],
      (∀ e : ↥E, σ (algebraMap ↥E _ e) = σE e) ∧
        σ (IntermediateField.AdjoinSimple.gen ↥E θ) = z := by
  have hgen : (IntermediateField.adjoin.powerBasis hint).gen =
      IntermediateField.AdjoinSimple.gen ↥E θ :=
    IntermediateField.adjoin.powerBasis_gen hint
  have hmin : minpoly ↥E (IntermediateField.adjoin.powerBasis hint).gen =
      minpoly ↥E θ := by
    rw [hgen, IntermediateField.minpoly_gen]
  have h2 : Polynomial.eval₂ σE z
      (minpoly ↥E (IntermediateField.adjoin.powerBasis hint).gen) = 0 := by
    rw [hmin]; exact hz
  have hy : @Polynomial.aeval ↥E ℚ_[p] _ _ σE.toAlgebra z
      (minpoly ↥E (IntermediateField.adjoin.powerBasis hint).gen) = 0 := by
    rw [@Polynomial.aeval_def ↥E ℚ_[p] _ _ σE.toAlgebra z _,
      RingHom.algebraMap_toAlgebra]
    exact h2
  let Falg := (@PowerBasis.lift (S := ↥(IntermediateField.adjoin ↥E {θ})) (A := ↥E)
    (S' := ℚ_[p]) _ _ _ _ σE.toAlgebra
    (IntermediateField.adjoin.powerBasis hint) z hy)
  let hAlg : Algebra ↥E ℚ_[p] := σE.toAlgebra
  have e1 : ∀ e : ↥E, Falg (algebraMap ↥E _ e) = σE e := by
    intro e
    have hc := AlgHom.commutes (φ := Falg) (r := e)
    have hd : algebraMap ↥E ℚ_[p] e = σE e :=
      show (algebraMap ↥E ℚ_[p] : ↥E →+* ℚ_[p]) e = σE e from
        congrFun (congrArg DFunLike.coe (RingHom.algebraMap_toAlgebra σE)) e
    exact hc.trans hd
  have e2 : Falg (IntermediateField.AdjoinSimple.gen ↥E θ) = z := by
    rw [← hgen]
    exact PowerBasis.lift_gen (IntermediateField.adjoin.powerBasis hint) z hy
  refine ⟨@AlgHom.toRingHom ↥E ↥(IntermediateField.adjoin ↥E {θ}) ℚ_[p] _ _ _
    _ σE.toAlgebra Falg, fun e => e1 e, e2⟩

/-- Derivative commutes with scaling the roots. -/
private theorem cassels_derivative_scaleRoots {R : Type*} [CommRing R] [IsAddTorsionFree R]
    (f : Polynomial R) (s : R) :
    Polynomial.derivative (f.scaleRoots s) = (Polynomial.derivative f).scaleRoots s := by
  apply Polynomial.ext
  intro i
  rw [Polynomial.coeff_derivative, Polynomial.coeff_scaleRoots,
    Polynomial.coeff_scaleRoots, Polynomial.coeff_derivative,
    Polynomial.natDegree_derivative]
  have hexp : f.natDegree - (i + 1) = f.natDegree - 1 - i := by omega
  rw [hexp]
  ring

/-- An integral polynomial model for a primitive element, together with a
Bezout identity and common denominators for a prescribed finite set. -/
private theorem cassels_integral_model {K : Type*} [Field K] [CharZero K]
    (d : ℕ) (T : Fin d → K) (hT : AlgebraicIndependent ℚ T) (theta : K)
    (htheta : IsIntegral ↥(IntermediateField.adjoin ℚ (Set.range T)) theta)
    (Z : Finset ↥(IntermediateField.adjoin ℚ (Set.range T))) :
    ∃ q : MvPolynomial (Fin d) ℤ, q ≠ 0 ∧
      ∃ G : Polynomial (MvPolynomial (Fin d) ℤ), G.Monic ∧
        G.map (cassels_iota d T) =
          (minpoly ↥(IntermediateField.adjoin ℚ (Set.range T)) theta).scaleRoots
            ((cassels_iota d T) q) ∧
        ∃ A B : Polynomial (MvPolynomial (Fin d) ℤ),
          ∃ Delta : MvPolynomial (Fin d) ℤ, Delta ≠ 0 ∧
            A * G + B * G.derivative = Polynomial.C Delta ∧
            ∀ z ∈ Z, ∃ P : MvPolynomial (Fin d) ℤ,
              (cassels_iota d T) q * z = (cassels_iota d T) P := by
  classical
  let f := minpoly ↥(IntermediateField.adjoin ℚ (Set.range T)) theta
  let n := f.natDegree
  let Zc := Z ∪ (Finset.range n).image fun i => f.coeff i
  obtain ⟨q, hq, hden⟩ := cassels_common_denom d T hT Zc
  have hdenZ : ∀ z ∈ Z, ∃ P : MvPolynomial (Fin d) ℤ,
      (cassels_iota d T) q * z = (cassels_iota d T) P := by
    intro z hz
    exact hden z (Finset.mem_union_left _ hz)
  have hcoeff : ∀ i < n, ∃ P : MvPolynomial (Fin d) ℤ,
      (cassels_iota d T) q * f.coeff i = (cassels_iota d T) P := by
    intro i hi
    apply hden
    exact Finset.mem_union_right _ <| Finset.mem_image.mpr
      ⟨i, Finset.mem_range.mpr hi, rfl⟩
  let P : ℕ → MvPolynomial (Fin d) ℤ := fun i =>
    if hi : i < n then Classical.choose (hcoeff i hi) else 0
  have hP : ∀ i < n,
      (cassels_iota d T) q * f.coeff i = (cassels_iota d T) (P i) := by
    intro i hi
    simp only [P, dite_eq_left hi]
    exact Classical.choose_spec (hcoeff i hi)
  let G : Polynomial (MvPolynomial (Fin d) ℤ) :=
    Polynomial.X ^ n + ∑ i ∈ Finset.range n,
      Polynomial.C (P i * q ^ (n - 1 - i)) * Polynomial.X ^ i
  have hn : n = f.natDegree := rfl
  have hGdef : G = Polynomial.X ^ n + ∑ i ∈ Finset.range n,
      Polynomial.C (P i * q ^ (n - 1 - i)) * Polynomial.X ^ i := rfl
  have hiinj : Function.Injective (cassels_iota d T) := cassels_iota_injective d T hT
  have hfmonic : f.Monic := minpoly.monic htheta
  have hGmap : G.map (cassels_iota d T) = f.scaleRoots ((cassels_iota d T) q) := by
    apply Polynomial.ext
    intro i
    rw [Polynomial.coeff_map, Polynomial.coeff_scaleRoots, ← hn]
    by_cases hi : i < n
    · have hin : i ≠ n := by omega
      have hexp : n - i = (n - 1 - i) + 1 := by omega
      rw [hGdef, Polynomial.coeff_add, Polynomial.coeff_X_pow,
        ite_eq_right hin, zero_add]
      rw [Polynomial.finsetSum_coeff, Finset.sum_eq_single i]
      · simp only [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow_self, mul_one]
        rw [map_mul, map_pow, ← hP i hi, hexp, pow_succ]
        ring
      · intro j _ hji
        rw [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
          ite_eq_right (Ne.symm hji), mul_zero]
      · intro hnot
        exact (hnot (Finset.mem_range.mpr hi)).elim
    · by_cases hin : i = n
      · subst i
        have hsum :
            (∑ j ∈ Finset.range n,
              Polynomial.C (P j * q ^ (n - 1 - j)) * Polynomial.X ^ j).coeff n = 0 := by
          rw [Polynomial.finsetSum_coeff]
          apply Finset.sum_eq_zero
          intro j hj
          rw [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
            ite_eq_right (Ne.symm (ne_of_lt (Finset.mem_range.mp hj))), mul_zero]
        have hfn : f.coeff n = 1 := by
          simpa only [hn] using hfmonic.coeff_natDegree
        rw [hGdef, Polynomial.coeff_add, Polynomial.coeff_X_pow_self, hsum,
          add_zero, hfn, map_one]
        simp
      · have hni : n < i := by omega
        have hfi : f.coeff i = 0 := by
          apply Polynomial.coeff_eq_zero_of_natDegree_lt
          simpa only [n] using hni
        have hsum :
            (∑ j ∈ Finset.range n,
              Polynomial.C (P j * q ^ (n - 1 - j)) * Polynomial.X ^ j).coeff i = 0 := by
          rw [Polynomial.finsetSum_coeff]
          apply Finset.sum_eq_zero
          intro j hj
          have hjn : j < n := Finset.mem_range.mp hj
          have hji : i ≠ j := by omega
          rw [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
            ite_eq_right hji, mul_zero]
        rw [hGdef, Polynomial.coeff_add, Polynomial.coeff_X_pow,
          ite_eq_right hin, hsum, add_zero, map_zero, hfi, zero_mul]
  have hGmonic : G.Monic := by
    have hmapped : (G.map (cassels_iota d T)).Monic := by
      rw [hGmap]
      exact (Polynomial.monic_scaleRoots_iff _).mpr hfmonic
    apply hiinj
    rw [← Polynomial.leadingCoeff_map_of_injective hiinj G, hmapped, map_one]
  have hdelta : IsUnit ((cassels_iota d T) q) := by
    apply isUnit_iff_ne_zero.mpr
    intro hzero
    exact hq <| hiinj <| hzero.trans (map_zero (cassels_iota d T)).symm
  have hcop0 : IsCoprime f f.derivative :=
    (Polynomial.separable_def f).mp (minpoly.irreducible htheta).separable
  have hcopScaled : IsCoprime (f.scaleRoots ((cassels_iota d T) q))
      (f.derivative.scaleRoots ((cassels_iota d T) q)) :=
    Polynomial.isCoprime_scaleRoots f f.derivative _ hdelta hcop0
  have hGderiv : G.derivative.map (cassels_iota d T) =
      f.derivative.scaleRoots ((cassels_iota d T) q) := by
    rw [← Polynomial.derivative_map, hGmap, cassels_derivative_scaleRoots]
  have hcop : IsCoprime (G.map (cassels_iota d T))
      (G.derivative.map (cassels_iota d T)) := by
    rw [hGmap, hGderiv]
    exact hcopScaled
  obtain ⟨a, b, hab⟩ := hcop
  let Zab := a.support.image (fun i => a.coeff i) ∪
    b.support.image fun i => b.coeff i
  obtain ⟨Delta, hDelta, hdenAB⟩ := cassels_common_denom d T hT Zab
  have liftPoly : ∀ r : Polynomial ↥(IntermediateField.adjoin ℚ (Set.range T)),
      (∀ i ∈ r.support, r.coeff i ∈ Zab) →
      ∃ R : Polynomial (MvPolynomial (Fin d) ℤ),
        R.map (cassels_iota d T) = Polynomial.C ((cassels_iota d T) Delta) * r := by
    intro r hr
    have hnum : ∀ i ∈ r.support, ∃ Q : MvPolynomial (Fin d) ℤ,
        (cassels_iota d T) Delta * r.coeff i = (cassels_iota d T) Q := by
      intro i hi
      exact hdenAB (r.coeff i) (hr i hi)
    let Q : ℕ → MvPolynomial (Fin d) ℤ := fun i =>
      if hi : i ∈ r.support then Classical.choose (hnum i hi) else 0
    have hQ : ∀ i ∈ r.support,
        (cassels_iota d T) Delta * r.coeff i = (cassels_iota d T) (Q i) := by
      intro i hi
      simp only [Q, dite_eq_left hi]
      exact Classical.choose_spec (hnum i hi)
    let R : Polynomial (MvPolynomial (Fin d) ℤ) :=
      ∑ i ∈ r.support, Polynomial.C (Q i) * Polynomial.X ^ i
    have hRdef : R = ∑ i ∈ r.support,
        Polynomial.C (Q i) * Polynomial.X ^ i := rfl
    refine ⟨R, ?_⟩
    apply Polynomial.ext
    intro i
    rw [Polynomial.coeff_map, Polynomial.coeff_C_mul]
    by_cases hi : i ∈ r.support
    · rw [hRdef, Polynomial.finsetSum_coeff, Finset.sum_eq_single i]
      · rw [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow_self, mul_one]
        exact (hQ i hi).symm
      · intro j _ hji
        rw [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
          ite_eq_right (Ne.symm hji), mul_zero]
      · intro hnot
        exact (hnot hi).elim
    · have hri : r.coeff i = 0 := by
        simpa only [Polynomial.mem_support_iff, not_ne_iff] using hi
      have hsum :
          (∑ j ∈ r.support, Polynomial.C (Q j) * Polynomial.X ^ j).coeff i = 0 := by
        rw [Polynomial.finsetSum_coeff]
        apply Finset.sum_eq_zero
        intro j hj
        have hij : i ≠ j := fun hij => hi (hij.symm ▸ hj)
        rw [Polynomial.coeff_C_mul, Polynomial.coeff_X_pow,
          ite_eq_right hij, mul_zero]
      rw [hRdef, hsum, map_zero, hri, mul_zero]
  obtain ⟨A, hA⟩ := liftPoly a fun i hi =>
    Finset.mem_union_left _ <| Finset.mem_image.mpr ⟨i, hi, rfl⟩
  obtain ⟨B, hB⟩ := liftPoly b fun i hi =>
    Finset.mem_union_right _ <| Finset.mem_image.mpr ⟨i, hi, rfl⟩
  have hBezout : A * G + B * G.derivative = Polynomial.C Delta := by
    apply (Polynomial.map_injective (cassels_iota d T) hiinj)
    rw [Polynomial.map_add, Polynomial.map_mul, Polynomial.map_mul, hA, hB,
      Polynomial.map_C]
    calc
      (Polynomial.C ((cassels_iota d T) Delta) * a) * G.map (cassels_iota d T) +
          (Polynomial.C ((cassels_iota d T) Delta) * b) *
            G.derivative.map (cassels_iota d T) =
        Polynomial.C ((cassels_iota d T) Delta) *
          (a * G.map (cassels_iota d T) + b * G.derivative.map (cassels_iota d T)) := by
            ring
      _ = Polynomial.C ((cassels_iota d T) Delta) := by rw [hab, mul_one]
  refine ⟨q, hq, G, hGmonic, ?_, A, B, Delta, hDelta, hBezout, hdenZ⟩
  simpa only [f] using hGmap

/-- Schur's prime-divisor argument: a nonconstant integer polynomial takes
a value divisible by a prime `≥ 3` not dividing a given nonzero integer. -/
private theorem cassels_schur (g : Polynomial ℤ) (M₀ : ℤ)
    (hdeg : 1 ≤ g.natDegree) (hM : M₀ ≠ 0) :
    ∃ (p : ℕ) (b : ℤ), p.Prime ∧ 3 ≤ p ∧ ¬ ((p : ℤ) ∣ M₀) ∧ ((p : ℤ) ∣ g.eval b) := by
  classical
  set L : ℕ := max 3 M₀.natAbs with hL
  have hL3 : 3 ≤ L := le_max_left _ _
  have hLM : M₀.natAbs ≤ L := le_max_right _ _
  have hMpos : 0 < M₀.natAbs := Int.natAbs_pos.mpr hM
  have hbig : ∀ q : ℕ, q.Prime → L < q → ¬ ((q : ℤ) ∣ M₀) := by
    intro q hq hqL hdvd
    have h2 : ((q : ℤ)) ∣ ((M₀.natAbs : ℕ) : ℤ) := Int.dvd_natAbs.mpr hdvd
    have h1 : q ∣ M₀.natAbs := Int.natCast_dvd_natCast.mp h2
    have hle : q ≤ M₀.natAbs := Nat.le_of_dvd hMpos h1
    omega
  have hbig3 : ∀ q : ℕ, q.Prime → L < q → 3 ≤ q := by
    intro q _ hqL
    exact le_trans hL3 (le_of_lt hqL)
  by_cases h0 : g.eval 0 = 0
  · obtain ⟨q, hqL, hqP⟩ := Nat.exists_infinite_primes (L + 1)
    have hLt : L < q := by omega
    refine ⟨q, 0, hqP, hbig3 q hqP hLt, hbig q hqP hLt, ?_⟩
    rw [h0]
    exact dvd_zero _
  · set c : ℤ := g.eval 0 with hc
    set M : ℕ := Nat.factorial L with hMdef
    have hMne : (M : ℤ) ≠ 0 := by
      rw [hMdef]
      exact_mod_cast Nat.factorial_ne_zero L
    have hcM : c * (M : ℤ) ≠ 0 := mul_ne_zero h0 hMne
    set ℓ : Polynomial ℤ := Polynomial.C (c * (M : ℤ)) * Polynomial.X with hℓ
    have hℓdeg : ℓ.natDegree = 1 := by
      rw [hℓ, ← pow_one Polynomial.X]
      exact Polynomial.natDegree_C_mul_X_pow 1 _ hcM
    set h : Polynomial ℤ := g.comp ℓ with hh
    have hhdeg : h.natDegree = g.natDegree := by
      rw [hh, Polynomial.natDegree_comp, hℓdeg, mul_one]
    have hne1 : h - Polynomial.C c ≠ 0 := by
      intro hcon
      have heq : h = Polynomial.C c := sub_eq_zero.mp hcon
      rw [heq, Polynomial.natDegree_C] at hhdeg
      omega
    have hne2 : h - Polynomial.C (-c) ≠ 0 := by
      intro hcon
      have heq : h = Polynomial.C (-c) := sub_eq_zero.mp hcon
      rw [heq, Polynomial.natDegree_C] at hhdeg
      omega
    have hfin : Set.Finite ({y | (h - Polynomial.C c).eval y = 0} ∪
        {y | (h - Polynomial.C (-c)).eval y = 0}) :=
      (Polynomial.finite_setOfPred_isRoot hne1).union
        (Polynomial.finite_setOfPred_isRoot hne2)
    obtain ⟨y, -, hyS⟩ := Set.infinite_univ.exists_notMem_finset hfin.toFinset
    rw [Set.Finite.mem_toFinset] at hyS
    simp only [Set.mem_union, Set.mem_ofPred_eq, not_or] at hyS
    obtain ⟨hy1, hy2⟩ := hyS
    have hhy : h.eval y = g.eval (c * (M : ℤ) * y) := by
      rw [hh, Polynomial.eval_comp]
      congr 1
      simp [hℓ]
    have hv1 : g.eval (c * (M : ℤ) * y) ≠ c := by
      intro hcon
      apply hy1
      rw [Polynomial.eval_sub, Polynomial.eval_C, hhy, hcon, sub_self]
    have hv2 : g.eval (c * (M : ℤ) * y) ≠ -c := by
      intro hcon
      apply hy2
      rw [Polynomial.eval_sub, Polynomial.eval_C, hhy, hcon, sub_self]
    have hdvd : c * (M : ℤ) * y ∣ g.eval (c * (M : ℤ) * y) - c := by
      have hd := Polynomial.sub_dvd_eval_sub (c * (M : ℤ) * y) 0 g
      rwa [sub_zero, ← hc] at hd
    obtain ⟨k, hk⟩ := hdvd
    set v : ℤ := g.eval (c * (M : ℤ) * y) with hv
    set w : ℤ := 1 + (M : ℤ) * (y * k) with hw
    have hvw : v = c * w := by
      rw [hv, hw]
      linear_combination hk
    by_cases hv0 : v = 0
    · obtain ⟨q, hqL, hqP⟩ := Nat.exists_infinite_primes (L + 1)
      have hLt : L < q := by omega
      refine ⟨q, c * (M : ℤ) * y, hqP, hbig3 q hqP hLt, hbig q hqP hLt, ?_⟩
      rw [← hv, hv0]
      exact dvd_zero _
    · have hw0 : w ≠ 0 := by
        intro hcon
        apply hv0
        rw [hvw, hcon, mul_zero]
      have hw1 : w ≠ 1 := by
        intro hcon
        apply hv1
        rw [hvw, hcon, mul_one]
      have hwm1 : w ≠ -1 := by
        intro hcon
        apply hv2
        rw [hvw, hcon, mul_neg, mul_one]
      have hwabs1 : w.natAbs ≠ 1 := by
        rintro hcon
        have hcast : ((w.natAbs : ℕ) : ℤ) = 1 := by exact_mod_cast hcon
        rw [Int.natCast_natAbs] at hcast
        have hsq : w ^ 2 = 1 := by
          have h2 := congrArg (· ^ 2) hcast
          rwa [sq_abs, one_pow] at h2
        rw [sq_eq_one_iff] at hsq
        rcases hsq with h | h
        · exact absurd h hw1
        · exact absurd h hwm1
      obtain ⟨q, hqP, hqdvd⟩ := Nat.exists_prime_and_dvd hwabs1
      have hqw : ((q : ℤ)) ∣ w :=
        Int.natAbs_dvd_natAbs.mp (by rwa [Int.natAbs_natCast])
      have hqv : ((q : ℤ)) ∣ v := by
        rw [hvw]
        exact dvd_mul_of_dvd_right hqw c
      have hqL : L < q := by
        by_contra hcon
        have hcon' : q ≤ L := le_of_not_gt hcon
        have hq0 : 0 < q := hqP.pos
        have hqM : q ∣ M := by
          rw [hMdef]
          exact Nat.dvd_factorial hq0 hcon'
        have hqdvdM : ((q : ℤ)) ∣ (M : ℤ) := Int.natCast_dvd_natCast.mpr hqM
        have hsub := dvd_sub hqw (dvd_mul_of_dvd_left hqdvdM (y * k))
        rw [hw, add_sub_cancel_right] at hsub
        have hq1 : q ∣ 1 := Int.natCast_dvd_natCast.mp (by exact_mod_cast hsub)
        exact hqP.ne_one (Nat.dvd_one.mp hq1)
      refine ⟨q, c * (M : ℤ) * y, hqP, hbig3 q hqP hqL, hbig q hqP hqL, ?_⟩
      rwa [← hv]

/-- The subalgebra generated by finitely many `p`-adic numbers is countable. -/
private theorem cassels_adjoin_countable (p : ℕ) [Fact p.Prime] (d : ℕ)
    (τ : Fin d → ℚ_[p]) :
    Countable ↥(Algebra.adjoin ℚ (Set.range τ)) := by
  classical
  have hcount : Countable (MvPolynomial (Fin d) ℚ) := by
    rw [← Cardinal.mk_le_aleph0_iff]
    calc Cardinal.mk (MvPolynomial (Fin d) ℚ)
        ≤ Cardinal.mk ℚ ⊔ Cardinal.mk (Fin d) ⊔ Cardinal.aleph0 :=
          MvPolynomial.cardinalMk_le_max
      _ ≤ Cardinal.aleph0 ⊔ Cardinal.aleph0 ⊔ Cardinal.aleph0 :=
          sup_le_sup (sup_le_sup Cardinal.mk_le_aleph0 Cardinal.mk_le_aleph0) le_rfl
      _ = Cardinal.aleph0 := by rw [sup_idem, sup_idem]
  have hmem : ∀ P : MvPolynomial (Fin d) ℚ,
      MvPolynomial.aeval (R := ℚ) τ P ∈ Algebra.adjoin ℚ (Set.range τ) := by
    intro P
    rw [Algebra.adjoin_range_eq_range_aeval]
    exact (AlgHom.mem_range (MvPolynomial.aeval (R := ℚ) τ)).mpr ⟨P, rfl⟩
  have hsurj : Function.Surjective (fun P : MvPolynomial (Fin d) ℚ =>
      (⟨MvPolynomial.aeval (R := ℚ) τ P, hmem P⟩ :
        ↥(Algebra.adjoin ℚ (Set.range τ)))) := by
    intro x
    obtain ⟨v, hv⟩ := x
    have hx : v ∈ (MvPolynomial.aeval (R := ℚ) τ).range := by
      rw [← Algebra.adjoin_range_eq_range_aeval]
      exact hv
    obtain ⟨P, hP⟩ := (AlgHom.mem_range (MvPolynomial.aeval (R := ℚ) τ)).mp hx
    exact ⟨P, Subtype.ext hP⟩
  exact @Function.Surjective.countable _ _ hcount _ hsurj

/-- Integer tuples can be approximated by algebraically independent `p`-adic
tuples. -/
private theorem cassels_transcendental_tuple (p : ℕ) [Fact p.Prime] :
    ∀ (d : ℕ) (a : Fin d → ℤ), ∃ τ : Fin d → ℚ_[p],
      AlgebraicIndependent ℚ τ ∧ ∀ i, ‖τ i - a i‖ < 1 := by
  intro d
  induction d with
  | zero =>
    intro a
    refine ⟨Fin.elim0, algebraicIndependent_empty_type, fun i => ?_⟩
    exact i.elim0
  | succ d ih =>
    intro a
    obtain ⟨τ, hτindep, hτclose⟩ := ih (fun i => a i.succ)
    have hA : Countable ↥(Algebra.adjoin ℚ (Set.range τ)) :=
      cassels_adjoin_countable p d τ
    have halg : Set.Countable
        {x : ℚ_[p] | IsAlgebraic ↥(Algebra.adjoin ℚ (Set.range τ)) x} :=
      @Algebraic.countable _ _ _ _ _ _ _ _ hA
    obtain ⟨t, htball, htnalg⟩ :
        ∃ t ∈ Metric.ball ((a 0 : ℤ) : ℚ_[p]) 1,
          ¬ IsAlgebraic ↥(Algebra.adjoin ℚ (Set.range τ)) t := by
      by_contra hcon
      have hall : ∀ t ∈ Metric.ball ((a 0 : ℤ) : ℚ_[p]) 1,
          IsAlgebraic ↥(Algebra.adjoin ℚ (Set.range τ)) t := by
        intro t ht
        by_contra halt
        exact hcon ⟨t, ht, halt⟩
      have hsub : Metric.ball ((a 0 : ℤ) : ℚ_[p]) 1 ⊆
          {x : ℚ_[p] | IsAlgebraic ↥(Algebra.adjoin ℚ (Set.range τ)) x} :=
        fun t ht => hall t ht
      have hcountB :
          Cardinal.mk ↥(Metric.ball ((a 0 : ℤ) : ℚ_[p]) 1) ≤ Cardinal.aleph0 :=
        (Set.Countable.mono hsub halg).le_aleph0
      have hcont : Cardinal.continuum ≤
          Cardinal.mk ↥(Metric.ball ((a 0 : ℤ) : ℚ_[p]) 1) :=
        continuum_le_cardinal_of_isOpen ℚ_[p] Metric.isOpen_ball
          ⟨_, Metric.mem_ball_self zero_lt_one⟩
      exact lt_irrefl _
        (lt_of_le_of_lt (le_trans hcont hcountB) Cardinal.aleph0_lt_continuum)
    set oFam : Option (Fin d) → ℚ_[p] := fun o => o.elim t τ with hoFam
    have hindep : AlgebraicIndependent ℚ oFam :=
      (AlgebraicIndependent.option_iff (R := ℚ) (x := τ) (a := t)).mpr
        ⟨hτindep, htnalg⟩
    set σ : Fin (d + 1) → ℚ_[p] := oFam ∘ finSuccEquiv d with hσ
    have hσindep : AlgebraicIndependent ℚ σ :=
      (algebraicIndependent_equiv (R := ℚ) (finSuccEquiv d) (f := oFam)).mpr
        hindep
    refine ⟨σ, hσindep, ?_⟩
    intro j
    by_cases hj : j = 0
    · subst hj
      simp only [hσ, hoFam, Function.comp_apply, finSuccEquiv_zero, Option.elim]
      rwa [Metric.mem_ball, dist_eq_norm] at htball
    · obtain ⟨i, rfl⟩ := Fin.exists_succ_eq_of_ne_zero hj
      simp only [hσ, hoFam, Function.comp_apply, finSuccEquiv_succ, Option.elim]
      exact hτclose i

/-- Reduction mod `p` commutes with evaluating integer polynomials. -/
private theorem cassels_congr_coeff (p : ℕ) [Fact p.Prime] (d : ℕ)
    (τ' : Fin d → ℤ_[p]) (a : Fin d → ℤ)
    (hcongr : ∀ i, PadicInt.toZMod (τ' i) = ((a i : ℤ) : ZMod p))
    (P : MvPolynomial (Fin d) ℤ) :
    PadicInt.toZMod (MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ' P)
      = ((MvPolynomial.eval a P : ℤ) : ZMod p) := by
  have hint : ∀ z : ℤ, PadicInt.toZMod ((z : ℤ_[p])) = ((z : ZMod p)) := by
    intro z
    have heq : PadicInt.toZMod.comp (Int.castRingHom ℤ_[p]) =
        Int.castRingHom (ZMod p) :=
      Subsingleton.elim _ _
    have hP := RingHom.congr_fun heq z
    rw [RingHom.comp_apply] at hP
    simp only [eq_intCast] at hP
    exact hP
  have heq : PadicInt.toZMod.comp
        (MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ')
      = (Int.castRingHom (ZMod p)).comp (MvPolynomial.eval a) := by
    apply MvPolynomial.ringHom_ext
    · intro r
      simp only [RingHom.comp_apply, MvPolynomial.eval₂Hom_C, MvPolynomial.eval_C]
      exact hint r
    · intro i
      simp only [RingHom.comp_apply, MvPolynomial.eval₂Hom_X',
        MvPolynomial.eval_X]
      exact hcongr i
  calc PadicInt.toZMod (MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ' P)
      = (PadicInt.toZMod.comp
          (MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ')) P := rfl
    _ = ((Int.castRingHom (ZMod p)).comp (MvPolynomial.eval a)) P := by rw [heq]
    _ = ((MvPolynomial.eval a P : ℤ) : ZMod p) := rfl

/-- Reduction mod `p` commutes with evaluating univariate polynomials
over integer polynomials. -/
private theorem cassels_congr_poly (p : ℕ) [Fact p.Prime] (d : ℕ)
    (τ' : Fin d → ℤ_[p]) (a : Fin d → ℤ)
    (hcongr : ∀ i, PadicInt.toZMod (τ' i) = ((a i : ℤ) : ZMod p))
    (G : Polynomial (MvPolynomial (Fin d) ℤ)) (b : ℤ) :
    PadicInt.toZMod ((G.map
      (MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ')).eval (b : ℤ_[p]))
      = ((((G.map (MvPolynomial.eval a)).eval b : ℤ)) : ZMod p) := by
  have hint : ∀ z : ℤ, PadicInt.toZMod ((z : ℤ_[p])) = ((z : ZMod p)) := by
    intro z
    have heq : PadicInt.toZMod.comp (Int.castRingHom ℤ_[p]) =
        Int.castRingHom (ZMod p) :=
      Subsingleton.elim _ _
    have hP := RingHom.congr_fun heq z
    rw [RingHom.comp_apply] at hP
    simp only [eq_intCast] at hP
    exact hP
  have hLHS : PadicInt.toZMod ((G.map
      (MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ')).eval (b : ℤ_[p]))
      = ∑ i ∈ Finset.range (G.natDegree + 1),
        (((MvPolynomial.eval a) (G.coeff i) : ℤ) : ZMod p) * (b : ZMod p) ^ i := by
    rw [Polynomial.eval_map, Polynomial.eval₂_eq_sum_range, map_sum]
    apply Finset.sum_congr rfl
    intro i _
    have h1 := cassels_congr_coeff p d τ' a hcongr (G.coeff i)
    have h2 := hint b
    simp only [map_mul, map_pow, h1, h2]
  have hRHS : ((((G.map (MvPolynomial.eval a)).eval b : ℤ)) : ZMod p)
      = ∑ i ∈ Finset.range (G.natDegree + 1),
        (((MvPolynomial.eval a) (G.coeff i) : ℤ) : ZMod p) * (b : ZMod p) ^ i := by
    rw [Polynomial.eval_map, Polynomial.eval₂_eq_sum_range, Int.cast_sum]
    apply Finset.sum_congr rfl
    intro i _
    rw [Int.cast_mul, Int.cast_pow]
  rw [hLHS, hRHS]

/-- Specialization of the transcendence basis to `p`-adic numbers. -/
private theorem cassels_specialize {K : Type*} [Field K] [CharZero K]
    (d : ℕ) (T : Fin d → K) (hT : AlgebraicIndependent ℚ T)
    (p : ℕ) [Fact p.Prime] (τ' : Fin d → ℤ_[p])
    (hindep : AlgebraicIndependent ℚ (fun i => ((τ' i : ℤ_[p]) : ℚ_[p]))) :
    ∃ σE : ↥(IntermediateField.adjoin ℚ (Set.range T)) →+* ℚ_[p],
      ∀ P : MvPolynomial (Fin d) ℤ,
        σE (cassels_iota d T P)
          = ((MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ' P : ℤ_[p]) : ℚ_[p]) := by
  have hinj : Function.Injective ((MvPolynomial.aeval
      (fun i => ((τ' i : ℤ_[p]) : ℚ_[p]))).toRingHom :
      MvPolynomial (Fin d) ℚ →+* ℚ_[p]) :=
    algebraicIndependent_iff_injective_aeval.mp hindep
  let TE : Fin d → ↥(IntermediateField.adjoin ℚ (Set.range T)) :=
    fun i => ⟨T i, IntermediateField.subset_adjoin _ _ ⟨i, rfl⟩⟩
  let gTQ : MvPolynomial (Fin d) ℚ →+* ↥(IntermediateField.adjoin ℚ (Set.range T)) :=
    (((MvPolynomial.aeval TE) :
      MvPolynomial (Fin d) ℚ →ₐ[ℚ] ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom
  have gTQhom_eq : ∀ x, gTQ x =
      ((((MvPolynomial.aeval TE) :
        MvPolynomial (Fin d) ℚ →ₐ[ℚ] ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom) x :=
    fun x => rfl
  have aevalC_E : ∀ r : ℚ, ((((MvPolynomial.aeval TE) :
      MvPolynomial (Fin d) ℚ →ₐ[ℚ] ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom)
      (MvPolynomial.C r) = algebraMap ℚ ↥(IntermediateField.adjoin ℚ (Set.range T)) r :=
    fun r => MvPolynomial.aeval_C _ r
  have aevalC_K : ∀ r : ℚ, ((((MvPolynomial.aeval T) :
      MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) (MvPolynomial.C r) = algebraMap ℚ K r :=
    fun r => MvPolynomial.aeval_C _ r
  have aevalX_E : ∀ i, ((((MvPolynomial.aeval TE) :
      MvPolynomial (Fin d) ℚ →ₐ[ℚ] ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom)
      (MvPolynomial.X i) = TE i :=
    fun i => MvPolynomial.aeval_X _ i
  have aevalX_K : ∀ i, ((((MvPolynomial.aeval T) :
      MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) (MvPolynomial.X i) = T i :=
    fun i => MvPolynomial.aeval_X _ i
  have bridgeHom : ((IntermediateField.val _).toRingHom).comp gTQ =
      (((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom := by
    apply MvPolynomial.ringHom_ext
    · intro r
      rw [RingHom.comp_apply, gTQhom_eq, aevalC_E, aevalC_K]
      exact AlgHom.commutes _ _
    · intro i
      rw [RingHom.comp_apply, gTQhom_eq, aevalX_E, aevalX_K]
      rfl
  have bridge : ∀ R : MvPolynomial (Fin d) ℚ,
      (IntermediateField.val _).toRingHom (gTQ R) =
        ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) R :=
    fun R => RingHom.congr_fun bridgeHom R
  have hTinj : Function.Injective (((MvPolynomial.aeval T) :
      MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom :=
    algebraicIndependent_iff_injective_aeval.mp hT
  have injT : Function.Injective gTQ := by
    intro P Q hPQ
    have hK : ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) P
        = ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) Q := by
      have h1 := congrArg ((IntermediateField.val _).toRingHom) hPQ
      rw [bridge, bridge] at h1
      exact h1
    exact hTinj hK
  let liftT : FractionRing (MvPolynomial (Fin d) ℚ) →+*
      ↥(IntermediateField.adjoin ℚ (Set.range T)) := IsFractionRing.lift injT
  have liftT_eq : ∀ x, liftT x = IsFractionRing.lift injT x := fun x => rfl
  have e0surj : Function.Surjective ⇑(hT.aevalEquivField) :=
    EquivLike.surjective (hT.aevalEquivField)
  have h2E : ∀ Q : MvPolynomial (Fin d) ℚ,
      (IntermediateField.val _).toRingHom ((hT.aevalEquivField) (algebraMap _ _ Q))
        = ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) Q :=
    fun Q => hT.aevalEquivField_algebraMap_apply_coe Q
  have surjT : Function.Surjective liftT := by
    intro Y
    obtain ⟨Z, hZ⟩ := e0surj Y
    obtain ⟨P, Q, hQ, hPQ⟩ := IsFractionRing.div_surjective (MvPolynomial (Fin d) ℚ) Z
    refine ⟨algebraMap _ _ P / algebraMap _ _ Q, ?_⟩
    have eL : (IntermediateField.val _).toRingHom (liftT (algebraMap _ _ P / algebraMap _ _ Q))
        = ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) P /
          ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) Q := by
      rw [liftT_eq, map_div₀, IsFractionRing.lift_algebraMap, IsFractionRing.lift_algebraMap,
        map_div₀, bridge, bridge]
    have eR : (IntermediateField.val _).toRingHom Y
        = ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) P /
          ((((MvPolynomial.aeval T) : MvPolynomial (Fin d) ℚ →ₐ[ℚ] K)).toRingHom) Q := by
      rw [← hZ, ← hPQ, map_div₀, map_div₀, h2E, h2E]
    have hZY : (IntermediateField.val _).toRingHom (liftT (algebraMap _ _ P / algebraMap _ _ Q))
        = (IntermediateField.val _).toRingHom Y := eL.trans eR.symm
    exact Subtype.ext hZY
  have injLiftT : Function.Injective liftT := by
    have ker0 : ∀ Z, liftT Z = 0 → Z = 0 := by
      intro Z hZ0
      obtain ⟨P, Q, hQ, hPQ⟩ := IsFractionRing.div_surjective (MvPolynomial (Fin d) ℚ) Z
      rw [← hPQ] at hZ0
      rw [liftT_eq, map_div₀, IsFractionRing.lift_algebraMap,
        IsFractionRing.lift_algebraMap] at hZ0
      have hQne : gTQ Q ≠ 0 := by
        intro hcon
        have hQ0 : Q = 0 := injT (by rw [hcon, map_zero])
        exact (mem_nonZeroDivisors_iff_ne_zero.mp hQ) hQ0
      have hP0 : gTQ P = 0 := by
        rcases div_eq_zero_iff.mp hZ0 with h | h
        · exact h
        · exact absurd h hQne
      have hP00 : P = 0 := injT (by rw [hP0, map_zero])
      rw [← hPQ, hP00, map_zero, zero_div]
    intro a b hab
    have hsub : liftT (a - b) = 0 := by rw [map_sub, hab, sub_self]
    have h0 : a - b = 0 := ker0 _ hsub
    exact sub_eq_zero.mp h0
  let req : FractionRing (MvPolynomial (Fin d) ℚ) ≃+*
      ↥(IntermediateField.adjoin ℚ (Set.range T)) :=
    RingEquiv.ofBijective liftT ⟨injLiftT, surjT⟩
  have req_fwd : ∀ x, req x = liftT x := fun x => rfl
  have keyP2aux : ∀ R : MvPolynomial (Fin d) ℤ,
      ((((MvPolynomial.aeval TE) : MvPolynomial (Fin d) ℤ →ₐ[ℤ]
        ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom) R
        = cassels_iota d T R := by
    have aevalCZ_E : ∀ r : ℤ, ((((MvPolynomial.aeval TE) : MvPolynomial (Fin d) ℤ →ₐ[ℤ]
        ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom) (MvPolynomial.C r)
        = algebraMap ℤ ↥(IntermediateField.adjoin ℚ (Set.range T)) r :=
      fun r => MvPolynomial.aeval_C _ r
    have hCa : ∀ r : ℤ, ((((MvPolynomial.aeval TE) : MvPolynomial (Fin d) ℤ →ₐ[ℤ]
        ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom) (MvPolynomial.C r)
        = cassels_iota d T (MvPolynomial.C r) := by
      intro r
      rw [aevalCZ_E]
      simp only [cassels_iota, MvPolynomial.eval₂Hom_C]
      exact RingHom.congr_fun (algebraMap_int_eq _) r
    have aevalXZ_E : ∀ i, ((((MvPolynomial.aeval TE) : MvPolynomial (Fin d) ℤ →ₐ[ℤ]
        ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom) ((MvPolynomial.X i :
        MvPolynomial (Fin d) ℤ))
        = TE i :=
      fun i => MvPolynomial.aeval_X _ i
    have hXa : ∀ i, ((((MvPolynomial.aeval TE) : MvPolynomial (Fin d) ℤ →ₐ[ℤ]
        ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom) ((MvPolynomial.X i :
        MvPolynomial (Fin d) ℤ))
        = cassels_iota d T ((MvPolynomial.X i : MvPolynomial (Fin d) ℤ)) := by
      intro i
      rw [aevalXZ_E]
      simp only [cassels_iota, MvPolynomial.eval₂Hom_X']
      rfl
    have hhom2 : ((((MvPolynomial.aeval TE) : MvPolynomial (Fin d) ℤ →ₐ[ℤ]
        ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom) = cassels_iota d T :=
      MvPolynomial.ringHom_ext hCa hXa
    exact fun R => RingHom.congr_fun hhom2 R
  have aemap : ∀ Q : MvPolynomial (Fin d) ℤ, ((((MvPolynomial.aeval TE) :
      MvPolynomial (Fin d) ℚ →ₐ[ℚ] ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom)
      (Q.map (algebraMap ℤ ℚ))
      = ((((MvPolynomial.aeval TE) : MvPolynomial (Fin d) ℤ →ₐ[ℤ]
        ↥(IntermediateField.adjoin ℚ (Set.range T)))).toRingHom) Q :=
    fun Q => MvPolynomial.aeval_map_algebraMap ℚ TE Q
  have keyP2 : ∀ P : MvPolynomial (Fin d) ℤ,
      cassels_iota d T P = liftT (algebraMap _ _ (P.map (algebraMap ℤ ℚ))) := by
    intro P
    rw [liftT_eq, IsFractionRing.lift_algebraMap, gTQhom_eq, aemap]
    exact (keyP2aux P).symm
  have key2P2 : ∀ P : MvPolynomial (Fin d) ℤ,
      (req.symm.toRingHom) (cassels_iota d T P)
        = algebraMap _ _ (P.map (algebraMap ℤ ℚ)) := by
    intro P
    rw [keyP2 P, ← req_fwd]
    exact RingEquiv.symm_apply_apply req _
  have hint : ∀ z : ℤ, PadicInt.Coe.ringHom ((z : ℤ_[p]))
      = algebraMap ℚ ℚ_[p] ((z : ℚ)) := by
    intro z
    have heq : PadicInt.Coe.ringHom.comp (Int.castRingHom ℤ_[p]) =
        (algebraMap ℚ ℚ_[p]).comp (Int.castRingHom ℚ) :=
      Subsingleton.elim _ _
    have hP := RingHom.congr_fun heq z
    rw [RingHom.comp_apply, RingHom.comp_apply] at hP
    simp only [eq_intCast] at hP
    exact hP
  have hcomp : PadicInt.Coe.ringHom.comp
        (MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ')
      = (MvPolynomial.aeval (fun i => ((τ' i : ℤ_[p]) : ℚ_[p]))).toRingHom.comp
        (MvPolynomial.map (algebraMap ℤ ℚ)) := by
    apply MvPolynomial.ringHom_ext
    · intro r
      simp only [RingHom.comp_apply, MvPolynomial.eval₂Hom_C, MvPolynomial.map_C]
      rw [show (MvPolynomial.aeval (fun i => ((τ' i : ℤ_[p]) : ℚ_[p]))).toRingHom
          (MvPolynomial.C _) = algebraMap ℚ ℚ_[p] _ from MvPolynomial.aeval_C _ _]
      simp only [eq_intCast]
      exact hint r
    · intro i
      have hXi : (((MvPolynomial.aeval (fun i => ((τ' i : ℤ_[p]) : ℚ_[p])) :
          MvPolynomial (Fin d) ℚ →ₐ[ℚ] ℚ_[p])).toRingHom)
          (MvPolynomial.X i) = ((τ' i : ℤ_[p]) : ℚ_[p]) :=
        MvPolynomial.aeval_X _ _
      rw [RingHom.comp_apply, RingHom.comp_apply, MvPolynomial.eval₂Hom_X',
        MvPolynomial.map_X, hXi]
      rfl
  have hfin : ∀ P : MvPolynomial (Fin d) ℤ,
      (MvPolynomial.aeval (fun i => ((τ' i : ℤ_[p]) : ℚ_[p]))).toRingHom
          (P.map (algebraMap ℤ ℚ))
        = ((MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) τ' P : ℤ_[p]) : ℚ_[p]) := by
    intro P
    have hPc := RingHom.congr_fun hcomp P
    exact hPc.symm
  refine ⟨(IsFractionRing.lift hinj).comp req.symm.toRingHom, fun P => ?_⟩
  rw [RingHom.comp_apply, key2P2 P, IsFractionRing.lift_algebraMap]
  exact hfin P

@[expose] public section

/-- Cassels' embedding theorem: the subring generated by a finite subset of a
characteristic-zero field embeds injectively into `ℤ_[p]` for some prime `p ≥ 3`.

J. W. S. Cassels, "An embedding theorem for fields", Bull. Austral. Math. Soc. 14
(1976), 193–198. -/
public theorem exists_injective_ringHom_closure_padicInt {K : Type*} [Field K] [CharZero K]
    (S : Finset K) :
    ∃ (p : ℕ) (hp : p.Prime),
      letI : Fact p.Prime := ⟨hp⟩
      3 ≤ p ∧ ∃ phi : Subring.closure (↑S : Set K) →+* ℤ_[p],
        Function.Injective phi := by
  classical
  obtain ⟨d, T, hT, hSalg⟩ := cassels_transcendence_basis S
  let E : IntermediateField ℚ K := IntermediateField.adjoin ℚ (Set.range T)
  obtain ⟨theta, htheta, hStheta⟩ := cassels_primitive d T S hSalg
  let L : IntermediateField ↥E K := IntermediateField.adjoin ↥E {theta}
  let gen : ↥L := IntermediateField.AdjoinSimple.gen ↥E theta
  have hpolyExists : ∀ s : ↥S, ∃ h : Polynomial ↥E,
      (⟨s.1, hStheta s.1 s.2⟩ : ↥L) = Polynomial.aeval gen h := by
    intro s
    obtain ⟨h, _, hh⟩ := (IntermediateField.adjoin.powerBasis htheta).exists_eq_aeval
      (⟨s.1, hStheta s.1 s.2⟩ : ↥L)
    refine ⟨h, ?_⟩
    simpa only [gen, IntermediateField.adjoin.powerBasis_gen] using hh
  choose hpoly hhpoly using hpolyExists
  let Z : Finset ↥E := S.attach.biUnion fun s =>
    (hpoly s).support.image fun i => (hpoly s).coeff i
  obtain ⟨q, hq, G, hGmonic, hGmap, A, B, Delta, hDelta, hBezout, hdenZ⟩ :=
    cassels_integral_model d T hT theta htheta Z
  let f : Polynomial ↥E := minpoly ↥E theta
  have hDeltaq : Delta * q ≠ 0 := mul_ne_zero hDelta hq
  obtain ⟨a, ha⟩ : ∃ a : Fin d → ℤ, MvPolynomial.eval a (Delta * q) ≠ 0 := by
    by_contra hnone
    have hzero : ∀ x : Fin d → ℤ, MvPolynomial.eval x (Delta * q) = 0 := by
      intro x
      by_contra hx
      exact hnone ⟨x, hx⟩
    have heq : Delta * q = 0 := MvPolynomial.funext fun x => by
      simpa using hzero x
    exact hDeltaq heq
  let evZ : MvPolynomial (Fin d) ℤ →+* ℤ := MvPolynomial.eval a
  let g : Polynomial ℤ := G.map evZ
  have hGdeg : G.natDegree = f.natDegree := by
    calc
      G.natDegree = (G.map (cassels_iota d T)).natDegree :=
        (hGmonic.natDegree_map (cassels_iota d T)).symm
      _ = f.natDegree := by
        rw [hGmap, Polynomial.natDegree_scaleRoots]
  have hgdeg : g.natDegree = f.natDegree := by
    calc
      g.natDegree = G.natDegree := by
        simpa only [g] using hGmonic.natDegree_map evZ
      _ = f.natDegree := hGdeg
  have hgpos : 1 ≤ g.natDegree := by
    rw [hgdeg]
    exact minpoly.natDegree_pos htheta
  have hM : evZ Delta * evZ q ≠ 0 := by
    simpa only [map_mul] using ha
  obtain ⟨p, b, hp, hp3, hpM, hpg⟩ :=
    cassels_schur g (evZ Delta * evZ q) hgpos hM
  let _ : Fact p.Prime := ⟨hp⟩
  obtain ⟨tau, htau, htauClose⟩ := cassels_transcendental_tuple p d a
  have htauNorm : ∀ i, ‖tau i‖ ≤ 1 := by
    intro i
    calc
      ‖tau i‖ = ‖(tau i - ((a i : ℤ) : ℚ_[p])) + ((a i : ℤ) : ℚ_[p])‖ := by
        rw [sub_add_cancel]
      _ ≤ max ‖tau i - ((a i : ℤ) : ℚ_[p])‖ ‖((a i : ℤ) : ℚ_[p])‖ :=
        IsUltrametricDist.norm_add_le_max _ _
      _ ≤ 1 := max_le (le_of_lt (htauClose i)) (Padic.norm_int_le_one (a i))
  let tau' : Fin d → ℤ_[p] := fun i => ⟨tau i, htauNorm i⟩
  have htau' : AlgebraicIndependent ℚ
      (fun i => (((tau' i : ℤ_[p]) : ℚ_[p]))) := by
    simpa only [tau'] using htau
  have hcongr : ∀ i, PadicInt.toZMod (tau' i) = ((a i : ℤ) : ZMod p) := by
    intro i
    have hnorm : ‖tau' i - (a i : ℤ_[p])‖ < 1 := by
      change ‖tau i - ((a i : ℤ) : ℚ_[p])‖ < 1
      exact htauClose i
    obtain ⟨w, hw⟩ := (PadicInt.norm_lt_one_iff_dvd _).mp hnorm
    have hzero : PadicInt.toZMod (tau' i - (a i : ℤ_[p])) = 0 := by
      rw [hw, map_mul]
      simp
    have hsub : PadicInt.toZMod (tau' i) - ((a i : ℤ) : ZMod p) = 0 := by
      simpa only [map_sub, map_intCast] using hzero
    exact sub_eq_zero.mp hsub
  let evP : MvPolynomial (Fin d) ℤ →+* ℤ_[p] :=
    MvPolynomial.eval₂Hom (Int.castRingHom ℤ_[p]) tau'
  let Gp : Polynomial ℤ_[p] := G.map evP
  have hGmod : PadicInt.toZMod (Gp.eval (b : ℤ_[p])) = 0 := by
    calc
      PadicInt.toZMod (Gp.eval (b : ℤ_[p])) = ((g.eval b : ℤ) : ZMod p) := by
        simpa only [Gp, evP, g, evZ] using cassels_congr_poly p d tau' a hcongr G b
      _ = 0 := (ZMod.intCast_zmod_eq_zero_iff_dvd _ p).mpr hpg
  have hGnorm : ‖Gp.eval (b : ℤ_[p])‖ < 1 := by
    have hker : Gp.eval (b : ℤ_[p]) ∈ RingHom.ker PadicInt.toZMod :=
      (RingHom.mem_ker).mpr hGmod
    rw [PadicInt.ker_toZMod, IsLocalRing.mem_maximalIdeal,
      PadicInt.mem_nonunits] at hker
    exact hker
  have hpDelta : ¬ ((p : ℤ) ∣ evZ Delta) := by
    intro hdvd
    exact hpM (dvd_mul_of_dvd_left hdvd (evZ q))
  have hDeltaMod : PadicInt.toZMod (evP Delta) ≠ 0 := by
    rw [cassels_congr_coeff p d tau' a hcongr Delta]
    intro hzero
    exact hpDelta ((ZMod.intCast_zmod_eq_zero_iff_dvd _ p).mp hzero)
  have hBezEval :
      (A.map evP).eval (b : ℤ_[p]) * Gp.eval (b : ℤ_[p]) +
        (B.map evP).eval (b : ℤ_[p]) * Gp.derivative.eval (b : ℤ_[p]) =
          evP Delta := by
    have h := congrArg
      (fun H : Polynomial (MvPolynomial (Fin d) ℤ) => (H.map evP).eval (b : ℤ_[p]))
      hBezout
    simpa only [Polynomial.map_add, Polynomial.map_mul, Polynomial.map_C,
      Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_C, Gp,
      Polynomial.derivative_map] using h
  have hDerivMod : PadicInt.toZMod (Gp.derivative.eval (b : ℤ_[p])) ≠ 0 := by
    intro hzero
    apply hDeltaMod
    have h := congrArg PadicInt.toZMod hBezEval
    simpa only [map_add, map_mul, hGmod, hzero, mul_zero, add_zero, zero_add] using h.symm
  have hDerivNorm : ‖Gp.derivative.eval (b : ℤ_[p])‖ = 1 := by
    have hnot : ¬ ‖Gp.derivative.eval (b : ℤ_[p])‖ < 1 := by
      intro hlt
      have hmax : Gp.derivative.eval (b : ℤ_[p]) ∈
          IsLocalRing.maximalIdeal ℤ_[p] :=
        (IsLocalRing.mem_maximalIdeal _).mpr ((PadicInt.mem_nonunits).mpr hlt)
      have hker : Gp.derivative.eval (b : ℤ_[p]) ∈ RingHom.ker PadicInt.toZMod := by
        rwa [PadicInt.ker_toZMod]
      exact hDerivMod ((RingHom.mem_ker).mp hker)
    exact le_antisymm (PadicInt.norm_le_one _) (not_lt.mp hnot)
  have hHensel : ‖Gp.eval (b : ℤ_[p])‖ <
      ‖Gp.derivative.eval (b : ℤ_[p])‖ ^ 2 := by
    simpa only [hDerivNorm, one_pow] using hGnorm
  obtain ⟨y, hy, _, _, _⟩ := hensels_lemma (F := Gp) (a := (b : ℤ_[p])) (by
    simpa only [Polynomial.aeval_def, Algebra.algebraMap_self,
      Polynomial.eval₂_id] using hHensel)
  have hyRoot : Gp.eval y = 0 := by
    simpa only [Polynomial.aeval_def, Algebra.algebraMap_self,
      Polynomial.eval₂_id] using hy
  obtain ⟨sigmaE, hsigmaE⟩ := cassels_specialize d T hT p tau' htau'
  let delta : ℚ_[p] := sigmaE ((cassels_iota d T) q)
  have hdelta : sigmaE ((cassels_iota d T) q) = delta := rfl
  have hfmonic : f.Monic := minpoly.monic htheta
  have hlead : sigmaE f.leadingCoeff ≠ 0 := by
    rw [hfmonic]
    simp
  have hcomp : PadicInt.Coe.ringHom.comp evP =
      sigmaE.comp (cassels_iota d T) := by
    apply DFunLike.ext _ _
    intro P
    exact (hsigmaE P).symm
  have hspec : ∀ P : MvPolynomial (Fin d) ℤ,
      sigmaE ((cassels_iota d T) P) = PadicInt.Coe.ringHom (evP P) := by
    intro P
    exact (RingHom.congr_fun hcomp P).symm
  have hGpMap : Gp.map PadicInt.Coe.ringHom =
      (f.map sigmaE).scaleRoots delta := by
    calc
      Gp.map PadicInt.Coe.ringHom =
          G.map (PadicInt.Coe.ringHom.comp evP) := by
        simpa only [Gp] using Polynomial.map_map evP PadicInt.Coe.ringHom G
      _ = G.map (sigmaE.comp (cassels_iota d T)) := by rw [hcomp]
      _ = (G.map (cassels_iota d T)).map sigmaE :=
        (Polynomial.map_map (cassels_iota d T) sigmaE G).symm
      _ = (f.scaleRoots ((cassels_iota d T) q)).map sigmaE := by rw [hGmap]
      _ = (f.map sigmaE).scaleRoots delta := by
        simpa only [hdelta] using
          Polynomial.map_scaleRoots f ((cassels_iota d T) q) sigmaE hlead
  have hpq : ¬ ((p : ℤ) ∣ evZ q) := by
    intro hdvd
    exact hpM (dvd_mul_of_dvd_right hdvd (evZ Delta))
  have hqMod : PadicInt.toZMod (evP q) ≠ 0 := by
    rw [cassels_congr_coeff p d tau' a hcongr q]
    intro hzero
    exact hpq ((ZMod.intCast_zmod_eq_zero_iff_dvd _ p).mp hzero)
  have hqNorm : ‖evP q‖ = 1 := by
    have hnot : ¬ ‖evP q‖ < 1 := by
      intro hlt
      have hmax : evP q ∈ IsLocalRing.maximalIdeal ℤ_[p] :=
        (IsLocalRing.mem_maximalIdeal _).mpr ((PadicInt.mem_nonunits).mpr hlt)
      have hker : evP q ∈ RingHom.ker PadicInt.toZMod := by
        rwa [PadicInt.ker_toZMod]
      exact hqMod ((RingHom.mem_ker).mp hker)
    exact le_antisymm (PadicInt.norm_le_one _) (not_lt.mp hnot)
  have hdeltaNorm : ‖delta‖ = 1 := by
    rw [← hdelta, hsigmaE q, ← PadicInt.norm_def]
    exact hqNorm
  have hdeltaNe : delta ≠ 0 := by
    intro hzero
    rw [hzero, norm_zero] at hdeltaNorm
    exact zero_ne_one hdeltaNorm
  have hyQ : (Gp.map PadicInt.Coe.ringHom).eval (PadicInt.Coe.ringHom y) = 0 := by
    calc
      (Gp.map PadicInt.Coe.ringHom).eval (PadicInt.Coe.ringHom y) =
          Polynomial.eval₂ PadicInt.Coe.ringHom (PadicInt.Coe.ringHom y) Gp :=
        Polynomial.eval_map PadicInt.Coe.ringHom _
      _ = PadicInt.Coe.ringHom (Gp.eval y) :=
        Polynomial.eval₂_at_apply PadicInt.Coe.ringHom y
      _ = 0 := by rw [hyRoot, map_zero]
  have hscaleRoot : ((f.map sigmaE).scaleRoots delta).eval
      (PadicInt.Coe.ringHom y) = 0 := by
    rw [← hGpMap]
    exact hyQ
  let z : ℚ_[p] := PadicInt.Coe.ringHom y / delta
  have hdz : delta * z = PadicInt.Coe.ringHom y := by
    exact mul_div_cancel₀ _ hdeltaNe
  have hz : Polynomial.eval₂ sigmaE z f = 0 := by
    have hprod : delta ^ f.natDegree * Polynomial.eval₂ sigmaE z f = 0 := by
      calc
        delta ^ f.natDegree * Polynomial.eval₂ sigmaE z f =
            Polynomial.eval₂ sigmaE (delta * z)
              (f.scaleRoots ((cassels_iota d T) q)) := by
          symm
          simpa only [hdelta] using
            Polynomial.scaleRoots_eval₂_mul sigmaE z ((cassels_iota d T) q)
        _ = ((f.map sigmaE).scaleRoots delta).eval (delta * z) := by
          rw [Polynomial.eval₂_eq_eval_map,
            Polynomial.map_scaleRoots f ((cassels_iota d T) q) sigmaE hlead]
        _ = 0 := by rw [hdz, hscaleRoot]
    exact (mul_eq_zero.mp hprod).resolve_left (pow_ne_zero _ hdeltaNe)
  obtain ⟨sigma, hsigmaBase, hsigmaGen⟩ :=
    cassels_extend E theta htheta p sigmaE z (by simpa only [f] using hz)
  have hcoeffZ : ∀ (s : ↥S) (i : ℕ), i ∈ (hpoly s).support →
      (hpoly s).coeff i ∈ Z := by
    intro s i hi
    exact Finset.mem_biUnion.mpr ⟨s, Finset.mem_attach _ s,
      Finset.mem_image.mpr ⟨i, hi, rfl⟩⟩
  have hsigmaENorm : ∀ e ∈ Z, ‖sigmaE e‖ ≤ 1 := by
    intro e he
    obtain ⟨P, hP⟩ := hdenZ e he
    have hmap := congrArg sigmaE hP
    have hmul : delta * sigmaE e = PadicInt.Coe.ringHom (evP P) := by
      calc
        delta * sigmaE e = sigmaE ((cassels_iota d T) q) * sigmaE e := by rw [hdelta]
        _ = sigmaE ((cassels_iota d T) q * e) := (map_mul sigmaE _ _).symm
        _ = sigmaE ((cassels_iota d T) P) := hmap
        _ = PadicInt.Coe.ringHom (evP P) := hspec P
    have hsolve : sigmaE e = PadicInt.Coe.ringHom (evP P) / delta := by
      apply (eq_div_iff hdeltaNe).mpr
      rw [mul_comm]
      exact hmul
    rw [hsolve, norm_div, hdeltaNorm, div_one]
    exact (evP P).property
  have hcoeffNorm : ∀ (s : ↥S) (i : ℕ),
      ‖sigmaE ((hpoly s).coeff i)‖ ≤ 1 := by
    intro s i
    by_cases hi : i ∈ (hpoly s).support
    · exact hsigmaENorm _ (hcoeffZ s i hi)
    · have hzero : (hpoly s).coeff i = 0 := by
        simpa only [Polynomial.mem_support_iff, not_ne_iff] using hi
      rw [hzero, map_zero, norm_zero]
      exact zero_le_one
  have hzNorm : ‖z‖ ≤ 1 := by
    change ‖PadicInt.Coe.ringHom y / delta‖ ≤ 1
    rw [norm_div, hdeltaNorm, div_one]
    exact y.property
  have hevalMem : ∀ s : ↥S,
      ((hpoly s).map sigmaE).eval z ∈ PadicInt.subring p := by
    intro s
    rw [Polynomial.eval_map, Polynomial.eval₂_eq_sum_range]
    apply (PadicInt.subring p).sum_mem
    intro i hi
    apply (PadicInt.subring p).mul_mem
    · exact hcoeffNorm s i
    · exact (PadicInt.subring p).pow_mem hzNorm i
  have hsigmaComp : sigma.comp (algebraMap ↥E ↥L) = sigmaE := by
    apply DFunLike.ext _ _
    intro e
    exact hsigmaBase e
  have hsigmaGen' : sigma gen = z := by
    simpa only [gen] using hsigmaGen
  have hsigmaEval : ∀ s : ↥S,
      sigma (⟨s.1, hStheta s.1 s.2⟩ : ↥L) =
        Polynomial.eval₂ sigmaE z (hpoly s) := by
    intro s
    rw [hhpoly s, Polynomial.aeval_def]
    calc
      sigma (Polynomial.eval₂ (algebraMap ↥E ↥L) gen (hpoly s)) =
          Polynomial.eval₂ (sigma.comp (algebraMap ↥E ↥L))
            (sigma gen) (hpoly s) :=
        Polynomial.hom_eval₂ (hpoly s) (algebraMap ↥E ↥L) sigma gen
      _ = Polynomial.eval₂ sigmaE z (hpoly s) := by
        rw [hsigmaComp, hsigmaGen']
  have hSmem : ∀ s : ↥S,
      sigma (⟨s.1, hStheta s.1 s.2⟩ : ↥L) ∈ PadicInt.subring p := by
    intro s
    rw [hsigmaEval s, Polynomial.eval₂_eq_eval_map]
    exact hevalMem s
  let goodL : Subring ↥L := (PadicInt.subring p).comap sigma
  let goodK : Subring K := goodL.map (IntermediateField.val L).toRingHom
  have hSgood : (↑S : Set K) ⊆ goodK := by
    intro s hs
    let ss : ↥S := ⟨s, Finset.mem_coe.mp hs⟩
    let sl : ↥L := ⟨s, hStheta s ss.property⟩
    have hsl : sl ∈ goodL := by
      change sigma sl ∈ PadicInt.subring p
      simpa only [sl, ss] using hSmem ss
    exact ⟨sl, hsl, rfl⟩
  have hclosureGood : Subring.closure (↑S : Set K) ≤ goodK :=
    (Subring.closure_le).mpr hSgood
  have hS_L : (↑S : Set K) ⊆ L.toSubring := by
    intro s hs
    exact hStheta s (Finset.mem_coe.mp hs)
  have hclosureL : Subring.closure (↑S : Set K) ≤ L.toSubring :=
    (Subring.closure_le).mpr hS_L
  let inc : Subring.closure (↑S : Set K) →+* ↥L := Subring.inclusion hclosureL
  let rho : Subring.closure (↑S : Set K) →+* ℚ_[p] := sigma.comp inc
  have hrhoMem : ∀ x, rho x ∈ PadicInt.subring p := by
    intro x
    have hxgood : (x.1 : K) ∈ goodK := hclosureGood x.property
    obtain ⟨y, hy, hval⟩ := hxgood
    have hinc : inc x = y := by
      apply Subtype.ext
      exact hval.symm
    change sigma (inc x) ∈ PadicInt.subring p
    rw [hinc]
    exact hy
  let phi : Subring.closure (↑S : Set K) →+* ℤ_[p] :=
    rho.codRestrict (PadicInt.subring p) hrhoMem
  have hrhoInj : Function.Injective rho := by
    intro x₁ x₂ hxy
    have hsigma : sigma (inc x₁) = sigma (inc x₂) := by
      simpa only [rho, RingHom.comp_apply] using hxy
    have hinc : inc x₁ = inc x₂ := (RingHom.injective sigma) hsigma
    have hincval : ∀ x, ((inc x : L) : K) = (x : K) := by
      intro x
      exact Subring.coe_inclusion hclosureL x
    apply Subtype.ext
    exact (hincval x₁).symm.trans
      ((congrArg (fun w : ↥L => (w : K)) hinc).trans (hincval x₂))
  have hphiInj : Function.Injective phi := by
    intro x₁ x₂ hxy
    apply hrhoInj
    change (phi x₁ : ℚ_[p]) = (phi x₂ : ℚ_[p])
    exact congrArg (fun w : ℤ_[p] => (w : ℚ_[p])) hxy
  refine ⟨p, hp, hp3, phi, hphiInj⟩

end

end Subring
