module

public import Mathlib.FieldTheory.Galois.Basic
public import Mathlib.RingTheory.Trace.Basic

@[expose] public section

/-!
# Additive Hilbert 90 for a cyclic Galois extension

Let `L / K` be a Galois extension whose Galois group is generated by `σ`. Then the kernel of
the field trace `Tr_{L/K}` is the image of `σ - 1`:

`ker (Tr_{L/K}) = range (σ - 1)`.

This is Theorem 24.1(i) of MIT 18.785 (Number Theory I), Lecture 24. Mathlib proves trace
surjectivity and multiplicative Hilbert 90 in `Mathlib.FieldTheory.Galois.Hilbert90`, where
additive Hilbert 90 is listed as future work; this module fills that gap for cyclic Galois
groups, without any group-cohomology packaging.

## Proof outline

The inclusion `range (σ - 1) ≤ ker Tr` follows from trace invariance under automorphisms.
Both sides then have complementary finrank: `ker (σ - 1)` is the base field (an element
fixed by `σ` is fixed by every automorphism, hence lies in `K` for a Galois extension), so
it has `K`-finrank one; `range Tr` is all of `K` by trace surjectivity, so it also has
`K`-finrank one. Rank-nullity applied to both maps then forces the inclusion to be an
equality.
-/

variable {K L : Type*} [Field K] [Field L] [Algebra K L] [FiniteDimensional K L]
  [IsGalois K L]

namespace Algebra

omit [FiniteDimensional K L] [IsGalois K L] in
/-- A natural-number power of `σ` fixes every point fixed by `σ`. -/
private theorem pow_fix (σ : L ≃ₐ[K] L) (x : L) (hx : σ x = x) (n : ℕ) :
    (σ ^ n) x = x := by
  induction n with
  | zero => simp
  | succ n ih => rw [pow_succ, AlgEquiv.mul_apply, hx, ih]

omit [FiniteDimensional K L] [IsGalois K L] in
/-- An inverse natural-number power of `σ` fixes every point fixed by `σ`. -/
private theorem inv_pow_fix (σ : L ≃ₐ[K] L) (x : L) (hx : σ x = x) (n : ℕ) :
    ((σ ^ n)⁻¹) x = x := by
  have hinv : σ⁻¹ x = x := by
    have h1 : (σ⁻¹ * σ) x = x := by rw [inv_mul_cancel, AlgEquiv.one_apply]
    rw [AlgEquiv.mul_apply] at h1
    rw [hx] at h1
    exact h1
  induction n with
  | zero => simp
  | succ n ih => rw [pow_succ, mul_inv_rev, AlgEquiv.mul_apply, ih, hinv]

omit [FiniteDimensional K L] [IsGalois K L] in
/-- An integral power of `σ` fixes every point fixed by `σ`. -/
private theorem zpow_fix (σ : L ≃ₐ[K] L) (x : L) (hx : σ x = x) (n : ℤ) :
    (σ ^ n) x = x := by
  obtain ⟨m, rfl | rfl⟩ := Int.eq_nat_or_neg n
  · rw [zpow_natCast]
    exact pow_fix σ x hx m
  · rw [zpow_neg, zpow_natCast]
    exact inv_pow_fix σ x hx m

/-- Additive Hilbert 90 for a cyclic Galois extension: the trace kernel is the image of
`σ - 1` when `σ` generates the Galois group. -/
theorem ker_trace_eq_range_algEquiv_sub_id (σ : L ≃ₐ[K] L)
    (hσ : ∀ τ : L ≃ₐ[K] L, τ ∈ Subgroup.zpowers σ) :
    LinearMap.ker (Algebra.trace K L) =
      LinearMap.range (σ.toLinearMap - LinearMap.id) := by
  have hle : LinearMap.range (σ.toLinearMap - LinearMap.id) ≤
      LinearMap.ker (Algebra.trace K L) := by
    intro y hy
    obtain ⟨x, rfl⟩ := LinearMap.mem_range.mp hy
    rw [LinearMap.mem_ker, LinearMap.sub_apply, AlgEquiv.toLinearMap_apply,
      LinearMap.id_apply, map_sub, Algebra.trace_eq_of_algEquiv, sub_self]
  have hker : LinearMap.ker (σ.toLinearMap - LinearMap.id) =
      (⊥ : IntermediateField K L).toSubmodule := by
    ext x
    have hmem : (x ∈ (⊥ : IntermediateField K L).toSubmodule) ↔
        x ∈ (⊥ : IntermediateField K L) :=
      Iff.rfl
    simp only [LinearMap.mem_ker, LinearMap.sub_apply, AlgEquiv.toLinearMap_apply,
      LinearMap.id_apply, sub_eq_zero, hmem, IsGalois.mem_bot_iff_fixed]
    constructor
    · intro hx τ
      obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp (hσ τ)
      rw [← hn]
      exact zpow_fix σ x hx n
    · intro hx
      exact hx σ
  have hrange_top : LinearMap.range (Algebra.trace K L) = ⊤ :=
    LinearMap.range_eq_top.mpr (Algebra.trace_surjective K L)
  have htr1 : Module.finrank K (LinearMap.range (Algebra.trace K L)) = 1 := by
    rw [hrange_top, finrank_top]
    exact Module.finrank_self K
  have hker1 :
      Module.finrank K (LinearMap.ker (σ.toLinearMap - LinearMap.id)) = 1 := by
    rw [hker]
    exact IntermediateField.finrank_bot
  have hdim1 := LinearMap.finrank_range_add_finrank_ker (σ.toLinearMap - LinearMap.id)
  have hdim2 := LinearMap.finrank_range_add_finrank_ker (Algebra.trace K L)
  have hfin : Module.finrank K (LinearMap.ker (Algebra.trace K L)) ≤
      Module.finrank K (LinearMap.range (σ.toLinearMap - LinearMap.id)) := by
    omega
  exact (Submodule.eq_of_le_of_finrank_le hle hfin).symm

/-- Pointwise additive Hilbert 90: every trace-zero element is a `σ`-coboundary. -/
theorem exists_algEquiv_sub_eq_of_trace_eq_zero (σ : L ≃ₐ[K] L)
    (hσ : ∀ τ : L ≃ₐ[K] L, τ ∈ Subgroup.zpowers σ) {x : L}
    (hx : Algebra.trace K L x = 0) :
    ∃ y : L, σ y - y = x := by
  have hmem : x ∈ LinearMap.ker (Algebra.trace K L) := LinearMap.mem_ker.mpr hx
  rw [ker_trace_eq_range_algEquiv_sub_id σ hσ] at hmem
  obtain ⟨y, hy⟩ := LinearMap.mem_range.mp hmem
  exact ⟨y, by
    simpa only [LinearMap.sub_apply, AlgEquiv.toLinearMap_apply, LinearMap.id_apply]
      using hy⟩

end Algebra
