module

public import MathlibExt.GroupTheory.GroupGrowth

@[expose] public section

/-- Ordinary case: every generating family of a finite group has polynomial growth. -/
example (G ι : Type*) [Group G] [Finite G] (P : Group.Generators G ι) :
    P.HasPolynomialGrowth :=
  P.hasPolynomialGrowth_of_finite

/-- Boundary case: the ball of radius `0` has exactly one element. -/
example (G ι : Type*) [Group G] (P : Group.Generators G ι) :
    P.growth 0 = 1 :=
  P.growth_zero

/-- Regression (infinite group, finite generating family): the integers under the
multiplicative notation, generated by `1` in the `Fin 1` family, have radius-`0` growth `1`;
the finiteness side-condition of `HasPolynomialGrowth` is what excludes the junk
`Nat.card = 0` readings for infinite balls. -/
example :
    letI P : Group.Generators (Multiplicative ℤ) (Fin 1) :=
      ⟨fun _ => Multiplicative.ofAdd 1, by
        rw [Subgroup.eq_top_iff']
        intro g
        obtain ⟨n, hn⟩ : ∃ n : ℤ, g = Multiplicative.ofAdd n :=
          ⟨Multiplicative.toAdd g, by simp⟩
        rw [hn]
        have hgen : Multiplicative.ofAdd n = (Multiplicative.ofAdd (1 : ℤ)) ^ n := by
          simpa using (ofAdd_zsmul n (1 : ℤ))
        rw [hgen]
        exact zpow_mem (Subgroup.subset_closure (by simp)) n⟩
    P.growth 0 = 1 :=
  Group.Generators.growth_zero _
